---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: BlueXP backup and recovery服務需要先發現數據，您才能使用該服務。在發現過程中， BlueXP backup and recovery會分析您組織內工作環境中的所有磁碟區和檔案。 
---
= BlueXP backup and recoveryMicrosoft SQL Server 工作負載的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== 僅限標準部署模式

BlueXP backup and recovery版本僅在標準部署模式下運作，不適用於受限或私人模式。



== Windows 群集名稱限制

Windows 叢集名稱不能包含底線 (_) 字元。



== SnapCenter遷移問題

將資源從SnapCenter遷移到BlueXP backup and recovery有以下限制。

有關SnapCenter策略如何遷移到BlueXP backup and recovery策略的詳細信息，請參閱link:reference-policy-differences-snapcenter.html["SnapCenter中的策略與BlueXP backup and recovery中的策略比較"] 。



=== 資源組限制

如果資源組中的所有資源都受到保護，並且其中一個資源在資源組外部也受到保護，則從SnapCenter遷移將會被阻止。

*解決方法*：在資源群組中或單獨保護資源，但不能同時保護兩者。



=== 不支援使用相同計劃層的多個策略的資源

您無法為一個資源指派多個使用相同計畫層級（例如，每小時、每天、每週等）的策略。 BlueXPBlueXP backup and recovery不會從SnapCenter匯入這些資源。

*解決方法*：僅將使用相同計劃層的一項策略附加到資源。



=== 每小時保單必須從每小時開始時開始

如果您的SnapCenter策略每小時重複一次，但小時數並非以小時為間隔，BlueXP backup and recovery將不會匯入該資源。例如，不支援計劃時間為 1:30、2:30、3:30 等的策略，但支援計劃時間為 1:00、2:00、3:00 等的策略。

*解決方法*：使用從整點開始以 1 小時為間隔重複的策略。



=== 不支援將每日和每月策略附加到同一個資源

如果SnapCenter策略以天和月為間隔重複，則BlueXP backup and recovery將不會匯入該原則。

例如，您無法將每日策略（少於或等於 7 天或大於 7 天）附加到資源，也無法將每月策略附加到相同資源。

*解決方法*：使用以每日或每月為間隔的策略，但不能同時使用兩者。



=== 按需備份策略未遷移

BlueXP backup and recovery不會從SnapCenter匯入按需備份原則。



=== 僅日誌備份策略未遷移

BlueXP backup and recovery不會從SnapCenter匯入僅日誌備份原則。如果SnapCenter政策包含僅日誌備份，BlueXP backup and recovery將不會匯入該資源。

*解決方法*：在SnapCenter中使用不僅僅使用日誌備份的政策。



=== 主機對應

SnapCenter無法將資源的儲存叢集或 SVM 對應到主機，但BlueXP backup and recovery可以。在BlueXP backup and recovery預覽版中，本機ONTAP叢集或 SVM 不會對應到主機。此外， BlueXP不支援 SVM。

*解決方法*：在從SnapCenter匯入資源之前，請在BlueXP backup and recovery中為所有在本機SnapCenter中註冊的本機ONTAP儲存系統建立一個工作環境。然後，將該叢集的資源從SnapCenter匯入BlueXP backup and recovery。



=== 班次間隔不為 15 分鐘

如果您有一個SnapCenter策略計劃，該計劃在特定時間啟動並每隔幾分鐘重複一次，但間隔時間不是 15 分鐘，BlueXP backup and recovery將不會匯入該計劃。

*解決方法*：使用SnapCenter調整策略，使其以 15 分鐘的間隔重複。



=== 日誌備份保留

使用SnapCenter，您可以在附加到資源的多個政策中設定多個保留值。但是， BlueXP backup and recovery預覽版僅支援對附加到資源的所有策略使用單一保留值。
