---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= BlueXP backup and recovery的常見問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 部署

*您需要許可證才能使用BlueXP備份和還原預覽版嗎？ *

您可以使用下列授權類型：

* 註冊 30 天免費試用。


*如何啟用BlueXP backup and recovery？ *BlueXP backup and recovery無需任何啟用。備份和復原選項會在BlueXP左側導覽列中自動啟用。

若要開始使用、您必須註冊或聯絡 NetApp 銷售代表、才能試用這項服務。然後、當您使用 BlueXP Connector 時、它會包含該服務的適當功能。

若要開始使用BlueXP backup and recovery，請在其初始登入頁面上按一下「開始發現工作負載」。

* BlueXP backup and recovery是否在標準、受限和私人模式下可用？ *目前， BlueXP backup and recovery預覽版僅在標準模式下可用。敬請期待更多資訊。

有關所有 BlueXP  服務中這些模式的說明，請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 部署模式"^]。



== 存取

* BlueXP backup and recoveryURL 是什麼？ *對於 URL 、在瀏覽器中輸入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/backup-and-recovery"^] 以存取 BlueXP  主控台。

* 如何處理存取權限？ *只有組織管理員才能啟動服務並探索工作負載（因為這涉及使用資源）。後續互動可由任何角色執行。

* 哪種裝置解析度最佳？ *BlueXP backup and recovery的建議裝置解析度為 1920x1080 或更高。

* 我應該使用哪個瀏覽器？ *任何現代化的瀏覽器都能正常運作。



== 與其他服務互動

* BlueXP backup and recovery是否知道NetApp ONTAP中所做的保護設定？ *是的， BlueXP backup and recovery可以發現ONTAP中設定的快照計劃。

*如果您使用BlueXP backup and recovery設定策略，那麼您是否只需在此服務中進行將來的變更？ *我們建議您從BlueXP backup and recovery服務進行政策變更。



== 工作負載

* 工作負載的組成為何？ *工作負載是指 2025 預覽版中的應用程式。工作負載包括單一應用程式執行個體所使用的所有磁碟區。例如，部署在 mssql3.host.com 上的 Microsoft SQL Server 資料庫執行個體可以分別使用 vol1 和 vol2 來儲存其資料和日誌。這些磁碟區共同構成了該資料庫執行個體的工作負載。

* BlueXP backup and recovery支援哪些工作負載？ *

對於預覽版 2025， BlueXP backup and recovery可以識別下列工作負載：Microsoft SQL Server 應用程式。

* 什麼是「受保護的」工作負載？ *在BlueXP backup and recovery中，當啟用主要偵測策略時，工作負載將顯示「受保護」狀態。

* 什麼是「面臨風險」工作負載？ *如果工作負載未啟用主要偵測原則、即使已啟用備份和快照原則、也會有「風險」。

*新增了新的工作負載，但尚未出現* 如果您在環境中新增了新的工作負載，請再次啟動發現並套用保護策略來保護該新資源。



== 保護原則

* BlueXP backup and recovery是否能夠識別NetApp ONTAP中的保護設定？ *

是的， BlueXP backup and recovery會發現在ONTAP中設定的快照計畫以及在發現的工作負載中是否啟用了 ARP 和 FPolicy。您最初在儀表板中看到的資訊會從其他 NetApp 解決方案和產品中彙總。

* BlueXP backup and recovery是否知道SnapCenter中已經制定的策略？ *

是的，如果您在SnapCenter中管理工作負載，則這些產品管理的策略將納入BlueXP backup and recovery。

*您可以修改從SnapCenter繼承的策略嗎？ *

是的，您可以修改BlueXP backup and recovery中由SnapCenter管理的政策。

*如果ONTAP中存在策略（已在系統管理員中啟用，例如 ARP、FPolicy 和快照），那麼這些策略是否會在BlueXP backup and recovery中變更？ *

不會。 BlueXPBlueXP backup and recovery不會修改ONTAP的任何現有偵測策略（ARP、FPolicy 設定）。

*註冊BlueXP backup and recovery後，如果在SnapCenter中新增政策會發生什麼情況？ *

BlueXP backup and recovery可識別在SnapCenter中建立的任何新政策。

* 您可以從 ONTAP 變更原則嗎？ *

是的，您可以在BlueXP backup and recovery中變更ONTAP策略。您也可以在BlueXP backup and recovery中建立新政策並將其套用至工作負載。此操作會將現有ONTAP策略替換為在BlueXP backup and recovery中所建立的政策。
