---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Kubernetes 
summary: BlueXP backup and recovery服務需要先發現工作負載，您才能使用該服務。 
---
= 在BlueXP backup and recovery中發現 Kubernetes 工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recovery服務需要先發現 Kubernetes 工作負載，您才能使用該服務。

*所需的BlueXP角色* 此任務需要資料服務備份和還原超級管理員角色。了解link:reference-roles.html["備份和恢復資料服務角色和權限"]。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服務的 BlueXP 存取角色"^] 。



== 發現 Kubernetes 工作負載

在備份和復原清單中，您可以發現環境中正在執行的 Kubernetes 工作負載。發現工作負載會將 Kubernetes 叢集新增至BlueXP backup and recovery，使您能夠將應用程式新增至該叢集並保護該叢集託管的資源。

.步驟
. 執行下列其中一項：
+
** 如果您是第一次發現 Kubernetes 工作負載，請在BlueXP backup and recovery中，選擇 Kubernetes 工作負載類型下的 *發現和管理*。
** 如果您已經發現 Kubernetes 工作負載，請在BlueXP backup and recovery中選擇 *Inventory* > *Workloads*，然後選擇 *Discover resources*。


. 選擇 *Kubernetes* 工作負載類型。
. 輸入叢集名稱並選擇與叢集一起使用的連接器。
. 按照出現的命令列說明進行操作：
+
** 建立Trident保護命名空間
** 建立 Kubernetes 機密
** 新增 Helm 儲存庫
** 安裝Trident Protect 和Trident Protect 連接器
+
這些步驟確保BlueXP backup and recovery可以與叢集互動。



. 完成這些步驟後，選擇*發現*。
+
該集群已新增至清單。

. 在關聯的 Kubernetes 工作負載中選擇「檢視」以查看該工作負載的應用程式、叢集和命名空間清單。




== 繼續前往BlueXP backup and recovery儀表板

若要顯示BlueXP backup and recovery儀表板，請依照下列步驟操作。

. 從頂部選單中選擇*儀表板*。
. 檢查資料保護的運作狀況。處於風險或受保護的工作負載的數量會根據新發現、受保護和備份的工作負載的數量而增加。
+
link:br-use-dashboard.html["了解儀表板顯示的內容"]。


