---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 您可以將 Microsoft SQL Server 應用程式資料從本機ONTAP系統備份到 Amazon Web Services、Microsoft Azure 和StorageGRID，以確保資料受到保護。備份會自動產生、並儲存在公有雲或私有雲帳戶的物件存放區中。您可以實施 3-2-1 策略，即在 2 個不同的儲存系統上保留 3 個來源資料副本，並在雲端保留 1 個副本。 
---
= 使用BlueXP backup and recovery保護 Microsoft SQL 工作負載概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用BlueXP backup and recovery，保護您的 Microsoft SQL Server 應用程式數據，使其從本機ONTAP系統遷移到 Amazon Web Services、Microsoft Azure 或StorageGRID 。備份將根據您建立的策略自動產生並儲存在您的公有雲或私有雲帳戶的物件儲存中。您可以實施 3-2-1 策略，即在 2 個不同的儲存系統上保留 3 個來源資料副本，並在雲端保留 1 個副本。

3-2-1 方法的優點包括：

* 多個資料複本可提供多層保護、抵禦內部（內部）和外部網路安全威脅。
* 多種媒體類型可確保容錯移轉在某種媒體類型的實體或邏輯故障情況下可行。
* 現場副本有助於快速恢復，而異地副本則可在現場副本受損時使用。


BlueXP backup and recovery利用NetApp SnapMirror資料複製技術，透過建立快照副本並將其傳輸到備份位置來確保所有備份完全同步。

您可以實現以下保護目標：

* link:concept-start-prereq-snapcenter-import.html["如果從SnapCenter匯入，請配置其他項目"]
* link:br-start-discover.html["發現 Microsoft SQL Server 工作負載並選擇性地匯入SnapCenter資源"]
* link:br-use-mssql-backup.html["使用本機ONTAP主儲存上的本機快照備份工作負載"]
* link:br-use-mssql-backup.html["將工作負載複製到ONTAP二級存儲"]
* link:br-use-mssql-backup.html["將工作負載備份到物件儲存位置"]
* link:br-use-mssql-backup.html["立即備份工作負載"]
* link:br-use-mssql-restore-overview.html["恢復工作負載"]
* link:br-use-mssql-clone.html["克隆工作負載"]
* link:br-use-manage-inventory.html["管理工作負載清單"]
* link:br-use-manage-snapshots.html["管理快照"]


要備份工作負載，通常需要建立管理備份和復原作業的策略。如需詳細資訊、請參閱 link:br-use-policies-create.html["建立原則"] 。

.支援的備份目的地
BlueXP backup and recovery可讓您將 Microsoft SQL Server 執行個體和資料庫從下列來源工作環境備份到下列輔助工作環境和公有和私有雲供應商中的物件儲存。Snapshot 複本位於來源工作環境中。

[cols="33,33,33"]
|===
| 來源工作環境 | 次要工作環境（複寫） | 目的地物件存放區（備份） 


| AWS 中的 Cloud Volumes ONTAP | AWS 中的 Cloud Volumes ONTAP
內部部署 ONTAP 的作業系統 | Amazon S3 


| Azure 中的 Cloud Volumes ONTAP | Azure 中的 Cloud Volumes ONTAP
內部部署 ONTAP 的作業系統 | Azure Blob 


| 內部部署 ONTAP 的作業系統 | Cloud Volumes ONTAP
內部部署 ONTAP 的作業系統 | Amazon S3 Azure Blob NetApp StorageGRID ifdef::gcp[] endif::gcp[] ifdef::gcp[] endif::gcp[] 
|===
.支援的還原目的地
您可以將 Microsoft SQL Server 執行個體和資料庫從駐留在主儲存或輔助工作環境（複製磁碟區）或物件儲存（備份檔案）中的備份還原到下列工作環境。Snapshot 複本位於來源工作環境中、只能還原至相同的系統。

[cols="33,33,33"]
|===
2+| 從備份檔案位置 | 目標工作環境 


| * 物件存放區（備份） * | * 次系統（複寫） * |  


| Amazon S3 | AWS 中的 Cloud Volumes ONTAP
內部部署 ONTAP 的作業系統 | AWS 本機ONTAP系統中的 Cloud Volumes 


| Azure Blob | Azure 中的 Cloud Volumes ONTAP
內部部署 ONTAP 的作業系統 | Azure 本地ONTAP系統中的Cloud Volumes ONTAP ifdef::gcp[] endif::gcp[] 


| StorageGRID | Cloud Volumes ONTAP
內部部署 ONTAP 的作業系統 | 內部部署 ONTAP 的作業系統 
|===

NOTE: 「本地ONTAP系統」包括FAS和AFF系統。
