---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: BlueXP backup and recovery可讓您管理工作負載主機資訊、資料庫資訊和執行個體資訊。您可以查看、編輯和刪除庫存的保護設定。 
---
= 新增和保護 Kubernetes 應用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recovery可讓您管理工作負載主機資訊、資料庫資訊和執行個體資訊。您可以查看、編輯和刪除庫存的保護設定。

.所需的BlueXP角色
組織管理員或SnapCenter管理員。link:reference-roles.html["了解BlueXP backup and recovery存取角色"] 。  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服務的 BlueXP 存取角色"^] 。



== 新增並保護新的 Kubernetes 應用程式

保護 Kubernetes 應用程式的第一步是在BlueXP backup and recovery中建立應用程式。在建立應用程式時，您可以讓BlueXP感知 Kubernetes 叢集上正在執行的應用程式。

.步驟
. 在BlueXP backup and recovery中，選擇 *Inventory* > *Applications*。
. 選擇*建立應用程式*。
. 輸入應用程式的名稱。
. 選擇以下任意欄位來搜尋您想要保護的資源：
+
** 關聯集群
** 關聯的命名空間
** 資源類型
** 標籤選擇器


. （可選）選擇「叢集範圍資源」****，以選擇任何叢集等級範圍且未包含在應用程式中的資源。如果包含這些資源，它們會在建立應用程式時新增到應用程式中。
. 選擇*搜尋*以根據您的搜尋條件尋找資源。
. BlueXP顯示符合您的搜尋條件的資源清單。
. 如果清單包含您想要保護的資源，請選擇「*下一步*」。
. 在「*策略*」區域中，選擇現有的保護策略來保護應用程式或建立新策略。
. 在「*腳本和後記*」區域中，啟用並設定任何要在備份作業之前或之後執行的腳本或後記執行掛鉤。若要啟用腳本或後記，您必須已建立至少一個link:br-use-manage-execution-hook-templates.html["執行鉤子模板"] 。
. 選擇* Create *（建立*）。


.結果
應用程式已建立並顯示在 Kubernetes 清單的「應用程式」標籤中的應用程式清單中。 BlueXPBlueXP根據您的設定啟用應用程式保護，您可以在備份和還原的「監控」區域中監控進度。



== 保護現有的 Kubernetes 應用程式

在已新增的 Kubernetes 應用程式上啟用保護策略。

.步驟
. 在BlueXP backup and recovery中，選擇 *Inventory* > *Applications*。
. 在應用程式清單中，選擇您想要保護的應用程式並選擇相關的操作選單。
. 選取 * 保護 * 。
. 在「*策略*」區域中，選擇現有的保護策略來保護應用程式或建立新策略。
. 在「*前言和後記*」區域中，啟用並設定任何要在備份作業之前或之後執行的前言或後記執行鉤子。您可以配置執行鉤子的類型、它使用的模板、參數和標籤選擇器。
. 選擇*完成*。


.結果
BlueXP根據您的設定啟用對應用程式的保護，並且您可以在備份和還原的*監控*區域中監控進度。



== 立即備份 Kubernetes 應用程式

手動建立 Kubernetes 應用程式的備份，為未來的備份和快照建立基線，或確保最新資料受到保護。

.步驟
. 在BlueXP backup and recovery中，選擇 *Inventory* > *Applications*。
. 在應用程式清單中，選擇要備份的應用程式並選擇相關的操作選單。
. 選擇*立即備份*。
. 確保選擇了正確的應用程式名稱。
. 從策略清單中選擇一個保護策略。
. 選取 * 備份 * 。

