---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: BlueXP backup and recovery可讓您管理執行掛鉤，以便在應用程式保護作業之前或之後採取行動。 
---
= 管理 Kubernetes 工作負載的BlueXP backup and recovery執行掛鉤模板
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
執行鉤子是一種自訂操作，您可以將其配置為與託管 Kubernetes 應用程式的資料保護操作一起運行。例如、如果您有資料庫應用程式、您可以使用執行掛勾來暫停快照之前的所有資料庫交易、並在快照完成後繼續交易。如此可確保應用程式一致的快照。建立執行鉤子範本時，您可以指定鉤子的類型、要執行的腳本以及用於確定該鉤子適用哪些容器的篩選條件。然後，您可以使用該模板將執行鉤子與您的應用程式關聯。

.所需的BlueXP角色
組織管理員或SnapCenter管理員。link:reference-roles.html["了解BlueXP backup and recovery存取角色"] 。  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服務的 BlueXP 存取角色"^] 。



== 執行掛勾的類型

BlueXP backup and recovery根據其運行時間支援以下類型的執行掛鉤：

* 快照前
* 快照後
* 預先備份
* 備份後
* 還原後




=== 執行順序

執行資料保護作業時、執行掛機事件會依照下列順序發生：

. 任何適用的自訂操作前執行掛勾都會在適當的容器上執行。您可以視需要建立及執行任意數量的自訂操作前掛勾、但在作業之前執行這些掛勾的順序既不保證也無法設定。
. 如果適用，檔案系統會凍結。
. 執行資料保護作業。
. 凍結的檔案系統會在適用的情況下解除凍結。
. 任何適用的自訂操作後執行掛勾都會在適當的容器上執行。您可以視需要建立及執行任意數量的自訂後置作業掛勾、但在作業後執行這些掛勾的順序並不保證也無法設定。


如果您建立同一類型的多個執行掛勾（例如預先快照）、則無法保證這些掛勾的執行順序。不過、不同類型的掛勾的執行順序也有保證。例如，以下是具有所有不同類型勾點的組態執行順序：

. 執行快照前掛勾
. 快照後掛勾已執行
. 執行備份前掛勾
. 執行備份後掛勾



NOTE: 上述順序範例僅適用於執行不使用現有快照的備份時。


NOTE: 在正式作業環境中啟用執行攔截指令碼之前、請務必先進行測試。您可以使用'kubecl exec'命令來方便地測試指令碼。在正式作業環境中啟用執行掛勾之後、請測試所產生的快照和備份、以確保它們一致。您可以將應用程式複製到暫用命名空間、還原快照或備份、然後測試應用程式、藉此完成此作業。


NOTE: 如果快照前執行攔截器新增，變更或移除 Kubernetes 資源，則這些變更會包含在快照或備份中，以及任何後續還原作業中。



== 關於自訂執行掛勾的重要注意事項

規劃應用程式的執行掛勾時、請考量下列事項。

* 執行攔截必須使用指令碼來執行動作。許多執行掛勾可以參照相同的指令碼。
* 執行鉤子需要以可執行shell腳本的格式編寫。
* 指令碼大小上限為96KB。
* 執行掛鉤設定和任何匹配標準用於確定哪些掛鉤適用於快照、備份或還原操作。



NOTE: 由於執行掛勾通常會減少或完全停用執行中應用程式的功能、因此您應該一律盡量縮短自訂執行掛勾執行所需的時間。如果您以相關的執行掛勾開始備份或快照作業、但隨後取消它、則如果備份或快照作業已經開始、仍允許掛勾執行。這表示備份後執行掛勾中使用的邏輯無法假設備份已完成。



== 執行攔截篩選器

當您新增或編輯應用程式的執行掛鉤時，您可以將篩選器新增至執行掛鉤，以管理掛鉤將符合的容器。篩選器對於在所有容器上使用相同容器映像的應用程式來說非常實用、但可能會將每個映像用於不同的用途（例如Elasticsearch）。篩選器可讓您建立執行攔截器在某些容器上執行的案例、但不一定所有容器都相同。如果您為單一執行掛勾建立多個篩選器、這些篩選器會與邏輯和運算子結合使用。每個執行掛機最多可有10個作用中篩選器。

您新增至執行掛勾的每個篩選器都會使用規則運算式來比對叢集中的容器。當掛機符合容器時、掛機會在該容器上執行其相關的指令碼。篩選器的規則運算式使用規則運算式2（RE2）語法、不支援建立篩選器、將容器從相符項目清單中排除。有關BlueXP backup and recovery支援的執行鉤子過濾器中的正規表示式的語法的信息，請參閱 https://github.com/google/re2/wiki/Syntax["規則運算式2（RE2）語法支援"^] 。


NOTE: 如果您將命名空間篩選器新增至執行掛勾、而執行還原或複製作業之後執行、且還原或複製來源與目的地位於不同的命名空間、則命名空間篩選器只會套用至目的地命名空間。



== 執行攔截範例

請造訪 https://github.com/NetApp/Verda["NetApp Verda GitHub專案"] 下載熱門應用程式（例如 Apache Cassandra 和 Elasticsearch ）的實際執行連結。您也可以查看範例、瞭解如何建構您自己的自訂執行掛勾。



== 建立執行鉤子模板

您可以建立自訂執行掛鉤模板，用於在應用程式上執行資料保護操作之前或之後執行操作。

.步驟
. 在BlueXP中，前往 *保護* > *備份和還原*。
. 選取 * 設定 * 索引標籤。
. 展開*執行鉤子模板*部分。
. 選擇*建立執行鉤子模板*。
. 輸入執行掛鉤的名稱。
. 選擇鉤子類型。例如，還原後鉤子將在還原作業完成後執行。
. 在「*腳本*」文字方塊中，輸入要作為執行鉤子範本的一部分執行的可執行 Shell 腳本。您也可以選擇「上傳腳本*」來上傳腳本檔案。
. 選擇* Create *（建立*）。
+
模板已建立並出現在*執行掛鉤模板*部分的模板清單中。


