---
sidebar: sidebar 
permalink: concept-clone-cloud-native-oracle-concepts.html 
keywords: cloud native, application data, clone, Cloud Manager, BlueXP, Oracle database, Oracle, clone limitations, clone methods, clone naming scheme, requirements, clone specification file 
summary: 在複製資料庫之前、請先瞭解複製概念。 
---
= 複製概念與需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用資料庫備份複製Oracle資料庫至來源資料庫主機或備用主機。您可以從主要儲存系統複製備份。

在複製資料庫之前、您應該先瞭解複製概念、並確保符合所有需求。



== 複製Oracle資料庫的需求

在複製Oracle資料庫之前、您應確保已完成先決條件。

* 您應該已經建立資料庫的備份。您應該已成功建立線上資料和記錄備份、以便成功完成複製作業。
* 在asm_diskstring參數中、如果您使用ASMfd、則應設定afd:*；如果您使用ASMLIB、則應設定ORCL:*。
* 如果要在備用主機上建立複本、備用主機應符合下列需求：
+
** 外掛程式應安裝在替代主機上。
** 如果您要複製位於iSCSI SAN儲存設備上的資料庫、複製主機應該能夠從儲存設備探索LUN。如果您要複製到備用主機、請確定儲存設備與備用主機之間已建立iSCSI工作階段。
** 如果來源資料庫是ASM資料庫：
+
*** ASM執行個體應在執行實體複本的主機上啟動並執行。
*** 如果您想要將複製資料庫的歸檔記錄檔放入專屬的ASM磁碟群組、則應在複製作業之前配置ASM磁碟群組。
*** 您可以設定資料磁碟群組的名稱、但請確保執行實體複本之主機上的任何其他ASM磁碟群組不會使用該名稱。
*** ASM磁碟群組上的資料檔案會配置為複製工作流程的一部分。








== 複製限制

* 不支援排程的複本（Clone生命週期管理）。
* 不支援複製複製的資料庫。
* 不支援複製位於Qtree上的資料庫。
* 不支援複製歸檔記錄備份。
* 不支援備份複製的資料庫。




== 複製方法

您可以使用基本方法或使用Clone規格檔案來建立實體複本。



=== 使用基本方法複製

您可以根據來源資料庫和所選備份、使用預設組態來建立複本。

* 資料庫參數、主資料庫和作業系統使用者預設為來源資料庫。
* 資料檔案路徑會根據所選的命名配置命名。
* 無法指定指令碼前、指令碼後及SQL陳述式。
* 恢復選項預設為*直到取消*、並使用與資料備份相關的記錄備份進行恢復




=== 使用規格檔案複製

您可以在複製規格檔案中定義組態、並使用該組態來複製資料庫。您可以下載規格檔案、根據需求加以修改、然後上傳檔案。 link:task-clone-cloud-native-oracle-data.html["深入瞭解"]。

規格檔中定義的不同參數、可修改如下：

|===
| 參數 | 說明 


 a| 
control_fils
 a| 
實體複本資料庫的控制檔位置。

控制檔數量將與來源資料庫相同。如果您要覆寫控制檔路徑、可以提供不同的控制檔路徑。檔案系統或ASM磁碟群組應存在於主機上。



 a| 
重作記錄
 a| 
重作記錄的位置、大小、重作群組數目。

複製資料庫至少需要兩個重作記錄群組。如果您想要置換重作記錄檔路徑、可以自訂不同於來源資料庫的重作記錄檔路徑。檔案系統或ASM磁碟群組應該存在於主機上。



 a| 
Oracle_version
 a| 
目標主機上的Oracle版本。



 a| 
Oracle_Home
 a| 
目標主機上的Oracle主目錄。



 a| 
啟用_archive記錄模式
 a| 
控制複製資料庫的歸檔記錄模式



 a| 
database_parameters
 a| 
複製資料庫的資料庫參數



 a| 
SQL_陳述 式
 a| 
複製後在資料庫上執行的SQL陳述式



 a| 
OS_USER_Detail
 a| 
目標實體複製資料庫上的Oracle OS使用者



 a| 
資料庫連接埠
 a| 
當主機上停用OS驗證時、用於與資料庫通訊的連接埠。



 a| 
ASM_port
 a| 
如果在create Clone輸入中提供認證、則用於與ASM資料庫通訊的連接埠。



 a| 
SKip_recovery
 a| 
不執行恢復作業。



 a| 
直到SCN
 a| 
恢復資料庫至指定的系統變更編號（SCN）。



 a| 
直到時間
 a| 
將資料庫恢復到指定的日期和時間。

接受的格式為_mm/dd/yyyy hh：mm:ss_。



 a| 
直到取消
 a| 
掛載與選定要複製的資料備份相關的記錄備份來恢復。

複製的資料庫會恢復到遺失或毀損的記錄檔為止。



 a| 
log_paths
 a| 
用於還原複製資料庫的其他歸檔記錄路徑位置。



 a| 
來源位置
 a| 
磁碟群組或掛載點在來源資料庫主機上的位置。



 a| 
Clone位置
 a| 
磁碟群組或掛載點的位置、需要在對應來源位置的目標主機上建立。



 a| 
位置類型
 a| 
可以是ASM_diskgroup或mountpoint。

這些值會在下載檔案時自動填入。您不應該編輯此參數。



 a| 
指令碼前
 a| 
建立複本之前、在目標主機上執行的指令碼。



 a| 
POST指令碼
 a| 
建立複本後、在目標主機上執行的指令碼。



 a| 
路徑
 a| 
Clone主機上指令碼的絕對路徑。

您應該將指令碼儲存在/var/opt/snapcenter/spl/scripts或此路徑內的任何資料夾中。



 a| 
逾時
 a| 
為目標主機上執行的指令碼指定的逾時時間。



 a| 
引數
 a| 
為指令碼指定的引數。

|===


== 複製命名配置

Clone命名配置定義了掛載點的位置、以及複製資料庫磁碟群組的名稱。您可以選擇*完全相同*或*自動產生*。



=== 相同的命名配置

如果您將複製命名配置選取為*完全相同*、則複製資料庫的掛載點位置和磁碟群組名稱將與來源資料庫相同。

例如、如果來源資料庫的掛載點是_/NetApp_sourcedb/data_1、+Data1_DG_、則對於複製的資料庫、掛載點在SAN上的NFS和ASM都維持不變。

* 控制檔和重作檔案的數量和路徑等組態將與來源相同。
+

NOTE: 如果重作記錄或控制檔路徑位於非資料磁碟區、則使用者應該已在目標主機上配置ASM磁碟群組或掛載點。

* Oracle OS使用者和Oracle版本將與來源資料庫相同。
* 複製儲存磁碟區名稱的格式如下：sourceVolNameSCs_Clone_CurrentTimeStampNumber。
+
例如、如果來源資料庫上的磁碟區名稱是_sourceVolName_、則複製的磁碟區名稱將是_sourceVolNameSC_Clone_1661420020304608825_。

+

NOTE: _CurrentTimerStampNumber_提供了磁碟區名稱的唯一性。





=== 自動產生的命名配置

如果您將複製配置選取為*自動產生*、則掛載點的位置和複製資料庫的磁碟群組名稱會附加一個字尾。*如果您選擇了基本的複製方法、則後置處理的是* Clone SID*。*如果您已選取規格檔案方法、則後置字元將是下載複製規格檔案時所指定的*後置字元*。

例如、如果來源資料庫的掛載點是_/NetApp_sourcedb/data_1_、而* Clone SID*或* Suffix*是_HR_、則複製資料庫的掛載點將是_/NetApp_sourcedb/data_1_HR_。

* 控制檔和重作記錄檔的數量與來源相同。
* 所有的重作記錄檔和控制檔都會位於其中一個複製的資料掛載點或資料ASM磁碟群組。
* 複製儲存磁碟區名稱的格式如下：sourceVolNameSCs_Clone_CurrentTimeStampNumber。
+
例如、如果來源資料庫上的磁碟區名稱是_sourceVolName_、則複製的磁碟區名稱將是_sourceVolNameSC_Clone_1661420020304608825_。

+

NOTE: _CurrentTimerStampNumber_提供了磁碟區名稱的唯一性。

* NAS掛載點的格式為_SourceNASMountPoint_suffix。
* ASM磁碟群組的格式為_SourceDiscket_suffix。
+

NOTE: 如果複製磁碟群組中的字元數大於25、則會有_SC_HashCode_suffix。





== 資料庫參數

無論複製命名方案為何、下列資料庫參數的值都會與來源資料庫相同。

* log_archive格式
* 稽核追蹤
* 程序
* ga_gregate目標
* rem遠 端登入密碼檔案
* undo_tablesp空間
* open_cursors
* SGa_target
* DB_block_size


下列資料庫參數的值將會以複製的SID為基礎、附加後置字元。

* 稽核檔案目的地=｛sourcedatabase_parametervalue｝後置
* log_archive目的地1 =｛sourcedatabase_oRAcLEHOME}_suffix




== 支援的預先定義環境變數、適用於特定實體複本的pretced和postscript

當您在複製資料庫時執行預先記錄和PostScript時、可以使用支援的預先定義環境變數。

* sc_ORIGIN_SID指定來源資料庫的SID。此參數將會填入應用程式磁碟區。範例：NFS32
* sc_ORIGIN_host指定來源主機的名稱。此參數將會填入應用程式磁碟區。範例：asmrac1.gdl.englab.netapp.com
* sc_oracle_home_home指定目標資料庫的Oracle主目錄路徑。範例：/ora01/app/oracle/product/18.1.0/db_1
* sc_backup_name指定備份的名稱。此參數將會填入應用程式磁碟區。範例：
+
** 如果資料庫未以ARCHIVELOG模式執行：data@rg2_scspr2417819002_07-20-2021_12.16.48.9267_0| LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
** 如果資料庫以ARCHIVELOG模式執行：data@rg2_scspr2417819002_07-2021_12.16.48.9267_0|log@rg2_scspr2417819002_07-2021_12.16.48.9267_1、Rg2_sc2417819002_07-48.922_18.267-20267-12.267-20267-202_sc267-12.267-20267-20267-202_18.267-12.267-202_sc267-202_sc267-12.267-12.267-202_sc267-202_sc267-202_sc267-


* sc_ORIGIN_OS_user-指定來源資料庫的作業系統擁有者。範例：Oracle
* sc_ORIGIN_OS_group指定來源資料庫的作業系統群組。範例：oinstall
* sc_target：sid"指定複製資料庫的SID。對於pdb複製工作流程、此參數的值將不會預先定義。此參數將會填入應用程式磁碟區。範例：clonedb
* sc_target主機指定要複製資料庫的主機名稱。此參數將會填入應用程式磁碟區。範例：asmrac1.gdl.englab.netapp.com
* sc_target作業系統使用者指定複製資料庫的作業系統擁有者。對於pdb複製工作流程、此參數的值將不會預先定義。範例：Oracle
* sc_target作業系統群組會指定複製資料庫的作業系統群組。對於pdb複製工作流程、此參數的值將不會預先定義。範例：oinstall
* sc_target資料庫連接埠指定複製資料庫的資料庫連接埠。對於pdb複製工作流程、此參數的值將不會預先定義。範例：1521




=== 支援的分隔符號

* @用於分隔資料與其資料庫名稱、並將值與其金鑰區隔。範例：data@rg2_scspr2417819002_07-20-2021_12.16.48.9267_0| LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
* |用於分隔SC_backup_name參數兩個不同實體之間的資料。範例：DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 0| LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
* 用於分隔同一機碼的變數集。範例：data@rg2_scspr2417819002_07-2021_12.16.48.9267_0| log@rg2_scspr2417819002_07-2021_12.16.48.9267_1、rg2_scspr2417819002_07-21 - 2021_12.16.48.9267_1_48.922_19002_20267-20267-20267-20267-202_18.202_18.202_18.202_12.267-2022_18.202_18.202_18.202_18.202_24

