---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp BlueXP backup and recovery保護您的 VMware 工作負載。 
---
= 在BlueXP backup and recovery概述中保護虛擬機器工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用BlueXP backup and recovery保護您的虛擬機器工作負載。 BlueXPBlueXP backup and recovery為虛擬機器、資料儲存區和 VMDK 提供快速、節省空間、崩潰一致性和虛擬機器一致性的備份和還原作業。

您可以將資料存放區備份至 Amazon Web Services S3 、 Microsoft Azure Blob 、 Google Cloud Platform 和 StorageGRID 、並將虛擬機器還原至內部部署的 SnapCenter Plug-in for VMware vSphere 主機。

[]
====
*注意* 若要切換到BlueXP backup and recovery工作負載，請參閱link:br-start-switch-ui.html["切換到不同的BlueXP backup and recovery工作負載"] 。

====
有關保護虛擬機器工作負載的說明，請參閱以下主題：

* link:prev-vmware-policy-create.html["為 VMware 工作負載建立策略"]
* link:prev-vmware-backup-aws.html["將 VMware 資料儲存備份到 Amazon Web Services"]
* link:prev-vmware-backup-azure.html["將 VMware 資料儲存體備份到 Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["將 VMware 資料儲存區備份到 Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["將 VMware 資料儲存備份到StorageGRID"]
* link:prev-vmware-restore.html["復原 VMware 工作負載"]
* link:prev-vmware-manage.html["管理 VMware 工作負載的保護"]

