---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp BlueXP backup and recovery保護您的 VMware 工作負載。 
---
= SnapCenter Plug-in for VMware vSphere以用於BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該在 BlueXP 備份和復原中註冊適用於 VMware vSphere 主機的 SnapCenter 插件，以便顯示資料儲存區和虛擬機器。只有具有管理存取權的使用者才能登錄 VMware vSphere 主機的 SnapCenter 外掛程式。

[]
====
*注意* 若要切換到BlueXP backup and recovery工作負載，請參閱link:br-start-switch-ui.html["切換到不同的BlueXP backup and recovery工作負載"] 。

====
.步驟
. 在BlueXP UI 中，選擇 *保護* > *備份和還原* > *虛擬機器*。
. 從「*設定*」下拉式選單中，選擇「SnapCenter Plug-in for VMware vSphere*」。
. 選擇「SnapCenter Plug-in for VMware vSphere」*。
. 請指定下列詳細資料：
+
.. 在 SnapCenter Plug-in for VMware vSphere 欄位中、指定 SnapCenter Plug-in for VMware vSphere 主機的 FQDN 或 IP 位址。
.. 在連接埠欄位中、指定 SnapCenter Plug-in for VMware vSphere 主機執行的連接埠編號。
+
您應確保在內部部署的 SnapCenter Plug-in for VMware vSphere 主機（在預設 8144 連接埠上執行）和 BlueXP Connector 執行個體（可在任何雲端供應商（ Amazon Web Services 、 Microsoft Azure 、 Google Cloud Platform ）或內部部署中執行）之間、能夠進行通訊。

.. 在使用者名稱和密碼欄位中、指定具有管理員角色的 vCenter 使用者認證。


. 選擇*註冊*。


*完成後*

選擇「*備份與復原*」>「*虛擬機器*」以查看使用已註冊的SnapCenter Plug-in for VMware vSphere保護的所有資料儲存區和虛擬機器。
