---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: 雲端供應商
    default: 所有雲端供應商
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP 備份與還原文件
    url: "/index.html"
  - title: 版本資訊
    url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 瞭解 BlueXP 備份與還原
      url: "/concept-backup-to-cloud.html"
    - title: 設定授權
      url: "/task-licensing-cloud-backup.html"
  - title: 監控資料保護
    entries:
    - title: 報告資料保護涵蓋範圍
      url: "/task-report-inventory.html"
    - title: 監控備份與還原工作的狀態
      url: "/task-monitor-backup-jobs.html"
  - title: 備份及還原ONTAP 資料
    entries:
    - title: 保護您的 ONTAP Volume 資料
      url: "/concept-ontap-backup-to-cloud.html"
    - title: 規劃您的保護旅程
      url: "/concept-protection-journey.html"
    - title: 備份Cloud Volumes ONTAP 到Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: 備份Cloud Volumes ONTAP 到Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: 備份Cloud Volumes ONTAP 到Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: 將內部部署ONTAP 的不支援資料備份至Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: 將內部部署ONTAP 的資料備份到Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: 將內部部署ONTAP 的不全資料備份到Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: 將內部部署ONTAP 的內部部署資料備份至StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: 管理ONTAP 還原備份
      url: "/task-manage-backups-ontap.html"
    - title: 從ONTAP 還原備份還原
      url: "/task-restore-backups-ontap.html"
    - title: 管理叢集層級的物件備份設定
      url: "/task-manage-backup-settings-ontap.html"
  - title: 備份及還原內部部署應用程式資料
    entries:
    - title: 保護內部部署的應用程式資料
      url: "/concept-protect-app-data-to-cloud.html"
    - title: 註冊SnapCenter 伺服器
      url: "/task-register-snapcenter-server.html"
    - title: 建立備份應用程式的原則
      url: "/task-create-policies-apps.html"
    - title: 將內部部署應用程式資料備份至Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: 將內部部署應用程式資料備份到Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: 將內部部署應用程式資料備份到Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: 將內部部署的應用程式資料備份StorageGRID 到不受資料保護的地方
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: 管理應用程式保護
      url: "/task-manage-app-backups.html"
    - title: 還原內部部署應用程式資料
      entries:
      - title: 還原Oracle資料庫
        url: "/task-restore-oracle-data.html"
      - title: 還原SQL Server資料庫
        url: "/task-restore-sql-data.html"
      - title: 還原 SAP HANA 資料庫
        url: "/task-restore-hana-backup.html"
  - title: 備份及還原雲端原生應用程式資料
    entries:
    - title: 保護您的雲端原生應用程式資料
      url: "/concept-protect-cloud-app-data-to-cloud.html"
    - title: 備份雲端原生 Oracle 資料庫
      entries:
      - title: 快速入門
        url: "/task-quick-start-oracle.html"
      - title: 設定FSX ONTAP 以供使用
        url: "/reference-configure-fsx-for-ontap.html"
      - title: 設定Cloud Volumes ONTAP 功能
        url: "/reference-configure-cloud-volumes-ontap.html"
      - title: 設定Azure NetApp Files 功能
        flavor: azure
        url: "/reference-configure-azure-netapp-files.html"
      - title: 安裝適用於 Oracle 的 SnapCenter 外掛程式、並新增資料庫主機
        url: "/task-add-host-discover-oracle-databases.html"
      - title: 備份Oracle資料庫
        url: "/task-backup-cloud-native-oracle-data.html"
    - title: 備份雲端原生 SAP HANA 資料庫
      entries:
      - title: 快速入門
        flavor: azure
        url: "/task-quick-start-hana.html"
      - title: 設定Azure NetApp Files 功能
        flavor: azure
        url: "/reference-configure-azure-netapp-files.html"
      - title: 安裝 SnapCenter Plug-in for SAP HANA 並新增資料庫主機
        flavor: azure
        url: "/task-deploy-snapcenter-plugin-for-sap-hana.html"
      - title: 備份SAP HANA資料庫
        flavor: azure
        url: "/task-backup-cloud-native-sap-hana-data.html"
    - title: 還原雲端原生 Oracle 資料庫
      entries:
      - title: 還原至原始位置
        url: "/task-restore-cloud-native-oracle-data-to-original-location.html"
      - title: 還原至替代位置
        url: "/task-restore-cloud-native-oracle-data-to-alternate-location.html"
    - title: 還原雲端原生 SAP HANA 資料庫
      flavor: azure
      url: "/task-restore-cloud-native-sap-hana-data.html"
    - title: 重新整理 SAP HANA 目標系統
      flavor: azure
      url: "/task-refresh-sap-hana-target-system.html"
    - title: 複製雲端原生 Oracle 資料庫
      entries:
      - title: 複製概念與需求
        url: "/concept-clone-cloud-native-oracle-concepts.html"
      - title: 複製雲端原生 Oracle 資料庫
        url: "/task-clone-cloud-native-oracle-data.html"
    - title: 管理雲端原生應用程式資料的保護
      url: "/task-manage-cloud-native-app-data.html"
  - title: 備份及還原虛擬機器資料
    entries:
    - title: 保護您的虛擬機器資料
      url: "/concept-protect-vm-data.html"
    - title: 註冊 VMware vSphere 主機的 SnapCenter 外掛程式
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: 建立備份資料存放區的原則
      url: "/task-create-policies-vms.html"
    - title: 將資料存放區備份至Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: 將資料存放區備份至Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: 將資料存放區備份到Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: 將資料存放區備份StorageGRID 至
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 管理資料存放區和虛擬機器資料的保護
      url: "/task-manage-vm-data-in-cloud.html"
    - title: 還原虛擬機器資料
      url: "/task-restore-vm-data.html"
  - title: 備份及還原Kubernetes資料
    entries:
    - title: 保護您的Kubernetes資料
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: 備份至 Amazon S3
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: 備份至Azure Blob
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: 備份至Google Cloud
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: 管理Kubernetes備份
      url: "/task-manage-backups-kubernetes.html"
    - title: 從Kubernetes備份還原
      url: "/task-restore-backups-kubernetes.html"
  - title: 使用REST API進行自動化
    url: "/api-backup-restore.html"
  - title: 參考資料
    entries:
    - title: 備份原則設定
      url: "/concept-cloud-backup-policies.html"
    - title: 支援的AWS歸檔儲存層
      url: "/reference-aws-backup-tiers.html"
    - title: 支援的Azure歸檔存取層
      url: "/reference-azure-backup-tiers.html"
    - title: 支援的Google歸檔儲存層
      url: "/reference-google-backup-tiers.html"
    - title: 在Azure中設定多帳戶存取的備份
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: 在黑暗的站台中還原 BlueXP 備份與還原資料庫
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: 重新啟動 BlueXP 備份與還原
      url: "/reference-restart-backup.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/task-support-registration.html"
    - title: 取得協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 瞭解 BlueXP 備份與還原
      url: concept-backup-to-cloud.html
    - title: 新增功能
      url: whats-new.html
    - title: 設定授權
      url: task-licensing-cloud-backup.html
    - title: 監控備份與還原工作的狀態
      url: task-monitor-backup-jobs.html
    - title: 建立資料保護涵蓋範圍的報告
      url: task-report-inventory.html
  - title: 將ONTAP 資料還原至雲端
    links:
    - title: 支援Amazon S3 Cloud Volumes ONTAP
      url: task-backup-to-s3.html
      flavor: aws
    - title: 適用於Azure Blob Cloud Volumes ONTAP
      url: task-backup-to-azure.html
      flavor: azure
    - title: 從NetApp移轉至Google Cloud Cloud Volumes ONTAP
      url: task-backup-to-gcp.html
      flavor: gcp
    - title: 內部部署ONTAP 的不支援Amazon S3
      url: task-backup-onprem-to-aws.html
      flavor: aws
    - title: 內部部署ONTAP 的不只是Azure Blob
      url: task-backup-onprem-to-azure.html
      flavor: azure
    - title: 內部部署ONTAP 的不只是Google Cloud
      url: task-backup-onprem-to-gcp.html
      flavor: gcp
    - title: 內部部署ONTAP 的功能從功能到StorageGRID 功能
      url: task-backup-onprem-private-cloud.html
  - title: 管理ONTAP 還原備份檔案
    links:
    - title: 在其他磁碟區上啟用磁碟區備份
      url: task-manage-backups-ontap.html#activate-backup-on-additional-volumes-in-a-working-environment
    - title: 編輯現有的雲端備份原則
      url: task-manage-backups-ontap.html#edit-an-existing-backup-to-cloud-policy
    - title: 新增備份至雲端原則
      url: task-manage-backups-ontap.html#add-a-new-backup-to-cloud-policy
    - title: 變更指派給現有磁碟區的原則
      url: task-manage-backups-ontap.html#change-the-backup-settings-assigned-to-existing-volumes
    - title: 建立手動Volume備份
      url: task-manage-backups-ontap.html#create-a-manual-volume-backup-at-any-time
    - title: 檢視每個磁碟區的備份清單
      url: task-manage-backups-ontap.html#view-the-list-of-backups-for-each-volume
    - title: 管理複寫關係
      url: task-manage-backups-ontap.html#manage-the-replication-relationship-with-the-source-volume
    - title: 刪除備份
      url: task-manage-backups-ontap.html#delete-backups
  - title: 將應用程式資料備份到雲端
    links:
    - title: 將內部部署應用程式資料備份至Amazon Web Services
      flavor: aws
      url: task-backup-app-data-to-aws.html
    - title: 將內部部署應用程式資料備份到Microsoft Azure
      flavor: azure
      url: task-backup-app-data-to-azure.html
    - title: 將內部部署應用程式資料備份到Google Cloud
      flavor: gcp
      url: task-backup-app-data-to-gcp.html
    - title: 將內部部署的應用程式資料備份StorageGRID 到不受資料保護的地方
      url: task-backup-app-data-to-storagegrid.html
    - title: 備份雲端原生 Oracle 資料庫
      url: task-backup-cloud-native-oracle-data.html
    - title: 備份雲端原生 SAP HANA 資料庫
      flavor: azure
      url: task-backup-cloud-native-sap-hana-data.html
  - title: 將資料存放區備份到雲端
    links:
    - title: 將資料存放區備份至Amazon Web Services
      flavor: aws
      url: task-backup-vm-data-to-aws.html
    - title: 將資料存放區備份至Microsoft Azure
      flavor: azure
      url: task-backup-vm-data-to-azure.html
    - title: 將資料存放區備份到Google Cloud Platform
      flavor: gcp
      url: task-backup-vm-data-to-gcp.html
    - title: 將資料存放區備份StorageGRID 至
      url: task-backup-vm-data-to-storagegrid.html
  - title: 從雲端還原資料
    links:
    - title: 還原 ONTAP Volume 資料
      url: task-restore-backups-ontap.html
    - title: 還原內部部署的 Oracle 應用程式資料
      url: task-restore-oracle-data.html
    - title: 還原內部部署的 SQL Server 應用程式資料
      url: task-restore-sql-data.html
    - title: 還原雲端原生 Oracle 應用程式資料
      url: task-restore-cloud-native-oracle-data.html
    - title: 還原雲端原生 SAP HANA 應用程式資料
      flavor: azure
      url: task-restore-cloud-native-sap-hana-data.html
    - title: 還原虛擬機器資料
      url: task-restore-vm-data.html
    - title: 還原 Kubernetes Volume 資料
      url: task-restore-backups-kubernetes.html
  - title: 將Kubernetes資料備份到雲端
    links:
    - title: Kubernetes叢集至Amazon S3
      url: task-backup-kubernetes-to-s3.html
      flavor: aws
    - title: Kubernetes叢集至Azure Blob
      url: task-backup-kubernetes-to-azure.html
      flavor: azure
    - title: Kubernetes叢集至Google Cloud
      url: task-backup-kubernetes-to-gcp.html
      flavor: gcp
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
    - title: BlueXP 備份與還原部落格
      url: https://bluexp.netapp.com/blog/topic/cloud-backup
    - title: BlueXP 備份與還原使用案例
      url: https://bluexp.netapp.com/cloud-backup
    - title: BlueXP 網路研討會
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: 所有BlueXP文件
