---
settings:
  name: Cloud Backup
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: 雲端供應商
    default: 所有雲端供應商
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 雲端備份文件
    url: "/index.html"
  - title: 版本資訊
    url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 深入瞭解Cloud Backup
      url: "/concept-backup-to-cloud.html"
    - title: 設定授權
      url: "/task-licensing-cloud-backup.html"
    - title: 監控備份與還原工作的狀態
      url: "/task-monitor-backup-jobs.html"
  - title: 備份及還原ONTAP 資料
    entries:
    - title: 保護您的 ONTAP Volume 資料
      url: "/concept-ontap-backup-to-cloud.html"
    - title: 備份Cloud Volumes ONTAP 到Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: 備份Cloud Volumes ONTAP 到Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: 備份Cloud Volumes ONTAP 到Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: 將內部部署ONTAP 的不支援資料備份至Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: 將內部部署ONTAP 的資料備份到Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: 將內部部署ONTAP 的不全資料備份到Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: 將內部部署ONTAP 的內部部署資料備份至StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: 管理ONTAP 還原備份
      url: "/task-manage-backups-ontap.html"
    - title: 管理叢集層級的備份設定
      url: "/task-manage-backup-settings-ontap.html"
    - title: 從ONTAP 還原備份還原
      url: "/task-restore-backups-ontap.html"
  - title: 備份及還原Kubernetes資料
    entries:
    - title: 保護您的Kubernetes資料
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: 備份至 Amazon S3
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: 備份至Azure Blob
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: 備份至Google Cloud
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: 管理Kubernetes備份
      url: "/task-manage-backups-kubernetes.html"
    - title: 從Kubernetes備份還原
      url: "/task-restore-backups-kubernetes.html"
  - title: 保護應用程式資料
    entries:
    - title: 保護內部部署應用程式資料
      entries:
      - title: 保護內部部署的應用程式資料
        url: "/concept-protect-app-data-to-cloud.html"
      - title: 註冊SnapCenter 伺服器
        url: "/task-register-snapcenter-server.html"
      - title: 建立備份應用程式的原則
        url: "/task-create-policies-apps.html"
      - title: 將內部部署應用程式資料備份至Amazon Web Services
        flavor: aws
        url: "/task-backup-app-data-to-aws.html"
      - title: 將內部部署應用程式資料備份到Microsoft Azure
        flavor: azure
        url: "/task-backup-app-data-to-azure.html"
      - title: 將內部部署應用程式資料備份到Google Cloud
        flavor: gcp
        url: "/task-backup-app-data-to-gcp.html"
      - title: 將內部部署的應用程式資料備份StorageGRID 到不受資料保護的地方
        url: "/task-backup-app-data-to-storagegrid.html"
      - title: 管理應用程式保護
        url: "/task-manage-app-backups.html"
      - title: 還原內部部署應用程式資料
        entries:
        - title: 還原Oracle資料庫
          url: "/task-restore-oracle-data.html"
        - title: 還原SQL Server資料庫
          url: "/task-restore-sql-data.html"
      - title: 掛載應用程式備份
        url: "/task-mount-app-backup.html"
    - title: 保護雲端原生應用程式資料
      entries:
      - title: 保護雲端原生應用程式資料
        url: "/concept-protect-cloud-app-data-to-cloud.html"
      - title: 備份雲端原生應用程式資料
        entries:
        - title: 備份雲端原生Oracle資料庫
          entries:
          - title: 存取BlueXP
            url: "/reference-access-bluexp.html"
          - title: 設定FSX ONTAP 以供使用
            url: "/reference-configure-fsx-for-ontap.html"
          - title: 設定Cloud Volumes ONTAP 功能
            url: "/reference-configure-cloud-volumes-ontap.html"
          - title: 部署SnapCenter 適用於Oracle的支援功能外掛程式、並新增資料庫主機
            url: "/task-add-host-discover-oracle-databases.html"
          - title: 備份Oracle資料庫
            url: "/task-backup-cloud-native-oracle-data.html"
        - title: 備份雲端原生SAP HANA資料庫
          entries:
          - title: 存取BlueXP
            flavor: azure
            url: "/reference-access-bluexp.html"
          - title: 設定Azure NetApp Files 功能
            flavor: azure
            url: "/reference-configure-azure-netapp-files.html"
          - title: 部署SnapCenter 適用於SAP HANA的支援功能外掛程式、並新增資料庫主機
            flavor: azure
            url: "/task-deploy-snapcenter-plugin-for-sap-hana.html"
          - title: 備份SAP HANA資料庫
            flavor: azure
            url: "/task-backup-cloud-native-sap-hana-data.html"
      - title: 還原雲端原生應用程式資料
        entries:
        - title: 還原雲端原生Oracle資料庫
          url: "/task-restore-cloud-native-oracle-data.html"
        - title: 還原雲端原生SAP HANA資料庫
          flavor: azure
          url: "/task-restore-cloud-native-sap-hana-data.html"
      - title: 複製雲端原生應用程式資料
        entries:
        - title: 複製雲端原生Oracle資料庫
          entries:
          - title: 複製概念與需求
            url: "/concept-clone-cloud-native-oracle-concepts.html"
          - title: 複製雲端原生Oracle資料庫
            url: "/task-clone-cloud-native-oracle-data.html"
      - title: 管理雲端原生應用程式資料的保護
        url: "/task-manage-cloud-native-app-data.html"
  - title: 備份及還原虛擬機器資料
    entries:
    - title: 保護您的虛擬機器資料
      url: "/concept-protect-vm-data.html"
    - title: 註冊SnapCenter VMware vSphere的VMware外掛程式
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: 建立備份虛擬機器的原則
      url: "/task-create-policies-vms.html"
    - title: 將資料存放區備份至Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: 將資料存放區備份至Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: 將資料存放區備份到Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: 將資料存放區備份StorageGRID 至
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 管理虛擬機器的保護
      url: "/task-manage-vm-data-in-cloud.html"
    - title: 還原虛擬機器資料
      url: "/task-restore-vm-data.html"
  - title: 使用REST API進行自動化
    url: "/api-backup-restore.html"
  - title: 參考資料
    entries:
    - title: 雲端備份原則設定
      url: "/concept-cloud-backup-policies.html"
    - title: 支援的AWS歸檔儲存層
      flavor: aws
      url: "/reference-aws-backup-tiers.html"
    - title: 支援的Azure歸檔存取層
      flavor: azure
      url: "/reference-azure-backup-tiers.html"
    - title: 支援的Google歸檔儲存層
      flavor: gcp
      url: "/reference-google-backup-tiers.html"
    - title: 在黑暗的站台中備份Cloud Backup資料庫
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: 設定備份以在Azure中存取多個帳戶
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/task-support-registration.html"
    - title: 取得協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 深入瞭解Cloud Backup
      url: concept-backup-to-cloud.html
    - title: 新增功能
      url: whats-new.html
    - title: 設定授權
      url: task-licensing-cloud-backup.html
    - title: 監控備份與還原工作的狀態
      url: task-monitor-backup-jobs.html
  - title: 將ONTAP 資料還原至雲端
    links:
    - title: 支援Amazon S3 Cloud Volumes ONTAP
      url: task-backup-to-s3.html
      flavor: aws
    - title: 適用於Azure Blob Cloud Volumes ONTAP
      url: task-backup-to-azure.html
      flavor: azure
    - title: 從NetApp移轉至Google Cloud Cloud Volumes ONTAP
      url: task-backup-to-gcp.html
      flavor: gcp
    - title: 內部部署ONTAP 的不支援Amazon S3
      url: task-backup-onprem-to-aws.html
      flavor: aws
    - title: 內部部署ONTAP 的不只是Azure Blob
      url: task-backup-onprem-to-azure.html
      flavor: azure
    - title: 內部部署ONTAP 的不只是Google Cloud
      url: task-backup-onprem-to-gcp.html
      flavor: gcp
    - title: 內部部署ONTAP 的功能從功能到StorageGRID 功能
      url: task-backup-onprem-private-cloud.html
  - title: 將Kubernetes資料備份到雲端
    links:
    - title: Kubernetes叢集至Amazon S3
      url: task-backup-kubernetes-to-s3.html
      flavor: aws
    - title: Kubernetes叢集至Azure Blob
      url: task-backup-kubernetes-to-azure.html
      flavor: azure
    - title: Kubernetes叢集至Google Cloud
      url: task-backup-kubernetes-to-gcp.html
      flavor: gcp
  - title: 保護應用程式資料
    links:
    - title: 將內部部署應用程式資料備份至Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: 將內部部署應用程式資料備份到Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: 將內部部署應用程式資料備份到Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: 將內部部署的應用程式資料備份StorageGRID 到不受資料保護的地方
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: 備份雲端原生Oracle資料庫
      url: task-backup-cloud-native-oracle-data.html
    - title: 備份雲端原生SAP HANA資料庫
      url: task-backup-cloud-native-sap-hana-data.html
  - title: 備份及還原虛擬機器資料
    links:
    - title: 將資料存放區備份至Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: 將資料存放區備份至Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: 將資料存放區備份到Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: 將資料存放區備份StorageGRID 至
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 從雲端還原虛擬機器
      url: task-restore-vm-data.html
  - title: 還原ONTAP 來自還原備份檔案的資料
    links:
    - title: 還原ONTAP 功能
      url: task-restore-backups-ontap.html
    - title: 從ONTAP 還原磁碟區還原檔案和資料夾
      url: task-restore-backups-ontap.html
    - title: 還原Kubernetes磁碟區
      url: task-restore-backups-kubernetes.html
  - title: 管理ONTAP 還原備份檔案
    links:
    - title: 啟用和停用Volume備份
      url: task-manage-backups-ontap.html#enabling-and-disabling-backups-of-volumes
    - title: 編輯現有的備份原則
      url: task-manage-backups-ontap.html#editing-an-existing-backup-policy
    - title: 新增備份原則
      url: task-manage-backups-ontap.html#adding-a-new-backup-policy
    - title: 變更指派給現有磁碟區的原則
      url: task-manage-backups-ontap.html#changing-the-policy-assigned-to-existing-volumes
    - title: 建立手動Volume備份
      url: task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time
    - title: 檢視每個磁碟區的備份清單
      url: task-manage-backups-ontap.html#viewing-the-list-of-backups-for-each-volume
    - title: 刪除備份
      url: task-manage-backups-ontap.html#deleting-backups
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
    - title: Cloud Backup 部落格
      url: https://bluexp.netapp.com/blog/topic/cloud-backup
    - title: 雲端備份使用案例
      url: https://bluexp.netapp.com/cloud-backup
    - title: 雲端網路研討會
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有BlueXP文件
