---
sidebar: sidebar 
permalink: reference-google-backup-tiers.html 
keywords: google, storage classes, archive 
summary: BlueXP 備份與還原支援單一 Google 歸檔儲存類別和大多數地區。 
---
= Google歸檔儲存類別並還原擷取時間
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 備份與還原支援單一 Google 歸檔儲存類別和大多數地區。



== 支援用於 BlueXP 備份與還原的 Google 歸檔儲存類別

一開始建立備份檔案時、檔案會儲存在_Standard_儲存設備中。此階層已最佳化、可儲存不常存取的資料、但也可讓您立即存取。

如果您的內部叢集使用 ONTAP 9.12.1 或更新版本、您可以選擇在特定天數（通常超過 30 天）之後、將舊備份分層儲存至 BlueXP 備份和恢復 UI 中的 _Archive_ 儲存設備、以進一步最佳化成本。此層級中的資料需要較高的擷取成本、因此您需要考量從這些歸檔備份檔案還原資料的頻率。請參閱相關章節 <<restore data from archival storage,從歸檔儲存設備還原資料>>。

請注意、當您使用此類型的生命週期規則來設定 BlueXP 備份與還原時、在 Google 帳戶中設定儲存庫時、不得設定任何生命週期規則。

https://cloud.google.com/storage/docs/storage-classes["深入瞭解Google儲存課程"^]。



== 從歸檔儲存設備還原資料

雖然在歸檔儲存設備中儲存較舊的備份檔案比標準儲存設備便宜得多、但從歸檔儲存設備中的備份檔案存取資料以進行還原作業需要較長的時間、而且成本較高。

從Google歸檔還原資料需要多少成本？:: 如需各地區的詳細Google Cloud Storage定價資訊、請參閱 https://cloud.google.com/storage/pricing["Google Cloud Storage定價頁面"^]。
還原在Google歸檔中歸檔的物件需要多久時間？:: 共有2個部分可構成總還原時間：
+
--
* *擷取時間*：從歸檔中擷取備份檔案並將其置於標準儲存設備的時間。這有時稱為「補水」時間。與其他雲端供應商提供的「最冷」儲存解決方案不同、您的資料可在幾毫秒內存取。
* *還原時間*：從標準儲存設備中的備份檔案還原資料的時間。這一次與一般直接從標準儲存設備進行還原作業（不使用歸檔層時）並無不同。


--

