---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: 打造Azure NetApp Files 可運作的環境和Connector 
---
= 設定Azure NetApp Files 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 BlueXP 、您應該建立 Azure NetApp Files 工作環境來新增和管理磁碟區和其他資料服務。您也應該在 Azure 中建立 Connector 、讓 BlueXP 能夠管理公有雲環境中的資源和程序。



== 打造Azure NetApp Files 可運作的環境

您應該在Azure NetApp Files 託管資料庫的環境中建立不必要的工作環境。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["深入瞭解 Azure NetApp Files"] 和 link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["打造 Azure NetApp Files 一個不一樣的工作環境"]。



== 建立連接器

BlueXP 帳戶管理員應在 Azure 中部署 Connector 、讓 BlueXP 能夠在您的公有雲環境中管理資源和程序。


NOTE: 您無法從UI更新新的連接器ID。

如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["從BlueXP在Azure中建立連接器"]。

* 您應該使用相同的連接器來管理 Azure NetApp Files 工作環境和資料庫。
* 如果您在同一個虛擬網路（ vnet ）中擁有 Azure NetApp Files 工作環境和資料庫、則可以在同一個 vnet 中部署連接器。
* 如果您的 Azure NetApp Files 工作環境和資料庫位於不同的 VNets 中、且在 Azure NetApp Files 上設定了 NAS （ NFS ）工作負載、則可以在任一 VNets 上建立連接器。


建立連接器後、請執行下列步驟：

* 按一下 * 儲存 * > * 畫布 * > * 我的工作環境 * > * 新增工作環境 * 來新增工作環境。
+
確保連接器與資料庫主機和 Azure NetApp Files 工作環境之間有連線。連接器應連接至 Azure NetApp Files 工作環境。

* 按一下 *Connector > Manage Connectors* 並選取 Connector 名稱、以複製 Connector ID 。

