---
sidebar: sidebar 
permalink: reference-configure-fsx-for-ontap.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, BlueXP 
summary: 建立FSX,以利ONTAP 執行不必要的工作環境和連接器 
---
= 設定FSX ONTAP 以供使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 BlueXP 、您應該建立適用於 ONTAP 工作環境的 FSX 、以新增及管理磁碟區和其他資料服務。您也應該在 AWS 中建立一個 Connector 、讓 BlueXP 能夠在您的公有雲環境中管理資源和程序。



== 建立FSX以利ONTAP 執行不工作環境

您應該為託管資料庫的 ONTAP 工作環境建立 FSX 。如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSX for ONTAP Sfor Sf.入門"] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["建立及管理Amazon FSX以利ONTAP 實現不工作環境"]。

您可以使用 BlueXP 或 AWS 為 ONTAP 工作環境建立 FSX 。如果您是使用AWS建立、那麼您應該在ONTAP BlueXP中探索FSXfor the Sfor the Sfor the System.



== 建立連接器

帳戶管理員需要在 AWS 中建立一個 Connector 、讓 BlueXP 能夠在您的公有雲環境中管理資源和程序。

如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-aws.html["從BlueXP在AWS中建立連接器"]。

* 您應該使用相同的連接器來管理 ONTAP 工作環境和資料庫的 FSX 。
* 如果您在同一個虛擬私有雲（ VPC ）中擁有適用於 ONTAP 的 FSX 工作環境和資料庫、則可以在同一個 VPC 中部署連接器。
* 如果您在不同的 VPC 中擁有適用於 ONTAP 工作環境和資料庫的 FSX ：
+
** 如果您在適用於 ONTAP 的 FSX 上設定 NAS （ NFS ）工作負載、則可以在任一部 VPC 上建立連接器。
** 如果您只設定 SAN 工作負載、而不打算使用任何 NAS （ NFS ）工作負載、則應在建立 ONTAP 系統的 FSX 的 VPC 中建立連接器。
+

NOTE: 若要使用 NAS （ NFS ）工作負載、您應該在資料庫 VPC 和 Amazon VPC 之間擁有傳輸閘道。NFS IP位址是浮動IP位址、只能透過傳輸閘道從其他VPC存取。我們無法透過對等處理VPC來存取浮動IP位址。





建立 Connector 之後、按一下 * 儲存 * > * 畫布 * > * 我的工作環境 * > * 新增工作環境 * 、然後依照提示新增工作環境。確保 Connector 與 Oracle 資料庫主機和 FSX 工作環境之間有連線。Connector 應該能夠連線至 FSX 工作環境的叢集管理 IP 位址。

* 按一下 * 儲存 * > * 畫布 * > * 我的工作環境 * > * 新增工作環境 * 來新增工作環境。
+
確保連接器與資料庫主機之間有連線、 ONTAP 工作環境則有 FSX 。此連接器應連接至適用於 ONTAP 工作環境的 FSX 的叢集管理 IP 位址。

* 按一下 *Connector > Manage Connectors* 並選取 Connector 名稱、以複製 Connector ID 。

