---
sidebar: sidebar 
permalink: reference-configure-fsx-for-ontap.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, BlueXP 
summary: 建立FSX,以利ONTAP 執行不必要的工作環境和連接器 
---
= 設定FSX ONTAP 以供使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該建立FSX,以利ONTAP 進行不工作的環境和連接器。



== 建立FSX以利ONTAP 執行不工作環境

您應該建立Amazon FSX、以利ONTAP 資料庫所在的不中斷作業環境。如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSX for ONTAP Sfor Sf.入門"] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["建立及管理Amazon FSX以利ONTAP 實現不工作環境"]。

您可以使用BlueXP或AWS來建立NetApp FSX。如果您是使用AWS建立、那麼您應該在ONTAP BlueXP中探索FSXfor the Sfor the Sfor the System.



== 建立連接器

客戶管理員需要在AWS中部署Connector、讓BlueXP能夠管理公有雲環境中的資源和程序。

如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["從BlueXP在AWS中建立連接器"]。

* 您應該使用相同的連接器來管理FSX工作環境和Oracle資料庫。
* 如果您在同一個VPC上有FSX工作環境和Oracle資料庫、您可以在同一個VPC上部署連接器。
* 如果您在不同的VPC上有FSX工作環境和Oracle資料庫：
+
** 如果您在FSX上設定NAS（NFS）工作負載、則可以在任一VPC上建立連接器。
** 如果您只設定SAN工作負載、而不打算使用任何NAS（NFS）工作負載、則應在建立FSX系統的VPC中建立連接器。
+

NOTE: 若要使用NAS（NFS）工作負載、您應該在Oracle資料庫VPC和FSXVPC之間擁有傳輸閘道。NFS IP位址是浮動IP位址、只能透過傳輸閘道從其他VPC存取。我們無法透過對等處理VPC來存取浮動IP位址。





建立連接器之後、按一下「*儲存設備*>* Canvas*>*我的工作環境*>*「新增工作環境*」、然後依照提示新增工作環境。確保連接器與Oracle資料庫主機和FSX工作環境之間有連線。連接器應能連線至FSX工作環境的叢集管理IP位址。


IMPORTANT: 建立連接器之後、按一下*連接器>管理連接器*；選取連接器名稱、然後複製連接器ID。
