---
sidebar: sidebar 
permalink: reference-prereq-protect-cloud-native-app-data.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, AWS, deploy Oracle plug-in 
summary: 在建立備份之前、請先完成先決條件。 
---
= 先決條件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該可以存取Cloud Manager、建立Cloud Manager帳戶、建立工作環境和Connector、並部署SnapCenter 適用於Oracle的「支援Oracle的支援程式」。



== 存取Cloud Manager

您應該 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-signing-up.html["註冊NetApp Cloud Central"]、 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["登入Cloud Manager"]，然後設定 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html["NetApp帳戶"]。



== 建立FSX以利ONTAP 執行不工作環境

您應該建立Amazon FSX、以利ONTAP 資料庫所在的不中斷作業環境。如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSX for ONTAP Sfor Sf.入門"] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["建立及管理Amazon FSX以利ONTAP 實現不工作環境"]。

您可以使用Cloud Manager或AWS來建立NetApp FSX。如果您是使用AWS建立、那麼您應該在ONTAP Cloud Manager中探索FSX for the Sfor the Sfor the System。



== 建立連接器

客戶管理員需要在AWS中部署Connector、讓Cloud Manager能夠管理公有雲環境中的資源和程序。

如需相關資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["從 Cloud Manager 在 AWS 中建立連接器"]。

* 您應該使用相同的連接器來管理FSX工作環境和Oracle資料庫。
* 如果您在同一個VPC上有FSX工作環境和Oracle資料庫、您可以在同一個VPC上部署連接器。
* 如果您在不同的VPC上有FSX工作環境和Oracle資料庫：
+
** 如果您在FSX上設定NAS（NFS）工作負載、則可以在任一VPC上建立連接器。
** 如果您只設定SAN工作負載、而不打算使用任何NAS（NFS）工作負載、則應在建立FSX系統的VPC中建立連接器。
+

NOTE: 若要使用NAS（NFS）工作負載、您應該在Oracle資料庫VPC和FSXVPC之間擁有傳輸閘道。NFS IP位址是浮動IP位址、只能透過傳輸閘道從其他VPC存取。我們無法透過對等處理VPC來存取浮動IP位址。





建立連接器之後、按一下* Canvas*>* Add Working Environment*、然後依照提示新增工作環境。確保連接器與Oracle資料庫主機和FSX工作環境之間有連線。連接器應能連線至FSX工作環境的叢集管理IP位址。


IMPORTANT: 建立連接器之後、按一下*連接器>管理連接器*；選取連接器名稱、然後複製連接器ID。



== 部署SnapCenter 適用於Oracle的支援功能外掛程式

您應該在SnapCenter 每個Oracle資料庫主機上部署適用於Oracle的支援功能。視Oracle主機是否啟用SSH金鑰型驗證而定、您可以遵循其中一種方法來部署外掛程式。


NOTE: 請確定每個Oracle資料庫主機上都安裝了Java 8、且已適當設定Java_Home變數。



=== 使用SSH金鑰型驗證的外掛程式部署

如果在Oracle主機上啟用SSH金鑰型驗證、您可以執行下列步驟來部署外掛程式。在執行這些步驟之前、請先確認已啟用連接器的SSH連線。

. 以非root使用者身分登入Connector VM。
. 取得基本掛載路徑。「Udo Docker Volume ls | Grep SCS_Cloud Volume | awk｛'print $2'｝| xargs Sudo Docker Volume Check | Grep mountpoint」
. 部署外掛程式。
+
「<base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name>--sshkey <ssh金鑰_key_file>--userName <user_name>--port <ssh連接埠>--pluginport <plugin_port>--installdir <install目錄>'

+
** host_name是Oracle主機的名稱、這是必要的參數。
** SSH_KEY_file是用於連接Oracle主機的SSH金鑰、這是必要的參數。
** 使用者名稱：在Oracle主機上具有SSH權限的使用者、此為選用參數。預設值為EC2使用者。
** SSH_port：Oracle主機上的SSH連接埠、此為選用參數。預設值為22
** plugin_port：外掛程式使用的連接埠、這是選用參數。預設值為8145
** 安裝目錄：要部署外掛程式的目錄、此為選用參數。預設值為/opt。




例如：「sUdo /var/lib/dred/voles/service-manager-2_cloudmanager_scs_cloud_volate_volue/_data/scripts/oracle_plugin_copy_and_install.sh - host xxx.xxx.xxx.-sshkey /keys/NetApp-ssh．pk」



=== 手動部署外掛程式

如果未在Oracle主機上啟用SSH金鑰型驗證、您應該執行下列手動步驟來部署外掛程式。

. 登入Connector VM。
. 下載SnapCenter 《支援Linux主機的二進位程式》。「Udo Docker執行- IT cloudmanager_SCs_cloul -X Get 'http://127.0.0.1/deploy/downloadLinuxPlugin'`[]
. 取得基本掛載路徑。「Udo Docker Volume ls | Grep SCS_Cloud Volume | awk｛'print $2'｝| xargs Sudo Docker Volume Check | Grep mountpoint」
. 取得下載外掛程式的二進位路徑。「Udo ls <base_mount_path>$(sudo dod泊 塢視窗ps | grep -po" cloudmanager_SCs_clou:.*？"| sed -e 's/*$/'| cut -F2 -d":")/sc-Linux主機外掛程式/snapcenter_Linux主機外掛程式_scsscs.bin"
. 使用scp或其他替代方法、將_snapcenter_Linux主機_plugin_scs.bin_複製到每個Oracle資料庫主機。
. 在Oracle資料庫主機上、執行下列命令以啟用二進位檔案的執行權限。"chmod+x snapcenter_Linux主機_plugin_SCs.bin"
. 以root使用者身分部署Oracle外掛程式。如欲瞭解更多資訊、請參閱：snapcenter_linux_host_plugin_scs.bin -I silent
. 從連接器VM的_<base_mount_path>/用戶端/憑證/_路徑、複製_imple.p12_到外掛主機的_/var/opt/snapcenter/spl/etc/_。
+
.. 瀏覽至_/var/opt/snapcenter/spl/etc/、然後執行keytoole命令以匯入憑證。「keytool-v -importkeystore -srckeystore CERT.p12 -srcstoretype pkcs12 -destkeystore keyKeystore .jks -deststoretype JKS -rcsstorepass SnapCenter sore-ascalias SnapCenter agentcert -noprompt」
.. 重新啟動SPL：「系統重新啟動spl」



