---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, backup, restore, backup and recovery 
summary: 已知限制指出本產品版本不支援的功能、或是無法與產品正確互通的功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的功能、或是無法與產品正確互通的功能。請仔細檢閱這些限制。



== ONTAP 磁碟區的備份與還原限制



=== 複寫限制

* 您一次只能選取一個 FlexGroup Volume 進行複寫。您需要為每個 FlexGroup 磁碟區分別啟動備份。
+
FlexVol Volume 沒有限制、您可以選取工作環境中的所有 FlexVol Volume 、並指派相同的備份原則。

* 中支援下列功能 https://docs.netapp.com/us-en/bluexp-replication/index.html["BlueXP 複寫服務"]，但在使用 BlueXP 備份和恢復的複製功能時不需要：
+
** 不支援串聯組態、從磁碟區 A 複寫到磁碟區 B 、從磁碟區 B 複寫到磁碟區 C支援包括從磁碟區 A 複寫到磁碟區 B
** 不支援在 ONTAP 系統的 FSX 之間複寫資料。
** 不支援建立磁碟區一次性複寫。


* 從內部部署 ONTAP 系統建立複製時、如果目標 Cloud Volumes ONTAP 系統上的 ONTAP 版本為 9.8 、 9.9 或 9.11 、則只允許鏡射資料保險箱原則。




=== 備份至物件限制

* 當您建立或編輯未指派磁碟區給原則的備份原則時、保留的備份數量最多可達 1018 個。將磁碟區指派給原則之後、您可以編輯原則、建立最多 4000 個備份。
* 備份資料保護（DP）磁碟區時：
+
** 與SnapMirror標籤「app_nistent」和「all_source_snapshot」的關係將不會備份到雲端。
** 如果您在SnapMirror目的地磁碟區上建立Snapshot的本機複本（無論使用的是SnapMirror標籤）、這些Snapshot將不會作為備份移至雲端。此時、您需要建立一個 Snapshot 原則、並將所需的標籤貼到來源 DP Volume 、以便 BlueXP 備份和還原進行備份。


* FlexGroup Volume 備份無法移至歸檔儲存設備。
* 如果叢集執行的是 ONTAP 9.13.1 或更新版本、 FlexGroup Volume 備份可以使用 DataLock 和勒索軟體保護。
* SVM-DR磁碟區備份受到下列限制的支援：
+
** 備份僅支援ONTAP 來自於不支援的支援。
** 套用至磁碟區的 Snapshot 原則必須是 BlueXP 備份與還原所認可的其中一項原則、包括每日、每週、每月等 無法辨識預設的「 sm_Created 」原則（用於 * 鏡射所有快照 * ）、而且 DP Volume 不會顯示在可備份的磁碟區清單中。




* 支援MetroCluster ：
+
** 當您使用 ONTAP 9.12.1 GA 或更新版本時、連接至主要系統時支援備份。整個備份組態會傳輸到次要系統、以便在切換後自動繼續備份到雲端。您不需要在次要系統上設定備份（事實上、您受到限制、無法這麼做）。
** 當您使用 ONTAP 9.12.0 及更早版本時、只有 ONTAP 次要系統支援備份。
** 目前不支援還原磁碟區的備份FlexGroup 。


* 資料保護磁碟區不支援使用*立即備份*按鈕進行臨機操作磁碟區備份。
* 不支援SM至BC組態。
* ONTAP 不支援從單一磁碟區到多個物件存放區的 SnapMirror 關係排除、因此 BlueXP 備份與還原不支援此組態。
* 目前Amazon S3、Azure和StorageGRID 支援物件存放區上的WORM /法規遵循模式。這稱為 DataLock 功能、必須使用 BlueXP 備份與還原設定來管理、而非使用雲端供應商介面。




=== 還原限制

這些限制同時適用於「搜尋與還原」和「瀏覽與還原」還原檔案與資料夾的方法、除非特別提出。

* 瀏覽與還原一次最多可還原100個個別檔案。
* 搜尋與還原一次可還原1個檔案。
* 使用ONTAP 支援更新版本的版本時、瀏覽與還原及搜尋與還原功能可還原資料夾及其中的所有檔案與子資料夾。
+
當使用ONTAP 版本高於9.11.1但在9.13.0之前的版本時、還原作業只能還原選取的資料夾和該資料夾中的檔案、而不會還原子資料夾或子資料夾中的檔案。

+
使用ONTAP 9.11.1版之前的版本時、不支援資料夾還原。

* 僅當叢集執行 ONTAP 9.13.1 以上版本時、才支援儲存在歸檔儲存設備中的資料還原目錄 / 資料夾。
* 僅當叢集執行 ONTAP 9.13.1 以上版本時、才支援使用 DataLock 保護的資料還原目錄 / 資料夾。
* FlexGroup Volume 備份目前不支援目錄 / 資料夾還原。
* 目前不支援從複製和 / 或本機快照還原目錄 / 資料夾。
* 不FlexGroup 支援從支援的範圍內將資料從支援的資料區還原為FlexVol 資料區、或FlexVol 將資料區還原FlexGroup 為資料區。
* 要還原的檔案必須使用與目的地Volume上語言相同的語言。如果語言不同、您將會收到錯誤訊息。
* 從Azure歸檔儲存設備還原資料至StorageGRID 支援的系統不支援_高_還原優先順序。
* 如果您備份 DP 磁碟區、然後決定中斷與該磁碟區的 SnapMirror 關係、則除非您同時刪除 SnapMirror 關係或反轉 SnapMirror 方向、否則無法將檔案還原至該磁碟區。
* 快速還原限制：
+
** 目的地位置必須是使用 ONTAP 9.13.0 或更新版本的 Cloud Volumes ONTAP 系統。
** 歸檔儲存設備中的備份不支援此功能。
** 只有在建立雲端備份的來源系統執行 ONTAP 9.12.1 或更新版本時、才支援 FlexGroup Volume 。
** 只有在建立雲端備份的來源系統執行 ONTAP 9.11.0 或更新版本時、才支援 SnapLock Volume 。






=== 搭配 Podcast 使用 RHEL 8 以上的限制



==== 不支援單一檔案還原

使用在 Podman 中執行的 BlueXP Connector （在 RHEL 8 或 9 上執行時手動建立 BlueXP Connector ）時、不支援單一檔案還原和目錄還原的瀏覽與還原功能。使用 Podman 時支援所有其他類型的還原作業、因此您可以使用下列其他方法還原資料、直到問題解決為止：

* 如果複寫磁碟區存在、請從複寫的磁碟區還原檔案或資料夾。
* 使用「搜尋與還原」功能、從雲端備份還原檔案或資料夾。
* 使用「瀏覽與還原」從雲端備份還原磁碟區、然後存取所需的檔案或資料夾。




==== 不支援雲端備份的勒索軟體掃描

使用 Podman 引擎時、不支援掃描雲端備份的勒索軟體。如果您使用 DataLock & 勒索軟體功能進行雲端備份、則必須停用勒索軟體掃描。 link:task-manage-backup-settings-ontap.html#enable-or-disable-ransomware-scans["瞭解如何停用勒索軟體掃描"]。
