---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database, dark site, private mode, restore database, backup and recovery, BlueXP Connector 
summary: 在無法存取網際網路的站台（稱為「私有模式」）中使用 BlueXP 備份與還原時、 BlueXP 備份與還原組態資料會備份到儲存備份的 StorageGRID 或 ONTAP S3 儲存區。如果您未來的 BlueXP Connector 主機系統發生問題、您可以部署新的 Connector 、並還原關鍵的 BlueXP 備份與還原資料。 
---
= 在黑暗的站台中還原 BlueXP 備份與還原資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在無法存取網際網路的站台中使用 BlueXP 備份與還原時、稱為 _private 模式 _ 、 BlueXP 備份與還原組態資料會備份到儲存備份的 StorageGRID 或 ONTAP S3 儲存區。如果 BlueXP  Connector 主機系統發生問題，您可以部署新的 Connector ，並還原重要的 BlueXP  備份與還原資料。

當您在雲端供應商部署 BlueXP  Connector 的 SaaS 環境中使用 BlueXP  備份與還原，或在擁有網際網路存取權的主機系統上使用時，所有重要的 BlueXP  備份與還原組態資料都會在雲端中備份與保護。如果您對 Connector 有任何問題、只要建立新的 Connector 並新增工作環境、備份詳細資料就會自動還原。

備份的資料有兩種類型：

* BlueXP 備份與還原資料庫：包含所有磁碟區、備份檔案、備份原則及組態資訊的清單。
* 索引型錄檔案 - 包含用於搜尋與還原功能的詳細索引、可讓您在尋找要還原的 Volume 資料時、快速又有效率地進行搜尋。


此資料每天午夜備份一次、每個檔案最多保留 7 份複本。如果 Connector 正在管理多個內部部署 ONTAP 工作環境、則 BlueXP 備份與還原檔案將位於最先啟動的工作環境中的工作環境中。


TIP: BlueXP 備份與還原資料庫或索引型錄檔案中從未包含任何 Volume 資料。



== 將 BlueXP  備份與還原資料還原至新的 BlueXP  Connector

如果內部部署的 BlueXP  Connector 發生災難性故障，您需要安裝新的 Connector ，然後將 BlueXP  備份與還原資料還原至新的 Connector 。

您必須執行下列工作，才能將 BlueXP  備份與還原系統恢復至正常運作狀態：

* 安裝新的BlueXP Connector
* 還原 BlueXP 備份與還原資料庫
* 還原索引型目錄檔案
* 重新探索ONTAP 所有內部的功能齊全的系統、StorageGRID 並將其整合到BlueXP UI上


一旦您確認系統恢復正常運作、建議您建立新的備份檔案。

.您需要的產品
您需要從儲存備份檔案的 StorageGRID 或 ONTAP S3 儲存區存取最新的資料庫和索引備份：

* BlueXP 備份與還原 MySQL 資料庫檔案
+
此檔案位於貯體中的下列位置 `netapp-backup-<GUID>/mysql_backup/`，其名稱為 `CBS_DB_Backup_<day>_<month>_<year>.sql`。

* 索引型錄備份 zip 檔案
+
此檔案位於貯體中的下列位置 `netapp-backup-<GUID>/catalog_backup/`，其名稱為 `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`。





=== 在新的內部部署Linux主機上安裝新的Connector

安裝新的BlueXP Connector時、請確定您下載的軟體版本與安裝在原始Connector上的軟體版本相同。對 BlueXP 備份與還原資料庫結構進行定期變更、可能會使較新的軟體版本與原始資料庫備份不相容。您可以 https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["還原備份資料庫後、將Connector軟體升級至最新版本"^]。

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["在新的內部部署Linux主機上安裝BlueXP Connector"^]
. 使用您剛建立的管理員使用者認證登入BlueXP。




=== 還原 BlueXP 備份與還原資料庫

. 將 MySQL 備份從備份位置複製到新的 Connector 主機。我們將使用下方的範例檔案名稱「 CBS_DB_Backup_23_05_2023.SQL 」。
. 根據您使用的是 Docker 或 Podman 容器、使用下列其中一個命令將備份複製到 MySQL 泊塢視窗容器：
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. 根據您使用的是 Docker 或 Podman 容器、使用下列其中一個命令進入 MySQL Container Shell ：
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. 在Container Shell中、部署「env」。
. 您需要MySQL資料庫密碼、因此請複製「MySQL_root_password」金鑰的值。
. 使用下列命令還原 BlueXP 備份與還原 MySQL DB ：
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. 使用下列 SQL 命令、確認 BlueXP 備份與還原 MySQL DB 已正確還原：
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
輸入密碼。

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
檢查顯示的磁碟區是否與原始環境中的磁碟區相同。





=== 還原索引型目錄檔案

. 將 Indexed Catalog 備份 zip 檔案（我們會使用範例檔案名稱「 Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip 」）從備份位置複製到「 /opt/application/NetApp/CBS 」資料夾中的新 Connector 主機。
. 使用下列命令解壓縮「 Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip 」檔案：
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. 執行 *ls* 命令、確定已建立資料夾「 catalogdb1 」、其下方有子資料夾「變更」和「快照」。




=== 探索ONTAP 您的叢集與StorageGRID 功能性系統

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["探索ONTAP 所有內部環境"^] 您先前環境中可用的。這包括您用作 S3 伺服器的 ONTAP 系統。
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["探索StorageGRID 您的系統"^]。




=== 設定StorageGRID 有關支援環境的詳細資料

在StorageGRID 原始Connector設定中使用設定時、新增與ONTAP 您的不支援功能環境相關的詳細資訊 https://docs.netapp.com/us-en/bluexp-automation/index.html["BlueXP API"^]。

下列資訊適用於從 BlueXP  3.9.xx 開始的私有模式安裝。對於較舊的版本，請使用下列程序 https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite Cloud Backup ： MySQL 和索引型錄備份與還原"^]：。

您必須針對每個將資料備份到 StorageGRID 的系統執行這些步驟。

. 使用下列O驗 證/權杖API擷取授權權杖。
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
雖然 IP 位址，使用者名稱和密碼是自訂值，但帳戶名稱不是。帳戶名稱一律為「 account-DARKSITE1 」。此外，使用者名稱必須使用電子郵件格式的名稱。

+
此API會傳回如下回應。您可以擷取授權權杖、如下所示。

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. 使用租戶/外部/資源API擷取工作環境ID和X-agent-ID。
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
此API會傳回如下回應。「資源識別碼」下的值代表_WorkingEnvironment ID_、而「agentId」下的值則代表_x-agent-id_。

. 使用與工作環境相關的 StorageGRID 系統詳細資料，更新 BlueXP  備份與還原資料庫。請務必輸入StorageGRID 完整的網域名稱、以及存取金鑰和儲存金鑰、如下所示：
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== 驗證 BlueXP 備份與還原設定

. 選取每ONTAP 個執行中的環境、然後按一下右窗格中備份與還原服務旁的*檢視備份*。
+
您應該能夠查看為磁碟區建立的所有備份。

. 在「還原儀表板」的「搜尋與還原」區段下、按一下「*索引設定*」。
+
請確定先前啟用「索引」目錄的工作環境仍保持啟用狀態。

. 在「搜尋與還原」頁面中、執行幾項目錄搜尋、以確認已成功完成索引目錄還原。

