---
sidebar: sidebar 
permalink: task-add-sqlhost-install-plugin-sql.html 
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for SQL, SQL, database, host, install, add host, discover 
summary: 在每個 SQL 資料庫主機上安裝適用於 SQL 的 SnapCenter 外掛程式。 
---
= 安裝適用於 SQL Server 的 SnapCenter 外掛程式、並新增資料庫主機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該在每個 SQL 資料庫主機上安裝 SnapCenter Plug-in for SQL Server 、新增資料庫主機、探索資料庫執行個體、以及設定資料庫執行個體的認證。



== 安裝適用於 SQL Server 的 SnapCenter 外掛程式

您應該下載外掛程式 *snapcenter_service_windows_host_plugin.exe* 、然後執行無聲安裝程式命令、在資料庫主機上安裝外掛程式。

.開始之前
* 您應確保符合下列先決條件。
+
** 已安裝 Net 4.7.2
** PowerShell 4.0 已安裝
** 可用的磁碟空間下限為 5 GB
** 可用的 RAM 大小下限為 4 GB


* 您應該執行 API 來完成客戶的登入。如需更多資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Tenant%20Registration/createTenant[]


.步驟
. 從 Connector 主機執行 API 來下載外掛程式。
`docker exec -it cloudmanager_scs_cloud curl 'http://127.0.0.1/api/v2/pluginpackage/windows'`
+
檔案的位置是： /var/lib/v泊 塢視窗 /Volumes/service-manager-2_cloudmanager_scse_cloue_Volume/_data/sc-windows-host-plugin/sapcenter_service_windows_host_plugin.exe <agent_version> 。

. 使用 scp 或其他替代方法、將連接器上的 _snapcenter_service_windows_host_plugin.exe_ 複製到每個 MSSQL Server 資料庫主機。
. 安裝外掛程式。
'"C ： //snapcenter_service_windows_host_plugin.exe" <install_folder> / 無聲 / 偵錯記錄 "C ： <install_folder> / HA 套件 _Silent_Install_SCSQL_Fresh ． log" /log"C ： //install 資料夾 / " BI_SNAPCENTER_port=8145 功能 ISInstall=SCSQL'
. 將自我簽署的憑證從 /var/lib/泊 塢視窗 /Volumes/service-manager-2_cloudmanager_SCS_cloue_Volume/_data/client/certificate /certificate .pem_ 複製到 MSSQL Server 資料庫主機。
+
如果您不使用預設憑證、也可以產生自我簽署的憑證或 CA 簽署的憑證。

. 在 Connector 主機中、將憑證從 .pem 轉換為 .crt 格式。
'openssl x509 -outform der -in certificate .pem -out certificate .crt '
. 按兩下憑證、將其新增至 * Personal * 和 * Trusted Root Certification Authorities * 儲存區。




== 新增 SQL Server 資料庫主機

您應該使用主機 FQDN 來新增 MSSQL 資料庫主機。

' 張貼 snapcenter.cloudmanager.cloud.netapp.com/api/v1/hosts'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Host%20Management/AddHosts[]

此 API 會建立可從 BlueXP UI 的 * 工作監控 * 標籤追蹤的工作。



=== 參數

|===
| 名稱 | 類型 | 必要 


 a| 
地址
 a| 
字串
 a| 
是的



 a| 
連接器ID
 a| 
字串
 a| 
是的



 a| 
plugin_type
 a| 
字串
 a| 
是的



 a| 
install_method
 a| 
字串
 a| 
是的



 a| 
plugin_port
 a| 
數量
 a| 
是的



 a| 
使用者名稱
 a| 
字串
 a| 
是的

|===


=== 回應

如果 API 執行成功、則會顯示回應碼 202 。

範例：

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== 檢視新增的 SQL Server 資料庫主機

您可以執行此 API 來檢視所有新增的 SQL Server 資料庫主機。

「取得 snapcenter.cloudmanager.cloud.netapp.com/api/v1/hosts'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Host%20Management/GetHosts[]



=== 回應

如果 API 執行成功、則會顯示回應碼 200 。

範例：

[listing]
----
{
  "num_records": 1,
    "total_records": 1,
    "records": [
        {
            "id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "addr": "scspa2722211001.rtp.openenglab.netapp.com",
            "status": "Running",
            "connector_id": "fBf8Iwbp4BscBfD02qBwWm6I03gGAesRclients",
            "plugin_port": 8145,
            "plugins": [
                {
                    "type": "mssql"
                }
            ],
            "os_type": "windows",
            "platform": "onprem",
            "username": "administrator",
            "operating_mode": "production"
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== 探索資料庫執行個體

您可以執行此 API 並輸入主機 ID 來探索所有的 MSSQL 執行個體。

' 張貼 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances/discovery'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/MSSQLInstancesDiscoveryRequest[]

此 API 會建立可從 BlueXP UI 的 * 工作監控 * 標籤追蹤的工作。



=== 參數

|===
| 名稱 | 類型 | 必要 


 a| 
host_id
 a| 
字串
 a| 
是的

|===


=== 回應

如果 API 執行成功、則會顯示回應碼 202 。

範例：

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== 檢視探索到的資料庫執行個體

您可以執行此 API 來檢視所有探索到的資料庫執行個體。

「取得 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/GetMSSQLInstancesRequest[]



=== 回應

如果 API 執行成功、則會顯示回應碼 200 。

範例：

[listing]
----
{
    "num_records": 2,
    "total_records": 2,
    "records": [
        {
            "id": "953e66de-10d9-4fd9-bdf2-bf4b0eaabfd7",
            "name": "scspa2722211001\\NAMEDINSTANCE1",
            "host_id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "status": "Running",
            "auth_mode": 0,
            "version": "",
            "is_clustered": false,
            "is_credentials_configured": false,
            "protection_mode": ""
        },
        {
            "id": "18e1b586-4c89-45bd-99c8-26268def787c",
            "name": "scspa2722211001",
            "host_id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "status": "Stopped",
            "auth_mode": 0,
            "version": "",
            "is_clustered": false,
            "is_credentials_configured": false,
            "protection_mode": ""
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== 設定資料庫執行個體認證

您可以執行此 API 來驗證及設定資料庫執行個體的認證。

' 張貼 snapcenter.cloudmanager.cloud.netapp.com/api/mssql//api/mssql/credentials-configuration'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/ConfigureCredentialRequest[]

此 API 會建立可從 BlueXP UI 的 * 工作監控 * 標籤追蹤的工作。



=== 參數

|===
| 名稱 | 類型 | 必要 


 a| 
host_id
 a| 
字串
 a| 
是的



 a| 
instance_ids
 a| 
字串
 a| 
是的



 a| 
使用者名稱
 a| 
字串
 a| 
是的



 a| 
密碼
 a| 
字串
 a| 
是的



 a| 
驗證模式
 a| 
字串
 a| 
是的

|===


=== 回應

如果 API 執行成功、則會顯示回應碼 202 。

範例：

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----