---
sidebar: sidebar 
permalink: task-add-host-discover-oracle-databases.html 
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for Oracle, Oracle, database, host, deploy, add host, discover 
summary: 在SnapCenter 每個Oracle資料庫主機上部署適用於Oracle的支援功能。 
---
= 部署SnapCenter 適用於Oracle的支援功能外掛程式、並新增資料庫主機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該在SnapCenter 每個Oracle資料庫主機上部署適用於Oracle的支援功能、新增資料庫主機、並探索主機上的資料庫、以指派原則並建立備份。

* 如果資料庫主機已啟用SSH、您可以使用下列其中一種方法來部署外掛程式：
+
** 部署外掛程式、並使用SSH選項新增裝載UI。 <<部署外掛程式、並使用SSH選項從UI新增主機,深入瞭解>>。
** 使用指令碼部署外掛程式、並使用手動選項從UI新增主機。 <<使用指令碼部署外掛程式、並使用手動選項從UI新增主機,深入瞭解>>。


* 如果停用SSH、請手動部署外掛程式、並使用手動選項從UI新增主機。 <<手動部署外掛程式、並使用手動選項從UI新增主機,深入瞭解>>。




== 先決條件

在新增主機之前、您應確保符合先決條件。

* 您應該已經建立了工作環境和Connector。
* 確保連接器可連線至工作環境和Oracle資料庫主機。
* 確定BlueXP使用者具有「帳戶管理員」角色。
* 確保每個Oracle資料庫主機上都已安裝Java 11（64位元）Oracle Java或OpenJDK、且已適當設定Java_Home變數。
* 您應該已經為SnapCenter 該位使用者建立了「Sudo」、並已設定「Sudo」SnapCenter 。如需相關資訊、請參閱 <<設定Sudo for SnapCenter S供 使用者使用>>。
* 如果使用SSH型部署、請確定連接器已啟用SSH連接埠的通訊（預設值：22）。
* 請確定連接器已啟用外掛連接埠的通訊（預設值：8145）、讓作業正常運作。




=== 設定Sudo for SnapCenter S供 使用者使用

您應該建立SnapCenter 一個供使用者使用的Sudo、然後為使用者設定該Sudo。

*步驟*

. 登入Connector VM。
. 下載SnapCenter 《支援Linux主機的二進位程式》。「Udo Docker執行- IT cloudmanager_SCs_cloul -X Get 'http://127.0.0.1/deploy/downloadLinuxPlugin'`[]
. 取得基本掛載路徑。「Udo Docker Volume ls | Grep SCS_Cloud Volume | awk｛'print $2'｝| xargs Sudo Docker Volume Check | Grep mountpoint」
. 將第1行從* oracle_checksum _scs.txt*檔案複製到第16行、該檔案位於* base _mount_path_/_version _/sc-Linux主機外掛程式/*。
. 登入Oracle資料庫主機、然後執行下列步驟：
+
.. 建立SnapCenter 這個使用者帳戶、私密金鑰配對、然後指派權限。如需相關資訊、請參閱 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/managing-users.html#create-user-account["建立使用者帳戶"^]。
.. 使用visudo Linux公用程式、將您在步驟4中複製的行貼到/etc/udoers_檔案。
+
在以上各行中、<LINUXUSER> 將您SnapCenter 建立的支援功能取代為「支援功能」使用者、並將檔案儲存到「視覺效果」公用程式中。







== 部署外掛程式、並使用SSH選項從UI新增主機

. 在BlueXP UI中、按一下* Protection *>* Backup and recovery *>* Applications*。
. 按一下「探索應用程式」。
. 選取* Cloud Native *、然後按一下* Next*。
+
我們建立了一個具有「_SURFSystem_ SnapCenter 」角色的服務帳戶、以針對此帳戶中的所有使用者執行排程的資料保護作業。

+
** 按一下*帳戶*>*管理帳戶*>*成員*以檢視服務帳戶。
+

NOTE: 服務帳戶（_SnapCenter-account-<accounttid>_）用於執行排程的備份作業。切勿刪除服務帳戶。



. 在「Add Host（新增主機）」頁面中、執行下列步驟：
+
.. 選擇*使用SSH*。
.. 指定要安裝外掛程式之主機的FQDN或IP位址。
.. 指定使用者名稱（<<Configure a sudo for SnapCenter user,Sudo SnapCenter S答案 使用者>>）將外掛程式套件複製到主機的方法。
.. 指定SSH和外掛程式連接埠。
+
預設SSH連接埠為22、外掛程式連接埠為8145。

+
您可以在安裝外掛程式之後、關閉應用程式主機上的SSH連接埠。任何其他外掛程式作業都不需要SSH連接埠。

.. 選取連接器。
.. （選用）如果連接器與主機之間未啟用「金鑰較少」驗證、則應指定用於與主機通訊的SSH私密金鑰。
+

NOTE: SSH私密金鑰不會儲存在應用程式的任何位置、也不會用於任何其他作業。

.. 單擊 * 下一步 * 。
+
*** 顯示主機上的所有資料庫。如果已停用資料庫的OS驗證、您應該按一下「*設定*」來設定資料庫驗證。如需詳細資訊、請參閱 <<設定Oracle資料庫認證>>。
*** 按一下*設定*並選取*主機*以檢視所有主機。按一下「*移除*」移除資料庫主機。
+

NOTE: 檢視特定主機的篩選器無法運作。當您在篩選器中指定主機名稱時、會顯示所有主機。

*** 按一下*設定*、然後選取*原則*以檢視預設原則。檢閱預先設定的原則、如果您想要編輯這些原則以符合您的需求、或是建立新的原則。








== 使用指令碼部署外掛程式、並使用手動選項從UI新增主機

如果啟用Oracle主機上的SSH金鑰型驗證供SnapCenter 支援對象使用、您可以執行下列步驟來部署外掛程式。在執行這些步驟之前、請先確認已啟用連接器的SSH連線。

*步驟*

. 登入Connector VM。
. 取得基本掛載路徑。「Udo Docker Volume ls | Grep SCS_Cloud Volume | awk｛'print $2'｝| xargs Sudo Docker Volume Check | Grep mountpoint」
. 使用Connector中提供的輔助程式指令碼來部署外掛程式。
`sudo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`
+
** host_name是Oracle主機的名稱、這是必要的參數。
** SSH_KEY_file是SnapCenter 支援此功能的使用者SSH金鑰、用於連線至Oracle主機。這是必要參數。
** 使用者名稱：SnapCenter Oracle主機上具有SSH權限的支援對象、這是選用參數。預設值為EC2使用者。
** SSH_port：Oracle主機上的SSH連接埠、此為選用參數。預設值為22
** plugin_port：外掛程式使用的連接埠、這是選用參數。預設值為8145
** 安裝目錄：要部署外掛程式的目錄、此為選用參數。預設值為/opt。
+
例如：
`sudo /var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh --host xxx.xx.x.x --sshkey /keys/netapp-ssh.ppk`



. 在BlueXP UI中、按一下* Protection *>* Backup and recovery *>* Applications*。
. 按一下「探索應用程式」。
. 選取* Cloud Native *、然後按一下* Next*。
+
我們建立了一個具有「_SURFSystem_ SnapCenter 」角色的服務帳戶、以針對此帳戶中的所有使用者執行排程的資料保護作業。

+
** 按一下*帳戶*>*管理帳戶*>*成員*以檢視服務帳戶。
+

NOTE: 服務帳戶（_SnapCenter-account-<accounttid>_）用於執行排程的備份作業。切勿刪除服務帳戶。



. 在「Add Host（新增主機）」頁面中、執行下列步驟：
+
.. 選擇*手動*。
.. 指定部署外掛程式之主機的FQDN或IP位址。
+
請確定連接器可以使用FQDN或IP位址與資料庫主機通訊。

.. 指定外掛程式連接埠。
+
預設連接埠為8145。

.. 選取連接器。
.. 選取核取方塊、確認外掛程式已安裝在主機上
.. 按一下「*探索應用程式*」。
+
*** 顯示主機上的所有資料庫。如果已停用資料庫的OS驗證、您應該按一下「*設定*」來設定資料庫驗證。如需詳細資訊、請參閱 <<設定Oracle資料庫認證>>。
*** 按一下*設定*並選取*主機*以檢視所有主機。按一下「*移除*」移除資料庫主機。
+

NOTE: 檢視特定主機的篩選器無法運作。當您在篩選器中指定主機名稱時、會顯示所有主機。

*** 按一下*設定*、然後選取*原則*以檢視預設原則。檢閱預先設定的原則、如果您想要編輯這些原則以符合您的需求、或是建立新的原則。








== 手動部署外掛程式、並使用手動選項從UI新增主機

如果未在Oracle資料庫主機上啟用SSH金鑰型驗證、您應該執行下列手動步驟來部署外掛程式、然後使用手動選項從UI新增主機。

*步驟*

. 登入Connector VM。
. 下載SnapCenter 《支援Linux主機的二進位程式》。「Udo Docker執行- IT cloudmanager_SCs_cloul -X Get 'http://127.0.0.1/deploy/downloadLinuxPlugin'`[]
. 取得基本掛載路徑。「Udo Docker Volume ls | Grep SCS_Cloud Volume | awk｛'print $2'｝| xargs Sudo Docker Volume Check | Grep mountpoint」
. 取得下載外掛程式的二進位路徑。「Udo ls <base_mount_path>$(sudo dod泊 塢視窗ps | grep -po" cloudmanager_SCs_clou:.*？"| sed -e 's/*$/'| cut -F2 -d":")/sc-Linux主機外掛程式/snapcenter_Linux主機外掛程式_scsscs.bin"
. 使用scp或其他替代方法、將_snapcenter_Linux主機_plugin_scs.bin_複製到每個Oracle資料庫主機。
+
_snapcenter_Linux主機外掛程式_SCS.bin_應複製到SnapCenter 可由該位使用者存取的位置。

. 使用SnapCenter 支援程式碼的使用者帳戶登入Oracle資料庫主機、然後執行下列命令來啟用二進位檔的執行權限。
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. 將Oracle外掛程式部署為Sudo SnapCenter Sudo Sudo使用者。
`./snapcenter_linux_host_plugin_scs.bin -i silent -DSPL_USER=<snapcenter-user>`
. 從連接器VM的_<base_mount_path>/用戶端/憑證/_路徑、複製_imple.p12_到外掛主機的_/var/opt/snapcenter/spl/etc/_。
. 瀏覽至_/var/opt/snapcenter/spl/etc/、然後執行keytoole命令以匯入憑證。「keytool-v -importkeystore -srckeystore CERT.p12 -srcstoretype pkcs12 -destkeystore keyKeystore .jks -deststoretype JKS -rcsstorepass SnapCenter sore-ascalias SnapCenter agentcert -noprompt」
. 重新啟動SPL：「系統重新啟動spl」
. 從Connector執行下列命令、驗證外掛程式是否可從Connector存取。
`docker exec -it cloudmanager_scs_cloud curl -ik \https://<FQDN or IP of the plug-in host>:<plug-in port>/getVersion --cert /config/client/certificate/certificate.pem --key /config/client/certificate/key.pem`
. 在BlueXP UI中、按一下* Protection *>* Backup and recovery *>* Applications*。
. 按一下「探索應用程式」。
. 選取* Cloud Native *、然後按一下* Next*。
+
我們建立了一個具有「_SURFSystem_ SnapCenter 」角色的服務帳戶、以針對此帳戶中的所有使用者執行排程的資料保護作業。

+
** 按一下*帳戶*>*管理帳戶*>*成員*以檢視服務帳戶。
+

NOTE: 服務帳戶（_SnapCenter-account-<accounttid>_）用於執行排程的備份作業。切勿刪除服務帳戶。



. 在「Add Host（新增主機）」頁面中、執行下列步驟：
+
.. 選擇*手動*。
.. 指定部署外掛程式之主機的FQDN或IP位址。
+
請確定連接器可以使用FQDN或IP位址與資料庫主機通訊。

.. 指定外掛程式連接埠。
+
預設連接埠為8145。

.. 選取連接器。
.. 選取核取方塊、確認外掛程式已安裝在主機上
.. 按一下「*探索應用程式*」。
+
*** 顯示主機上的所有資料庫。如果已停用資料庫的OS驗證、您應該按一下「*設定*」來設定資料庫驗證。如需詳細資訊、請參閱 <<設定Oracle資料庫認證>>。
*** 按一下*設定*並選取*主機*以檢視所有主機。按一下「*移除*」移除資料庫主機。
+

NOTE: 檢視特定主機的篩選器無法運作。當您在篩選器中指定主機名稱時、會顯示所有主機。

*** 按一下*設定*、然後選取*原則*以檢視預設原則。檢閱預先設定的原則、如果您想要編輯這些原則以符合您的需求、或是建立新的原則。








== 設定Oracle資料庫認證

您應該設定用於在Oracle資料庫上執行資料保護作業的認證資料。

*步驟*

. 如果已停用資料庫的OS驗證、您應該按一下「*設定*」來設定資料庫驗證。
. 指定使用者名稱、密碼及連接埠詳細資料。
+
如果資料庫位於ASM上、您也應該設定ASM設定。

+
Oracle使用者應該擁有Sysdba權限、而ASM使用者應該擁有Sysasm權限。

. 按一下「*設定*」。

