---
sidebar: sidebar 
permalink: task-backup-cloud-native-sql-data.html 
keywords: BlueXP, scheduled backups, on-demand backups, create policy, SQL database 
summary: 建立原則、指派原則、然後建立 SQL 資料庫的隨選備份。 
---
= 備份雲端原生 Microsoft SQL Server 資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以指派所建立的原則來建立排程或隨需備份。



== 建立備份原則

您可以執行此 API 來建立備份原則。

' 張貼 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backup/policies'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backup%20Policies/MSSQLBackupPolicyService_CreateMSSQLBackupPolicy[]

此 API 會建立可從 BlueXP UI 的 * 工作監控 * 標籤追蹤的工作。



=== 參數

|===
| 名稱 | 類型 | 必要 


 a| 
名稱
 a| 
字串
 a| 
是的



 a| 
backup_type
 a| 
字串
 a| 
是的



 a| 
Copy_only_backup
 a| 
字串
 a| 
錯



 a| 
is_system_defined
 a| 
字串
 a| 
錯



 a| 
backup_name_format
 a| 
字串
 a| 
是的



 a| 
schedule_type
 a| 
字串
 a| 
是的



 a| 
start_tim
 a| 
數量
 a| 
是的



 a| 
hours 時間間隔
 a| 
數量
 a| 
是的



 a| 
Minutes_interval
 a| 
數量
 a| 
是的



 a| 
retion_type
 a| 
字串
 a| 
是的



 a| 
retion_count
 a| 
數量
 a| 
是的



 a| 
End_time_time
 a| 
數量
 a| 
是的

|===


=== 回應

如果 API 執行成功、則會顯示回應碼 201 。

範例：

[listing]
----
{
    "_links": {
    "self": {
        "href": "/api/resourcelink"
      }
    }
}
----


== 將原則指派給 SQL 資料庫執行個體

您可以執行此 API 、將原則指派給 SQL 資料庫執行個體。

' 張貼 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances/{id}/policy-assignment'

其中、 _id_ 是執行探索資料庫執行個體 API 所取得的 MSSQL 執行個體 ID 。如需詳細資訊、請參閱 link:task-add-sqlhost-install-plugin-sql.html#discover-the-database-instances["探索資料庫執行個體"]。

ID 陣列是此處的輸入。例如：

[listing]
----
[
  "c9f3e68d-1f9c-44dc-b9af-72a9dfc54320"
]
----
如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Policy%20Assignment/PostMSSQLInstanceAssignPolicyRequest[]

此 API 會建立可從 BlueXP UI 的 * 工作監控 * 標籤追蹤的工作。



=== 回應

如果 API 執行成功、則會顯示回應碼 202 。

範例：

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== 建立隨選備份

您可以執行此 API 來建立隨選備份。

' 張貼 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backups/CreateMSSQLBackupRequest[]

此 API 會建立可從 BlueXP UI 的 * 工作監控 * 標籤追蹤的工作。



=== 參數

|===
| 名稱 | 類型 | 必要 


 a| 
ID


NOTE: 這是 MSSQL 資料庫執行個體的 ID 。
 a| 
字串
 a| 
是的



 a| 
resource_type
 a| 
字串
 a| 
是的



 a| 
policy_id
 a| 
字串
 a| 
是的



 a| 
schedule_type
 a| 
字串
 a| 
是的

|===


=== 回應

如果 API 執行成功、則會顯示回應碼 202 。

範例：

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== 檢視備份

您可以執行這些 API 來列出所有備份、也可以檢視特定備份的詳細資料。

「取得 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups'

「取得 snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups/{id}'

如需詳細資訊、請參閱： https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backups/MSSQLGetBackupsRequest[]



=== 回應

如果 API 執行成功、則會顯示回應碼 200 。

範例：

[listing]
----
{
    "total_records": 1,
    "num_records": 1,
    "records": [
        {
            "backup_id": "602d7796-8074-43fc-a178-eee8c78566ac",
            "resource_id": "a779578d-cf78-46f3-923d-b9223255938c",
            "backup_name": "Hourly_policy2_scspa2722211001_NAMEDINSTANCE1_2023_08_08_07_02_01_81269_0",
            "policy_name": "policy2",
            "schedule_type": "Hourly",
            "start_time": "2023-08-08T07:02:10.203Z",
            "end_time": "0001-01-01T00:00:00Z",
            "backup_status": "success",
            "backup_type": "FullBackup"
        }
    ],
    "_links": {
        "next": {}
    }
}
----