---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: 您可以將SQL Server資料庫從雲端還原至內部部署SnapCenter 的伺服器。 
---
= 還原SQL Server資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以將SQL Server資料庫還原至同一部主機或替代主機。不支援恢復記錄備份及重新建立可用性群組。


IMPORTANT: 不支援單一檔案還原（SFR）。

*步驟*

. 在BlueXP UI中、按一下* Protection *>* Backup and recovery *>* Applications*。
. 在*篩選條件*欄位中、選取篩選條件*類型*、然後從下拉式清單中選取* SQL*。
. 按一下「*檢視詳細資料*」以檢視所有可用的備份。
. 選取備份、然後按一下*還原*。
. 選取您要還原資料庫檔案的位置。
+
|===
| 如果您... | 執行此動作... 


 a| 
想要將資料庫還原至建立備份的同一 SQL Server 主機
 a| 
選取 * 將資料庫還原至建立備份的同一主機 * 。



 a| 
想要將資料庫還原至建立備份的同一或不同主機中的不同 SQL Server
 a| 
選取 * 將資料庫還原至其他主機 * 。

選取主機名稱、提供資料庫名稱（選用）、選取執行個體、然後指定還原路徑。


NOTE: 替代路徑中提供的副檔名必須與原始資料庫檔案的副檔名相同。

如果「還原範圍」頁面中未顯示*將資料庫還原為替代主機*選項、請清除瀏覽器快取。

|===
. 如果快照位於歸檔儲存設備中、請指定從歸檔儲存設備還原資料的優先順序。
. 在「*預先還原選項*」頁面上、選取下列其中一個選項：
+
** 選取*還原期間以相同名稱覆寫資料庫*、以相同名稱還原資料庫。
** 選取*保留SQL資料庫複寫設定*以還原資料庫並保留現有的複寫設定。


. 在「*還原後選項*」頁面上、若要指定資料庫狀態以還原其他交易記錄、請選取下列其中一個選項：
+
** 如果您要立即還原所有必要的備份、請選取*運作中、但無法使用*。
+
這是預設行為、可藉由復原未提交的交易、讓資料庫隨時可供使用。您必須先建立備份、才能還原其他交易記錄。

** 選擇*非作業性、但可用*、可讓資料庫維持非作業狀態、而不會回復未提交的交易。
+
可還原其他交易記錄。您必須等到資料庫恢復後才能使用。

** 選取*唯讀模式、然後選取可用*以將資料庫保留為唯讀模式。
+
此選項會取消未提交的交易、但會將已復原的動作儲存在待命檔案中、以便還原還原還原效果。

+
如果啟用「復原目錄」選項、則會還原更多交易記錄。如果交易記錄的還原作業不成功、則變更可以回溯。SQL Server文件包含更多資訊。



. 檢閱詳細資料、然後按一下*還原*。

