---
sidebar: sidebar 
permalink: task-restore-hana-backup.html 
keywords: restore, mount application backups, SAP HANA database 
summary: 您可以將 SAP HANA 資料庫從雲端還原至內部部署的 SnapCenter Server 。 
---
= 使用 BlueXP 備份和復原來還原 SAP HANA 資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 BlueXP 備份和還原將 SAP HANA 資料庫還原到任何主機

*步驟*

. 在BlueXP UI中、按一下* Protection *>* Backup and recovery *>* Applications*。
. 在 * 篩選條件 * 欄位中、選取篩選條件 * 類型 * 、然後從下拉式清單中選取 * HANA * 。
. 按一下您要還原之資料庫的*檢視詳細資料*、然後按一下*還原*。
. 在「還原選項」頁面中、指定下列其中一項：
+
.. 對於 NAS 環境、請指定要將從物件存放區還原的磁碟區匯出至的主機的 FQDN 或 IP 位址。
.. 對於 SAN 環境、請指定主機的啟動器、將從物件存放區還原的磁碟區 LUN 對應到該主機的啟動器。


. 如果快照位於歸檔儲存設備中、請選擇從歸檔儲存設備還原資料的優先順序。
. 如果來源儲存空間不足、或來源儲存空間關閉、請選取 * 變更儲存位置 * 。
+
如果您選取 * 變更儲存位置 * 、您可以將尾碼附加至目的地磁碟區。如果尚未選中該複選框，則默認情況下會將 *_restore * 附加到目標卷。

. 單擊 * 下一步 * 。
. 在「儲存設備對應」頁面中、指定儲存物件存放區還原資料的替代儲存位置詳細資料。
. 單擊 * 下一步 * 。
. 檢閱詳細資料、然後按一下*還原*。


此作業只會匯出指定主機上所選備份的儲存區。您應該手動掛載檔案系統並開啟資料庫。使用磁碟區之後、儲存管理員可以從 ONTAP 叢集刪除磁碟區。

如需有關如何啟動 SAP HANA 資料庫的資訊、請參閱 https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667：利用SnapCenter 下列功能自動化SAP HANA系統複製與複製作業"^]。


NOTE: 如果還原作業未完成，請勿再次嘗試還原程序，直到「工作監控」顯示還原作業失敗為止。如果您在「工作監視器」顯示還原作業失敗之前再次嘗試還原程序，還原作業將會再次失敗。當您看到「工作監控」狀態為「失敗」時，可以再次嘗試還原程序。
