---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: 在 BlueXP 中註冊適用於 VMware vSphere 主機的 SnapCenter 外掛程式。 
---
= 註冊 VMware vSphere 主機的 SnapCenter 外掛程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該在 BlueXP 中註冊 VMware vSphere 主機的 SnapCenter 外掛程式、以便顯示資料存放區和虛擬機器。只有具有管理存取權的使用者才能登錄 VMware vSphere 主機的 SnapCenter 外掛程式。


NOTE: 您可以在 BlueXP 中註冊多個適用於 VMware vSphere 主機的 SnapCenter 外掛程式。不過、一旦註冊後、您就無法移除適用於 VMware vSphere 主機的 SnapCenter 外掛程式。

.步驟
. 在BlueXP UI中、按一下* Protection *>* Backup and recovery *>* Virtual Machines *。
. 從*設定*下拉式清單中、按一下* SnapCenter 適用於VMware vSpher*的「*」「外掛程式」。
. 按一下「*登錄SnapCenter VMware vSpher*的更新外掛程式」。
. 請指定下列詳細資料：
+
.. 在 SnapCenter Plug-in for VMware vSphere 欄位中、指定 SnapCenter Plug-in for VMware vSphere 主機的 FQDN 或 IP 位址。
.. 在連接埠欄位中、指定 SnapCenter Plug-in for VMware vSphere 主機執行的連接埠編號。
+
您應確保在內部部署的 SnapCenter Plug-in for VMware vSphere 主機（在預設 8144 連接埠上執行）和 BlueXP Connector 執行個體（可在任何雲端供應商（ Amazon Web Services 、 Microsoft Azure 、 Google Cloud Platform ）或內部部署中執行）之間、能夠進行通訊。

.. 在使用者名稱和密碼欄位中、指定具有系統管理員角色的使用者認證。


. 按一下 * 註冊 * 。


*完成後*

按一下 * 備份與還原 * > * 虛擬機器 * 、即可檢視所有使用 VMware vSphere 主機的已註冊 SnapCenter 外掛程式保護的資料存放區和虛擬機器。
