---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: 瞭解Cloud Backup的新功能。 
---
= Cloud Backup的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解Cloud Backup的新功能。



== 2022年9月28日



=== Cloud Backup for Applications的增強功能

* 支援Google Cloud Platform（GCP）和StorageGRID 支援以備份應用程式一致的快照
* 建立自訂原則
* 支援歸檔儲存
* 備份SAP HANA應用程式
* 備份VMware環境中的Oracle和SQL應用程式
* 從內部部署的二線儲存設備備份應用程式
* 停用備份
* 取消登SnapCenter 錄伺服器




=== 增強了適用於虛擬機器的Cloud Backup功能

* 支援StorageGRID 使用支援還原來備份一或多個資料存放區
* 建立自訂原則




== 2022年9月19日



=== DataLock和勒索軟體保護功能可設定用於StorageGRID 支援還原系統中的備份檔案

上一版針對儲存在Amazon S3儲存區的備份推出_DataLock和勒索軟體Protection。此版本可擴充對StorageGRID 儲存在還原系統中的備份檔案的支援。如果您的叢集使用ONTAP 的是更新版本的版本、StorageGRID 而您的系統執行的是11.6.0.3或更新版本、則可使用此新的備份原則選項。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["深入瞭解如何使用DataLock和勒索軟體保護來保護備份"^]。

請注意、您必須執行3.9.22版或更新版本軟體的Connector。連接器必須安裝在您的內部環境中、而且可以安裝在有或沒有網際網路存取的站台中。



=== 資料夾層級的還原功能現在可從您的備份檔案取得

現在、如果您需要存取該資料夾（目錄或共用）中的所有檔案、可以從備份檔案還原資料夾。還原資料夾比還原整個磁碟區更有效率。此功能可用於使用瀏覽與還原方法及使用ONTAP 版本更新版本的搜尋與還原方法進行還原作業。此時您只能選取及還原單一資料夾、而且只會還原該資料夾中的檔案、而不會還原子資料夾或子資料夾中的檔案。



=== 檔案層級還原現在可從已移至歸檔儲存設備的備份取得

過去您只能從已移至歸檔儲存設備的備份檔案還原磁碟區（僅限AWS和Azure）。現在您可以從這些已歸檔的備份檔案還原個別檔案。此功能可用於使用瀏覽與還原方法及使用ONTAP 版本更新版本的搜尋與還原方法進行還原作業。



=== 檔案層級還原現在提供覆寫原始來源檔案的選項

過去、還原至原始磁碟區的檔案一律會以新檔案的形式還原、並以「RESE_」為前置詞。現在、您可以選擇在將檔案還原至磁碟區上的原始位置時、覆寫原始來源檔案。此功能可用於使用「瀏覽與還原」方法和「搜尋與還原」方法進行還原作業。



=== 拖放以啟用「雲端備份至StorageGRID 不支援的系統」

如果是 https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 備份的目的地在畫版上會以工作環境的形式存在、您可以將內部ONTAP 作業環境拖曳到目的地、以啟動Cloud Backup設定精靈。



== 2022年8月18日



=== 新增支援以保護雲端原生應用程式資料

Cloud Backup for Applications是一項SaaS型服務、可為NetApp Cloud Storage上執行的應用程式提供資料保護功能。在BlueXP中啟用的雲端應用程式備份、可針對位於Amazon FSX for NetApp ONTAP 上的Oracle資料庫、提供有效率且應用程式一致的原則型備份與還原功能。https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html["深入瞭解"^]。



=== Azure Blob的備份檔案現在支援搜尋與還原功能

現在、將備份檔案儲存在Azure Blob儲存設備中的使用者、可以使用「搜尋與還原」方法來還原磁碟區和檔案。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["瞭解如何使用Search  Restore還原磁碟區和檔案"^]。

請注意、連接器角色需要其他權限才能使用此功能。使用3.9.21版軟體（2022年8月）部署的Connector包含這些權限。如果您使用舊版部署Connector、則需要手動新增權限。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["如有必要、請參閱如何新增這些權限"^]。



=== 我們新增了保護備份檔案免受刪除和勒索軟體攻擊的能力

雲端備份現在支援物件鎖定功能、可進行勒索軟體安全的備份。如果您的叢集使用ONTAP 的是VMware版本的更新版本、而您的備份目的地是Amazon S3、則現在可以使用名為_DataLock和勒索軟體Protection的新備份原則選項。DataLock可保護您的備份檔案、避免遭到修改或刪除、勒索軟體保護功能會掃描您的備份檔案、尋找勒索軟體攻擊備份檔案的證據。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["深入瞭解如何使用DataLock和勒索軟體保護來保護備份"^]。

請注意、連接器角色需要其他權限才能使用此功能。使用3.9.21版軟體部署的Connector包含這些權限。如果您使用舊版部署Connector、則需要手動新增權限。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html#set-up-s3-permissions["如有必要、請參閱如何新增這些權限"^]。



=== Cloud Backup現在支援使用自訂SnapMirror標籤建立的原則

以前、Cloud Backup僅支援預先定義的SnapMirror標籤、例如每小時、每日、每週、每小時和每年。現在Cloud Backup可以探索SnapMirror原則、這些原則具有您使用System Manager或CLI建立的自訂SnapMirror標籤。這些新標籤會顯示在Cloud Backup UI中、讓您可以使用所選的SnapMirror標籤、將磁碟區備份到雲端。



=== 針對功能完善的其他備份原則ONTAP

部分備份原則頁面已重新設計、可讓您更輕鬆地檢視每ONTAP 個叢集中可供磁碟區使用的所有備份原則。如此一來、您就能更輕鬆地查看可用原則的詳細資料、以便在磁碟區上套用最佳原則。



=== 拖放以啟用Cloud Backup至Azure Blob和Google Cloud Storage

如果是 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-azure-blob.html["Azure Blob"^] 或 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-gcp-storage.html["Google Cloud Storage"^] 備份的目的地是在畫版上的工作環境、您可以將內部ONTAP 的功能環境（Cloud Volumes ONTAP 安裝於Azure或GCP）拖曳到目的地、以啟動備份設定精靈。

此功能已適用於Amazon S3儲存區。



== 2022年7月13日



=== 支援已新增至備份SnapLock 支援的支援功能

現在、您可以使用Cloud Backup將SnapLock 非公有雲和私有雲備份到其中。此功能需要ONTAP 您的不知道系統執行ONTAP 的是版本不符合更新版本的版本。不過、目前不支援「符合性」磁碟區。SnapLock



=== 現在、您可以在使用內部部署Connector時、在公有雲中建立備份檔案

過去、您需要在建立備份檔案的相同雲端供應商中部署Connector。現在、您可以使用部署在內部部署的Connector、從內部ONTAP 部署的支援系統建立備份檔案、以將檔案備份到Amazon S3、Azure Blob和Google Cloud Storage。（在StorageGRID 還原系統上建立備份檔案時、一律需要內部連接器。）



=== 建立ONTAP 適用於不支援的系統的備份原則時、也提供其他功能

* 現在可以按年度排程進行備份。每年備份的預設保留值為1、但如果您想要存取多個前幾年的備份檔案、可以變更此值。
* 您可以命名備份原則、以便以更多描述性文字來識別原則。




== 2022年6月14日



=== 我們新增支援功能、可在ONTAP 無法存取網際網路的站台中備份內部部署的叢集資料

如果您的內部ONTAP 使用的叢集位於無法存取網際網路的站台、也稱為暗站或離線站台、現在您可以使用Cloud Backup將Volume資料備份到StorageGRID 位於同一個站台的NetApp作業系統。此功能需要同時在離線站台部署BlueXP Connector（3.9.19或更新版本）。

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["瞭解如何在離線站台中安裝Connector"]。https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html["瞭解如何在ONTAP 離線網站上備份不只是StorageGRID 資料的功能"]。



=== 適用於虛擬機器的Cloud Backup 1.1.0現已上市

您可以將SnapCenter VMware vSphere的VMware vSphere的VMware vCenter外掛程式與BlueXP整合、以保護虛擬機器上的資料。您可以將資料存放區備份到雲端、SnapCenter 並輕鬆將虛擬機器還原回內部部署的VMware vSphere版的內部部署功能。

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html["深入瞭解如何將虛擬機器保護至雲端"]。



=== 不需要Cloud Restore執行個體、ONTAP 即可執行瀏覽與還原功能

用於從S3和Blob儲存設備進行檔案層級瀏覽與還原作業時、需要使用獨立的雲端還原執行個體/虛擬機器。此執行個體不使用時會關閉、但還原檔案時仍會增加一些時間和成本。此功能已由免費容器取代、可在需要時部署在Connector上。它具有下列優點：

* 無需增加檔案層級還原作業的成本
* 加快檔案層級的還原作業
* 在內部部署安裝Connector時、可支援從雲端瀏覽及還原檔案作業


請注意、如果您先前使用Cloud Restore執行個體/ VM、將會自動移除。雲端備份程序會每天執行一次、以刪除所有舊的Cloud Restore執行個體。這項變更是完全透明的、不會對您的資料造成任何影響、而且您不會注意到備份或還原工作有任何變更。



=== 瀏覽及還原Google Cloud和StorageGRID 支援不支援的檔案

新增瀏覽與還原作業的容器（如上所述）之後、現在即可從儲存在Google Cloud和StorageGRID 更新系統中的備份檔案執行檔案還原作業。現在、瀏覽與還原可用於還原所有公有雲供應商和StorageGRID 來自於整個過程的檔案。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore["瞭解如何使用Browse  Restore從ONTAP 您的還原備份還原磁碟區和檔案"]。



=== 拖放以啟用雲端備份至S3儲存設備

如果您的備份Amazon S3目的地是在Canvas上的工作環境、您可以將內部ONTAP 的支援叢集或Cloud Volumes ONTAP 支援系統（安裝於AWS中）拖曳到Amazon S3工作環境、以啟動設定精靈。



=== 自動將備份原則套用至Kubernetes叢集中新建立的磁碟區

如果您在雲端備份啟動後、將新的持續磁碟區新增至Kubernetes叢集、過去您需要記住為這些磁碟區設定備份。現在、您可以選取要自動套用至新建立磁碟區的原則 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes["從_備份設定_頁面"] 適用於已啟動Cloud Backup的叢集。



=== 雲端備份API現在可用於管理備份與還原作業

API可從取得 https://docs.netapp.com/us-en/cloud-manager-automation/cbs/overview.html[]。請參閱 link:api-backup-restore.html["本頁"] 以取得API總覽。



== 2022年5月2日



=== Google Cloud Storage中的備份檔案現在支援搜尋與還原

四月推出的「搜尋與還原」方法、可還原磁碟區和檔案、適用於將備份檔案儲存在AWS中的使用者。現在、將備份檔案儲存在Google Cloud Storage中的使用者可以使用這項功能。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["瞭解如何使用Search  Restore還原磁碟區和檔案"]。



=== 設定要自動套用至Kubernetes叢集中新建立之磁碟區的備份原則

如果您在雲端備份啟動後、將新的持續磁碟區新增至Kubernetes叢集、過去您需要記住為這些磁碟區設定備份。現在、您可以選取要自動套用至新建立磁碟區的原則。當為新的Kubernetes叢集啟動Cloud Backup時、此選項可在設定精靈中使用。



=== 雲端備份現在需要授權、才能在工作環境中啟動

雲端備份的授權實作方式有幾項變更：

* 您必須先向雲端供應商註冊PAYGO Marketplace訂閱、或向NetApp購買BYOL授權、才能啟動Cloud Backup。
* 30天免費試用版僅適用於從雲端供應商訂閱PAYGO的情況、使用BYOL授權時無法使用。
* 免費試用版從Marketplace訂閱開始的那一天開始。例如、如果您在針對Cloud Volumes ONTAP 某個系統使用Marketplace訂閱30天之後啟動免費試用版、雲端備份試用版將無法使用。


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html["深入瞭解可用的授權模式"]。



== 2022年4月4日



=== Cloud Backup for Applications 1.1.0 SnapCenter （以支援功能為基礎）現已成為正式上市

全新的雲端應用程式備份功能可讓您將現有的Oracle與Microsoft SQL應用程式一致的Snapshot（備份）、從內部部署的主要儲存設備卸載到Amazon S3或Azure Blob的雲端物件儲存設備。

必要時、您可以將這些資料從雲端還原至內部部署。

link:concept-protect-app-data-to-cloud.html["深入瞭解如何將內部部署應用程式資料保護至雲端"]。



=== 全新的搜尋與還原功能、可在ONTAP 所有的還原檔案中搜尋磁碟區或檔案

現在、您可以ONTAP 透過*全部的支援檔案*、以部分或完整的Volume名稱、部分或完整的檔案名稱、大小範圍及其他搜尋篩選條件來搜尋Volume或檔案。如果您不確定哪個叢集或磁碟區是資料的來源、這是尋找您要還原資料的絕佳新方法。 link:task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["瞭解如何使用搜尋"]。



== 2022年3月3日



=== 能夠將持續磁碟區從GKE Kubernetes叢集備份到Google Cloud儲存設備

如果您的GKE叢集已安裝NetApp Astra Trident、而且使用Cloud Volumes ONTAP 適用於GCP的功能作為叢集的後端儲存設備、則您可以在Google Cloud儲存設備之間備份及還原持續的磁碟區。 link:task-backup-kubernetes-to-gcp.html["如需詳細資料、請前往此處"]。



=== 此版本已停止使用Cloud Data Sense掃描雲端備份檔案的試用版功能



== 2022年2月14日



=== 現在、您可以將備份原則指派給單一叢集中的個別磁碟區

過去您只能將單一備份原則指派給叢集中的所有磁碟區。現在、您可以為單一叢集建立多個備份原則、並將不同的原則套用至不同的磁碟區。 link:task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes["瞭解如何為叢集建立新的備份原則、並將其指派給所選的磁碟區"]。



=== 新選項可讓您自動將預設備份原則套用至新建立的磁碟區

過去、在雲端備份啟動之後、在工作環境中建立的新磁碟區、需要您手動套用備份原則。現在、無論磁碟區是在BlueXP、System Manager、CLI中建立、或是使用API建立、Cloud Backup都會探索磁碟區、並套用您選擇做為預設原則的備份原則。

在新的工作環境中啟用備份時、或從現有工作環境的「管理磁碟區」頁面啟用備份時、都可使用此選項。



=== 新的工作監控器可供查看所有備份與還原工作的處理中狀態

當您針對多個磁碟區啟動作業（例如變更備份原則或刪除備份）時、「工作監視器」會很有幫助、因此您可以查看所有磁碟區上的作業何時完成。 link:task-monitor-backup-jobs.html["瞭解如何使用工作監控器"]。



== 2022年1月2日



=== 能夠將持續磁碟區從您的KS Kubernetes叢集備份到Azure Blob儲存設備

如果您的叢集已安裝NetApp Astra Trident、而且使用Cloud Volumes ONTAP 適用於Azure的for Azure做為叢集的後端儲存設備、則您可以備份及還原Azure Blob儲存設備的磁碟區。 link:task-backup-kubernetes-to-azure.html["如需詳細資料、請前往此處"]。



=== 本次發表中已變更了各項收費、以更貼近業界標準Cloud Backup Service

現在您只需支付所保護資料的費用、而非根據備份檔案的大小來支付NetApp的容量費用、這是根據ONTAP 正在ONTAP 備份的來源供應區的邏輯使用容量（不含不含還原效率）計算而得。此容量也稱為前端TB（FTB）。



== 2021年11月28日



=== 能夠將持續磁碟區從EKS Kubernetes叢集備份到Amazon S3

如果您的EKS叢集已安裝NetApp Astra Trident、而且使用Cloud Volumes ONTAP 適用於AWS的叢集後端儲存設備、則您可以在Amazon S3之間備份及還原磁碟區。 link:task-backup-kubernetes-to-s3.html["如需詳細資料、請前往此處"]。



=== 增強備份DP磁碟區的功能

Cloud Backup現在支援在ONTAP SVM-DR關係中、建立目標支援的DP磁碟區備份。有幾項限制、請參閱 link:concept-ontap-backup-to-cloud.html#limitations["限制"] 以取得詳細資料。



== 2021年11月5日



=== 可在將Volume還原至內部部署ONTAP 的作業系統時、選擇私有端點

從ONTAP Amazon S3或Azure Blob上的備份檔案將磁碟區還原至內部部署的支援系統時、現在您可以選擇一個私有端點、以私密且安全的方式連線至內部部署系統。



=== 現在、您可以在數天後將舊的備份檔案分層保存至歸檔儲存設備、以節省成本

如果您的叢集執行ONTAP 的是版本為NetApp 9.10.1或更新版本、而且您使用的是AWS或Azure雲端儲存設備、則可以將備份分層處理至歸檔儲存設備。如需詳細資訊、請參閱 link:reference-aws-backup-tiers.html["AWS S3歸檔儲存類別"] 和 link:reference-azure-backup-tiers.html["Azure Blob歸檔存取層"]。



=== Cloud Backup BYOL授權已移至Digital Wallet中的「Data Services Licenses（資料服務授權）」索引標籤

Cloud Backup的BYOL授權已從Cloud Backup授權索引標籤移至BlueXP數位錢包的資料服務授權索引標籤。



== 2021年10月4日



=== 執行磁碟區或檔案還原時、備份檔案大小現在可在「備份」頁面中使用

如果您想要刪除不必要的大型備份檔案、或是比較備份檔案大小、找出任何可能因為惡意軟體攻擊而造成的異常備份檔案、這很有用。



=== TCO計算機可用來比較雲端備份成本

總體擁有成本計算機可協助您瞭解Cloud Backup的總體擁有成本、並將這些成本與傳統備份解決方案進行比較、並預估可能的節約效益。歡迎來看看https://cloud.netapp.com/cloud-backup-service-tco-calculator["請按這裡"^]。



=== 能夠取消註冊工作環境的Cloud Backup

現在您可以輕鬆完成 link:task_manage_backups.html#unregistering-cloud-backup-for-a-working-environment["取消登錄工作環境的Cloud Backup"] 如果您不想再為該工作環境使用備份功能（或付費）、



== 2021年9月2日



=== 能夠建立磁碟區的隨需備份

現在您可以隨時建立隨需備份、以擷取Volume的目前狀態。如果已對磁碟區進行重要變更、但您不想等待下一次排程備份來保護該資料、這項功能就很實用。

link:task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time["瞭解如何建立隨需備份"]。



=== 能夠定義私有介面連線、以便安全備份至Amazon S3

從內部部署ONTAP 的Sing系統將備份設定至Amazon S3時、現在您可以在啟動精靈中定義與私有介面端點的連線。這可讓您使用網路介面、將內部部署系統以私人且安全的方式連線至AWS Private Link所提供的服務。 link:task-backup-onprem-to-aws.html#preparing-amazon-s3-for-backups["請參閱此選項的詳細資料"]。



=== 現在、您可以在將資料備份至Amazon S3時、選擇自己的客戶管理金鑰來進行資料加密

為了加強安全性與控制、您可以在啟動精靈中選擇自己的客戶管理金鑰來進行資料加密、而非使用預設的Amazon S3加密金鑰。從內部部署ONTAP 的功能系統或Cloud Volumes ONTAP AWS的功能系統設定備份時、可使用此功能。



=== 現在、您可以從擁有超過30、000個檔案的目錄還原檔案
