---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection, sql server, workloads, volumes, snapshots' 
summary: 瞭解 BlueXP 備份與還原的新功能。 
---
= BlueXP 備份與還原的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 BlueXP 備份與還原的新功能。



== 2025 年 14 月 7 日

此 BlueXP  備份與還原版本包含下列更新。



=== 增強型ONTAP卷儀表板

2025 年 4 月，我們推出了增強型ONTAP卷儀表板的預覽版，它速度更快、更有效率。

此儀表板旨在協助企業客戶處理大量工作負載。即使對於擁有 20,000 個卷的客戶，新儀表板也能在 10 秒內加載完成。

預覽版成功上線，並獲得了許多預覽版用戶的正面回饋，我們現已將其設為所有客戶的預設體驗。準備好迎接極速儀表板吧！

如需詳細資訊、請參閱 link:br-use-dashboard.html["在儀表板中查看保護健康狀況"]。



=== Microsoft SQL Server 工作負載支援作為公共技術預覽

此版本的BlueXP backup and recovery提供了更新的使用者介面，可讓您使用BlueXP backup and recovery服務中熟悉的 3-2-1 保護策略來管理 Microsoft SQL Server 工作負載。使用此新版本，您可以將這些工作負載備份到主存儲，複製到輔助存儲，然後備份到雲端物件儲存。

您可以透過完成此步驟註冊預覽 https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["預覽註冊表"^] 。


NOTE: 本文檔旨在介紹如何保護 Microsoft SQL Server 工作負載，目前僅提供技術預覽版。 NetAppNetApp在正式發布之前修改此預覽版產品詳細資訊、內容和時間表的權利。

此版本的BlueXP backup and recovery包括以下更新：

* *3-2-1 備份功能*：此版本整合了SnapCenter功能，讓您能夠透過BlueXP backup and recovery使用者介面使用 3-2-1 資料保護策略來管理和保護您的SnapCenter資源。
* *從SnapCenter匯入*：您可以將SnapCenter備份資料和原則匯入BlueXP backup and recovery。
* *重新設計的使用者介面*為管理備份和復原任務提供了更直覺的體驗。
* *備份目標*：您可以在 Amazon Web Services (AWS)、Microsoft Azure Blob Storage、 StorageGRID和ONTAP S3 環境中新增儲存桶，以用作 Microsoft SQL Server 工作負載的備份目標。
* *工作負載支援*：此版本支援您備份、還原、驗證和複製 Microsoft SQL Server 資料庫和可用性群組。（未來版本將添加對其他工作負載的支援。）
* *靈活的復原選項*：此版本可讓您在發生損壞或意外資料遺失的情況下將資料庫還原至原始位置和備用位置。
* *即時生產副本*：在幾分鐘內（而不是幾小時或幾天）產生用於開發、測試或分析的節省空間的生產副本。
* 此版本包括建立詳細報告的功能。


有關保護 Microsoft SQL Server 工作負載的詳細信息，請參閱link:br-use-mssql-protect-overview.html["保護 Microsoft SQL Server 工作負載概述"] 。



== 2025 年 6 月 09 日

此 BlueXP  備份與還原版本包含下列更新。



=== 索引目錄支援更新

2025 年 2 月，我們推出了更新的索引功能（索引目錄 v2），您可以在「搜尋和還原」資料還原方法中使用此功能。上一版本顯著提升了本地環境中的資料索引效能。在此版本中，索引目錄現已可在 Amazon Web Services、Microsoft Azure 和 Google Cloud Platform (GCP) 環境中使用。

如果您是新客戶，所有新環境均預設啟用索引目錄 v2。如果您是現有客戶，您可以重新索引您的環境以利用索引目錄 v2。

.如何啟用索引？
在您使用「搜尋與還原」方法還原資料之前，您必須先在每個準備還原磁碟區或檔案的來源工作環境上啟用「索引」。執行搜尋和復原時，選擇“啟用索引”選項。

索引目錄可以追蹤每個捲和備份文件，使您的搜尋快速且有效率。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["啟用搜尋和還原索引"]參閱。



=== Azure 專用連結終結點與服務終點

通常， BlueXP backup and recovery會與雲端提供者建立一個私有端點來處理保護任務。此版本引入了一項可選設置，可讓您啟用或停用 BlueXP 備份和恢復自動建立私有端點的功能。如果您希望更好地控制私有端點的建立流程，這項設定可能會對您有所幫助。

您可以在啟用保護或開始復原程序時啟用或停用此選項。

如果停用此設置，則必須手動建立專用端點，以確保 BlueXP 備份和復原功能正常運作。如果沒有正確的連接，您可能無法成功執行備份和還原任務。



=== ONTAP S3 上支援 SnapMirror 到雲端重新同步

上一版本引入了對 SnapMirror 到雲端重新同步 (SM-C Resync) 的支援。此功能簡化了 NetApp 環境中磁碟區遷移期間的資料保護。此版本增加了對 ONTAP S3 以及其他與 S3 相容的提供者（例如 Wasabi 和 MinIO）上的 SM-C Resync 的支援。



=== 為 StorageGRID 帶來自己的儲存桶

當您在物件儲存中為工作環境建立備份檔案時，BlueXP 備份和復原功能會預設在您設定的物件儲存帳戶中為備份檔案建立容器（儲存桶或儲存帳戶）。之前，您可以覆寫此設置，並為 Amazon S3、Azure Blob Storage 和 Google Cloud Storage 指定您自己的容器。在此版本中，您現在可以自備 StorageGRID 物件儲存容器。

請參閱。 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["建立您自己的物件儲存容器"]



== 2025 年 13 月 5 日

此 BlueXP  備份與還原版本包含下列更新。



=== SnapMirror 到雲端的重新同步功能，可進行大量移轉

SnapMirror 至雲端重新同步功能可簡化 NetApp 環境中磁碟區移轉期間的資料保護與持續運作。當使用 SnapMirror 邏輯複寫（ LRSE ），從內部部署的 NetApp 部署移轉到另一個部署，或移轉到雲端型解決方案（例如 Cloud Volumes ONTAP 或 Cloud Volumes Service ）時， SnapMirror 到雲端重新同步可確保現有的雲端備份保持完整且正常運作。

這項功能不需要耗時且資源密集的重新基準作業，讓備份作業能夠在移轉後繼續進行。此功能在工作負載移轉案例中非常重要，可同時支援 FlexVols 和 FlexGroups ，並可從 ONTAP 9.16.1 版開始使用。

SnapMirror to Cloud Resync 可維持跨環境的備份持續運作，進而提升營運效率，並降低混合式和多雲端資料管理的複雜度。

如需如何執行重新同步作業的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-migrate-resync.html["使用 SnapMirror 移轉磁碟區至雲端重新同步"]。



=== 支援第三方 MinIO 物件存放區（預覽）

BlueXP  備份與還原現在將支援延伸至第三方物件儲存區，主要著重於 MinIO 。這項新的預覽功能可讓您運用任何與 S3 相容的物件儲存區，滿足備份與還原需求。

使用此預覽版本，我們希望能在完整功能推出之前，確保與協力廠商物件儲存區緊密整合。我們鼓勵您探索這項新功能，並提供意見回饋，以協助提升服務品質。


IMPORTANT: 此功能不應用於正式作業。

* 預覽模式限制 *

在預覽此功能時，有某些限制：

* 不支援自帶鏟斗（ BYOB ）。
* 不支援在原則中啟用 DataLock 。
* 不支援在原則中啟用歸檔模式。
* 僅支援內部部署 ONTAP 環境。
* 不支援 MetroCluster 。
* 不支援啟用貯體層級加密的選項。


* 快速入門 *

若要開始使用此預覽功能，您必須在 BlueXP  Connector 上啟用旗標。接著，您可以在備份區段中選擇 * 協力廠商相容 * 物件存放區，在保護工作流程中輸入 MinIO 協力廠商物件存放區的連線詳細資料。



== 2025 年 4 月 16 日

此 BlueXP  備份與還原版本包含下列更新。



=== UI 改善

此版本可簡化介面，提升您的使用體驗：

* 將 Aggregate 資料行從 Volumes 資料表中移除，以及從 V2 Dashboard 的 Volume 資料表中移除 Snapshot Policy ， Backup Policy 和 Replication Policy 資料行，將會產生更精簡的配置。
* 從下拉式清單中排除未啟動的工作環境，可減少介面雜亂，導覽效率更高，載入速度更快。
* 在標記欄上排序已停用時，您仍可檢視標記，確保重要資訊仍可輕鬆存取。
* 移除保護圖示上的標籤有助於更簡潔的外觀，並減少載入時間。
* 在工作環境啟動程序期間，對話方塊會顯示一個載入圖示，以提供意見回饋，直到探索程序完成為止，以提高系統作業的透明度和信心。




=== 增強型 Volume Dashboard （預覽）

Volume Dashboard 現在可在 10 秒內完成載入，提供更快，更有效率的介面。此預覽版本可提供給特定客戶，讓他們及早瞭解這些改善項目。



=== 支援第三方 WASBI 物件存放區（預覽）

BlueXP  備份與還原現在將支援延伸至第三方物件儲存區，主要著重於 WASBI 。這項新的預覽功能可讓您運用任何與 S3 相容的物件儲存區，滿足備份與還原需求。



==== WASBI 入門

若要開始使用第三方儲存設備做為物件存放區，您必須在 BlueXP  Connector 中啟用旗標。然後，您可以輸入第三方物件存放區的連線詳細資料，並將其整合至備份與還原工作流程。

.步驟
. SSH 連接到您的連接器。
. 進入 BlueXP  備份與恢復 CBS 伺服器容器：
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 透過 VIM 或任何其他編輯器開啟 `default.json`資料夾內的檔案 `config`：
+
[listing]
----
vi default.json
----
. 修改 `allow-s3-compatible`： false 至 `allow-s3-compatible`： true 。
. 儲存變更。
. 從容器結束。
. 重新啟動 BlueXP  備份與恢復 CBS 伺服器容器。


.結果
容器再次開啟後，開啟 BlueXP  備份與還原 UI 。當您開始備份或編輯備份策略時，您會看到新的供應商「 S3 相容」清單，以及 AWS ， Microsoft Azure ， Google Cloud ， StorageGRID 和 ONTAP S3 的其他備份供應商。



==== 預覽模式限制

在預覽此功能時，請考慮下列限制：

* 不支援自帶鏟斗（ BYOB ）。
* 不支援在原則中啟用 DataLock 。
* 不支援在原則中啟用歸檔模式。
* 僅支援內部部署 ONTAP 環境。
* 不支援 MetroCluster 。
* 不支援啟用貯體層級加密的選項。


在此預覽期間，我們鼓勵您探索這項新功能，並在完整功能推出之前，提供與協力廠商物件存放區整合的意見反應。



== 2025 年 3 月 17 日

此 BlueXP  備份與還原版本包含下列更新。



=== SMB 快照瀏覽

此 BlueXP  備份與還原更新解決了一項問題，使客戶無法在 SMB 環境中瀏覽本機快照。



=== AWS GovCloud 環境更新

此 BlueXP  備份與還原更新解決了由於 TLS 憑證錯誤而導致 UI 無法連線至 AWS GovCloud 環境的問題。此問題已透過使用 BlueXP  Connector 主機名稱而非 IP 位址來解決。



=== 備份原則保留限制

以前， BlueXP  備份與還原 UI 將備份限制為 999 份，而 CLI 則允許更多複本。現在，您可以將多達 4 ， 000 個磁碟區附加至備份原則，並包含 1 ， 018 個未附加至備份原則的磁碟區。此更新包含其他驗證，可避免超過這些限制。



=== SnapMirror 雲端重新同步

此更新可確保在刪除 SnapMirror 關係之後，無法從不支援的 ONTAP 版本的 BlueXP  備份與還原啟動 SnapMirror 雲端重新同步。



== 2025 年 21 月 2 日

此 BlueXP  備份與還原版本包含下列更新。



=== 高效能索引

BlueXP  備份與還原引進更新的索引功能，可讓來源工作環境上的資料索引更有效率。新的索引功能包括 UI 更新，還原資料的「搜尋與還原」方法效能提升，全球搜尋功能升級，擴充性更佳。

以下是改善項目的細目：

* * 資料夾整合 * ：更新版本會使用包含特定識別碼的名稱將資料夾群組在一起，使索引程序更順暢。
* * 硬碟檔案壓縮 * ：更新版本可減少用於建立每個磁碟區索引的檔案數量，簡化程序並免除額外資料庫的需求。
* * 以更多工作階段進行橫向擴充 * ：新版本新增更多工作階段來處理索引工作，加速程序。
* * 支援多個索引容器 * ：新版本使用多個容器來更好地管理及散佈索引工作。
* * 分割索引工作流程 * ：新版本將索引程序分為兩個部分，以提升效率。
* * 改善的並行處理 * ：新版本可同時刪除或移動目錄，加速索引程序。


.誰能從這項功能中獲益？
所有新客戶都能使用新的索引功能。

.如何啟用索引？
在您使用「搜尋與還原」方法還原資料之前，您必須先在每個準備還原磁碟區或檔案的來源工作環境上啟用「索引」。這可讓「索引型錄」追蹤每個磁碟區和每個備份檔案，讓您的搜尋快速又有效率。

執行「搜尋與還原」時，選取「啟用索引」選項，即可在來源工作環境上啟用索引。

有關詳細信息，請參閱文檔 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["如何使用搜尋擴大機還原 ONTAP 資料；還原"]。

.支援的擴充
新的索引功能支援下列項目：

* 不到 3 分鐘即可達到全域搜尋效率
* 多達 50 億個檔案
* 每個叢集最多 5000 個磁碟區
* 每個磁碟區最多可有 1 ，上限的快照
* 基準索引的最長時間少於 7 天。實際時間會因您的環境而異。




=== 全球搜尋效能提升

此版本也包含全球搜尋效能的增強功能。現在您將看到進度指標和更詳細的搜尋結果，包括檔案數和搜尋所需時間。專屬的搜尋和索引容器可確保在五分鐘內完成全域搜尋。

請注意下列與全域搜尋相關的考量事項：

* 新索引不會在標示為每小時的快照上執行。
* 新的索引功能僅適用於 FlexVols 上的快照，不適用於 FlexGroups 上的快照。




== 2025 年 13 月 2 日

此 BlueXP  備份與還原版本包含下列更新。



=== BlueXP backup and recovery預覽版

BlueXP backup and recovery的預覽版本提供了更新的使用者介面，讓您能夠使用BlueXP backup and recovery服務中熟悉的 3-2-1 保護策略來管理 Microsoft SQL Server 工作負載。使用此新版本，您可以將這些工作負載備份到主存儲，複製到輔助存儲，然後備份到雲端物件儲存。


NOTE: 本文檔作為技術預覽提供。透過此預覽方案、 NetApp 保留在「一般供應」之前修改產品詳細資料、內容和時間表的權利。

此版本的BlueXP backup and recovery預覽版 2025 包括以下更新。

* 重新設計的使用者介面為管理備份和復原任務提供了更直覺的體驗。
* 預覽版可讓您備份和還原 Microsoft SQL Server 資料庫。（未來版本將添加對其他工作負載的支援。）
* 此版本整合了SnapCenter功能，使您能夠透過BlueXP backup and recovery使用者介面使用 3-2-1 資料保護策略來管理和保護您的SnapCenter資源。
* 此版本可讓您將SnapCenter工作負載匯入BlueXP backup and recovery。




== 2024 年 22 月 11 日

此 BlueXP  備份與還原版本包含下列更新。



=== SnapLock Compliance 和 SnapLock Enterprise 保護模式

BlueXP  備份與還原現在可以備份使用 SnapLock Compliance 或 SnapLock Enterprise 保護模式設定的 FlexVol 和 FlexGroup 內部部署磁碟區。您的叢集必須執行 ONTAP 9.14 或更新版本、才能獲得此支援。自 ONTAP 9.11.1 版起、就支援使用 SnapLock 企業模式備份 FlexVol Volume 。較早的 ONTAP 版本不支援備份 SnapLock 保護磁碟區。

請參閱中支援磁碟區的完整清單 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["瞭解 BlueXP 備份與還原"]。



=== 「磁碟區」頁面上的「搜尋與還原程序索引」

在使用搜尋與還原之前、您必須在每個要從中還原Volume資料的來源工作環境上啟用「索引」。這可讓 Indexed Catalog 追蹤每個磁碟區的備份檔案。「 Volume 」頁面現在會顯示索引狀態：

* 索引：已建立磁碟區索引。
* 進行中
* 非索引
* 索引已暫停
* 錯誤
* 未啟用




== 2024 年 9 月 27 日

此 BlueXP  備份與還原版本包含下列更新。



=== 透過瀏覽與還原、在 RHEL 8 或 9 上支援 Podman

BlueXP  備份與還原現在支援在使用 Podman 引擎的 Red Hat Enterprise Linux （ RHEL ）第 8 版和第 9 版上進行檔案與資料夾還原。這適用於 BlueXP  備份與還原瀏覽與還原方法。

BlueXP  Connector 3.9.40 版支援某些版本的 Red Hat Enterprise Linux 第 8 版和第 9 版、可在 RHEL 8 或 9 主機上手動安裝 Connector 軟體、而不受中所述作業系統以外的位置 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["主機需求"^]限制。這些較新的 RHEL 版本需要使用 Podman 引擎、而非 Docker 引擎。以前、 BlueXP  備份與還原在使用 Podman 引擎時有兩項限制。這些限制已移除。

https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["深入瞭解如何從備份檔案還原 ONTAP 資料"]。



=== 目錄索引速度更快、可改善搜尋與還原

此版本包含改良的目錄索引、可更快完成基準索引。快速索引可讓您更快速地使用「搜尋與還原」功能。

https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["深入瞭解如何從備份檔案還原 ONTAP 資料"]。
