---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery' 
summary: 瞭解 BlueXP 備份與還原的新功能。 
---
= BlueXP 備份與還原的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 BlueXP 備份與還原的新功能。



== 2024 年 11 月 6 日



=== SnapLock Compliance 和 SnapLock Enterprise 保護模式

BlueXP  備份與還原現在可以備份使用 SnapLock Compliance 或 SnapLock Enterprise 保護模式設定的 FlexVol 和 FlexGroup 內部部署磁碟區。您的叢集必須執行 ONTAP 9.14 或更新版本、才能獲得此支援。自 ONTAP 9.11.1 版起、就支援使用 SnapLock 企業模式備份 FlexVol Volume 。較早的 ONTAP 版本不支援備份 SnapLock 保護磁碟區。

請參閱中支援磁碟區的完整清單 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["瞭解 BlueXP 備份與還原"]。



=== 「磁碟區」頁面上的「搜尋與還原程序索引」

在使用搜尋與還原之前、您必須在每個要從中還原Volume資料的來源工作環境上啟用「索引」。這可讓 Indexed Catalog 追蹤每個磁碟區的備份檔案。「 Volume 」頁面現在會顯示索引狀態：

* 索引：已建立磁碟區索引。
* 進行中
* 非索引
* 索引已暫停
* 錯誤
* 未啟用




== 2024 年 9 月 27 日



=== 透過瀏覽與還原、在 RHEL 8 或 9 上支援 Podman

BlueXP  備份與還原現在支援在使用 Podman 引擎的 Red Hat Enterprise Linux （ RHEL ）第 8 版和第 9 版上進行檔案與資料夾還原。這適用於 BlueXP  備份與還原瀏覽與還原方法。

BlueXP  Connector 3.9.40 版支援某些版本的 Red Hat Enterprise Linux 第 8 版和第 9 版、可在 RHEL 8 或 9 主機上手動安裝 Connector 軟體、而不受中所述作業系統以外的位置 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["主機需求"^]限制。這些較新的 RHEL 版本需要使用 Podman 引擎、而非 Docker 引擎。以前、 BlueXP  備份與還原在使用 Podman 引擎時有兩項限制。這些限制已移除。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["深入瞭解如何從備份檔案還原 ONTAP 資料"]。



=== 目錄索引速度更快、可改善搜尋與還原

此版本包含改良的目錄索引、可更快完成基準索引。快速索引可讓您更快速地使用「搜尋與還原」功能。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["深入瞭解如何從備份檔案還原 ONTAP 資料"]。



== 2024 年 7 月 22 日



=== 還原小於 1 GB 的磁碟區

使用此版本、您現在可以還原在 ONTAP 中建立的小於 1 GB 的磁碟區。您可以使用 ONTAP 建立的最小磁碟區大小為 20 MB 。



=== 如何降低 DataLock 成本的秘訣

DataLock 功能可保護您的備份檔案、避免在指定的時間內遭到修改或刪除。這有助於保護您的檔案免受勒索軟體攻擊。

如需有關 DataLock 的詳細資訊及如何降低相關成本的秘訣，請 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["備份至物件原則設定"]參閱。



=== AWS IAM 角色隨處整合

Amazon Web Services （ AWS ） Identity and Access Management （ IAM ） Roles Anywhere 服務可讓您為工作負載（ AWS 外部）使用 IAM 角色和短期認證、以安全的方式存取 AWS API 、就像您在工作負載上使用 IAM 角色一樣。當您在任何位置使用 IAM 角色的私密金鑰基礎架構和 AWS Token 時、您不需要長期 AWS 存取金鑰和秘密金鑰。這可讓您更頻繁地輪換認證、進而提升安全性。

在此版本中、 AWS IAM 角色 Anywhere 服務的支援是技術預覽。

ifdef::aws[]

這適用於link:task-backup-to-s3.html["將 Cloud Volumes ONTAP 備份至 AWS"]。這適用於link:task-backup-onprem-to-aws.html["將內部部署的 ONTAP 資料備份至 AWS"]。

endif::aws[]

請參閱 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXP 備份與還原 2024 年 7 月版本部落格"]。



=== FlexGroup 資料夾或目錄還原功能現已可供使用

以前、 FlexVol 磁碟區可以還原、但您無法還原 FlexGroup 資料夾或目錄。使用 ONTAP 9.15.1 P2 、您可以使用「瀏覽與還原」選項來還原 FlexGroup 資料夾。

在此版本中、支援 FlexGroup 資料夾還原是技術預覽。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-browse-restore["使用瀏覽安培還原資料夾與檔案"]參閱。

如需手動啟用的詳細資料、請 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXP 備份與還原 2024 年 7 月版本部落格"]參閱。



== 2024 年 5 月 17 日



=== 在內部部署 Connector 上使用 RHEL 8 和 RHEL 9 時的限制

BlueXP Connector 3.9.40 版支援某些版本的 Red Hat Enterprise Linux 第 8 版和第 9 版、可在 RHEL 8 或 9 主機上手動安裝 Connector 軟體、無論中提及的作業系統以外的位置為何 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["主機需求"^]。這些較新的 RHEL 版本需要使用 Podman 引擎、而非 Docker 引擎。目前、 BlueXP 備份與還原在使用 Podman 引擎時有兩項限制。

請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["備份與還原限制"] 以取得詳細資料。

下列程序包含新的 Podcast 說明：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["重新啟動 BlueXP 備份與還原"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["在黑暗的站台中還原 BlueXP 備份與還原資料"]




== 2024 年 4 月 30 日



=== 能夠啟用或停用排程的勒索軟體掃描

以前、您可以啟用或停用勒索軟體掃描、但無法在排程掃描中執行此動作。

使用此版本、您現在可以使用「進階設定」頁面上的選項、在最新的 Snapshot 複本上啟用或停用排程的勒索軟體掃描。如果啟用、預設會每週執行掃描。您可以將排程變更為天或週、或停用、節省成本。

如需詳細資訊、請參閱下列資訊：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["管理備份設定"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["管理 ONTAP 磁碟區的原則"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["備份至物件原則設定"]




== 2024 年 4 月 4 日



=== 能夠啟用或停用勒索軟體掃描

以前、當您在備份原則中啟用勒索軟體偵測時、會在建立第一個備份時、以及還原備份時自動進行掃描。以前、服務會掃描所有 Snapshot 複本、您無法停用掃描。

使用此版本、您現在可以使用「進階設定」頁面上的選項、在最新的 Snapshot 複本上啟用或停用勒索軟體掃描。如果啟用、預設會每週執行掃描。

如需詳細資訊、請參閱下列資訊：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["管理備份設定"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["管理 ONTAP 磁碟區的原則"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["備份至物件原則設定"]


ifdef::aws[]

請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["將Cloud Volumes ONTAP 不支援的資料備份至Amazon S3"]和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["將Cloud Volumes ONTAP 無法取得的資料備份到Azure Blob"]。

endif::aws[]



== 2024 年 3 月 12 日



=== 能夠從雲端備份到內部部署 ONTAP 磁碟區進行「快速還原」

現在、您可以從雲端儲存區執行磁碟區的 _ 快速還原 _ 至內部部署的 ONTAP 目的地 Volume 。以前您只能對 Cloud Volumes ONTAP 系統執行快速還原。如果您需要儘快提供對磁碟區的存取、快速還原是災難恢復的理想選擇。快速還原比完整磁碟區還原快得多；它會將中繼資料從雲端快照還原至 ONTAP 目的地磁碟區。來源可能來自 AWS S3 、 Azure Blob 、 Google Cloud Services 或 NetApp StorageGRID 。

內部部署 ONTAP 目的地系統必須執行 ONTAP 9.14.1 版或更新版本。

您可以使用「瀏覽與還原」程序、而非「搜尋與還原」程序來執行此作業。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["從備份檔案還原 ONTAP 資料"]。



=== 能夠從 Snapshot 和 Replication 複本還原檔案和資料夾

以前、您只能從 AWS 、 Azure 和 Google Cloud Services 的備份複本還原檔案和資料夾。現在、您可以從本機 Snapshot 複本和複寫複本還原檔案和資料夾。

您可以使用「搜尋與還原」程序來執行此功能、而非使用「瀏覽與還原」程序。



== 2024 年 2 月 1 日



=== 虛擬機器的 BlueXP 備份與還原增強功能

* 支援將虛擬機器還原至其他位置
* 支援不保護資料存放區




== 2023 年 12 月 15 日



=== 適用於本機 Snapshot 和複寫 Snapshot 複本的報告

以前、您只能在備份複本上產生報告。現在、您也可以在本機 Snapshot 複本和複寫 Snapshot 複本上建立報告。

使用這些報告、您可以執行下列動作：

* 確保關鍵資料受到組織原則的保護。
* 確保一組磁碟區的備份作業順利進行。
* 為您的正式作業資料提供保護證明。


請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["報告資料保護涵蓋範圍"]。



=== 可在磁碟區上使用自訂標記進行排序和篩選

您現在可以將自訂標記新增至 ONTAP 9.13.1 中的磁碟區、以便在工作環境中和跨工作環境將磁碟區分組在一起。如此一來、您就能在 BlueXP 備份與還原 UI 頁面中排序磁碟區、並在報告中篩選。



=== 目錄備份保留 30 天

以前、 Catalog.zip 備份會保留 7 天。現在、他們會保留 30 天。

請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["在黑暗的站台中還原 BlueXP 備份與還原資料"]。



== 2023 年 10 月 23 日



=== 在備份啟動期間建立 3-2-1 備份原則

之前、您必須先建立自訂原則、才能啟動 Snapshot 、複寫或備份。現在您可以使用 BlueXP 備份與還原 UI 、在備份啟動程序期間建立原則。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["深入瞭解原則"]。



=== 支援隨需快速還原 ONTAP 磁碟區

BlueXP 備份與還原現在提供從雲端儲存設備快速還原磁碟區至 Cloud Volumes ONTAP 系統的功能。如果您需要儘快提供對磁碟區的存取、快速還原是災難恢復的理想選擇。快速還原可將中繼資料從備份檔案還原至磁碟區、而非還原整個備份檔案。

Cloud Volumes ONTAP 目的地系統必須執行 ONTAP 9.13.0 版或更新版本。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["深入瞭解還原資料"]。

BlueXP 備份與還原工作監視器也會顯示快速還原工作進度的相關資訊。



=== 支援「工作監控」中的排程工作

BlueXP 備份與還原工作監控先前監控的排程磁碟區對物件儲存區備份與還原工作、但不是透過 UI 或 API 排程的本機 Snapshot 、複寫、備份與還原工作。

BlueXP 備份與還原工作監視器現在包含排程工作、可用於本機快照、複製及備份至物件儲存設備。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["深入瞭解更新的工作監控器"]。



== 2023 年 10 月 13 日



=== 應用程式（雲端原生）的 BlueXP 備份與還原功能增強功能

* Microsoft SQL Server 資料庫
+
** 支援 Amazon FSX for NetApp ONTAP 上的 Microsoft SQL Server 資料庫備份、還原及還原
** 所有作業只能透過 REST API 支援。


* SAP HANA 系統
+
** 在系統重新整理期間、會使用工作流程而非指令碼來自動掛載和卸載磁碟區
** 支援新增、移除、編輯、刪除、維護、 並使用 UI 升級外掛主機






=== 應用程式（混合式） BlueXP 備份與還原的增強功能

* 支援資料鎖定和勒索軟體保護
* 支援將備份從 StorageGRID 移至歸檔層
* 支援備份 MongoDB 、 MySQL 和 PostgreSQL 應用程式資料、從內部部署的 ONTAP 系統、到 Amazon Web Services 、 Microsoft Azure 、 Google Cloud Platform 和 StorageGRID 。您可以在必要時還原資料。




=== 虛擬機器的 BlueXP 備份與還原增強功能

* 支援 Connector Proxy 部署模式




== 2023 年 9 月 11 日



=== ONTAP 資料的新原則管理

此版本包含 UI 內的功能、可建立自訂的 Snapshot 原則、複寫原則、以及將 ONTAP 資料備份至物件儲存區的原則。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["深入瞭解原則"]。



=== 支援從 ONTAP S3 物件儲存區的磁碟區還原檔案和資料夾

以前、當磁碟區備份到 ONTAP S3 物件儲存時、您無法使用「瀏覽與還原」功能還原檔案和資料夾。此版本可移除此限制。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["深入瞭解還原資料"]。



=== 能夠立即歸檔備份資料、而非先寫入標準儲存設備

現在您可以立即將備份檔案傳送至歸檔儲存設備、而非將資料寫入標準雲端儲存設備。這對很少需要從雲端備份存取資料的使用者或是更換磁帶環境備份的使用者而言特別有幫助。



=== 額外支援備份與還原 SnapLock Volume

備份與還原現在可以備份使用 SnapLock Enterprise 保護模式設定的 FlexVol 和 FlexGroup 磁碟區。您的叢集必須執行 ONTAP 9.14 或更新版本、才能獲得此支援。自 ONTAP 9.11.1 版起、就支援使用 SnapLock 企業模式備份 FlexVol Volume 。較早的 ONTAP 版本不支援備份 SnapLock 保護磁碟區。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["深入瞭解如何保護 ONTAP 資料"]。



== 2023 年 8 月 1 日

[IMPORTANT]
====
* 由於 Connector 具備重要的安全性增強功能、因此現在需要透過外部網際網路存取額外的端點、才能在公有雲環境中管理備份與還原資源。如果此端點尚未新增至防火牆的「允許」清單、您會在 UI 中看到「服務無法使用」或「無法判斷服務狀態」的錯誤：
+
\https://netapp-cloud-account.auth0.com

* 現在當您使用「 CVO 專業版」套件時、您必須訂閱備份與還原 PAYGO 、才能套裝 Cloud Volumes ONTAP 與 BlueXP 備份與還原。過去並不需要這麼做。符合資格的 Cloud Volumes ONTAP 系統的備份與還原訂閱不會產生任何費用、但在任何新磁碟區上設定備份時都需要付費。


====


=== 新增支援功能、可將磁碟區備份至 S3 組態 ONTAP 系統上的貯體

現在您可以使用已設定為簡易儲存服務（ S3 ）的 ONTAP 系統、將磁碟區備份至物件儲存。內部部署 ONTAP 系統和 Cloud Volumes ONTAP 系統皆支援此功能。此組態可在雲端部署和內部部署位置中支援、無需網際網路存取（「私有」模式部署）。

ifdef::aws[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["深入瞭解"]。

endif::aws[]



=== 現在您可以在備份檔案中加入受保護磁碟區的現有 Snapshot

過去、您可以在初始備份檔案中將現有的 Snapshot 複本從讀寫磁碟區納入物件儲存區（而非從最新的 Snapshot 複本開始）。備份檔案中不包含來自唯讀磁碟區（資料保護磁碟區）的現有 Snapshot 複本。現在您可以選擇在「 DP 」磁碟區的備份檔案中包含較舊的 Snapshot 複本。

備份精靈會在備份步驟結束時顯示提示、您可以在其中選取這些「現有的快照」。



=== BlueXP 備份與還原不再支援未來新增的磁碟區自動備份

以前、您可以勾選備份精靈中的方塊、將選取的備份原則套用至未來新增至叢集的所有磁碟區。此功能已根據使用者的意見反應及缺乏使用此功能而移除。您需要手動啟用新增至叢集的任何新磁碟區備份。



=== 「工作監控」頁面已更新為新功能

「工作監控」頁面現在提供有關 3-2-1 備份策略的更多資訊。此服務也會提供與備份策略相關的其他警示通知。

「備份生命週期」類型篩選器已重新命名為「保留」。使用此篩選器可追蹤備份生命週期、並識別所有備份複本的到期日。「保留」工作類型會擷取在受 BlueXP 備份與還原保護的磁碟區上所起始的所有 Snapshot 刪除工作。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["深入瞭解更新的工作監控器"]。



== 2023 年 7 月 6 日



=== BlueXP 備份與還原現在包括排程及建立 Snapshot 複本與複寫磁碟區的能力

BlueXP 備份與還原現在可讓您實作 3-2-1 策略、讓您在 2 個不同的儲存系統上擁有 3 個來源資料複本、並在雲端中擁有 1 個複本。啟動之後、您將會看到：

* 來源系統上磁碟區的快照複本
* 在不同的儲存系統上複寫磁碟區
* 備份物件儲存區中的磁碟區


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["深入瞭解全新的全頻備份與還原功能"]。

這項新功能也適用於恢復作業。您可以從 Snapshot 複本、複製的磁碟區或雲端的備份檔案執行還原作業。如此一來、您就能靈活選擇符合恢復需求的備份檔案、包括恢復成本和速度。

請注意、這項新功能和使用者介面僅支援執行 ONTAP 9.8 或更新版本的叢集。如果您的叢集有舊版軟體、您可以繼續使用舊版 BlueXP 備份與還原。不過、我們建議您升級至支援的 ONTAP 版本、以取得最新的功能和功能。若要繼續使用舊版軟體、請遵循下列步驟：

. 從* Volumes（磁碟區）*索引標籤、選取* Backup Settings*（備份設定）。
. 從 _ 備份設定 _ 頁面、按一下 * 顯示先前 BlueXP 備份與還原版本 * 的選項按鈕。
+
然後您可以使用舊版軟體來管理舊叢集。





=== 能夠建立儲存容器以備份至物件儲存設備

當您在物件儲存區中建立備份檔案時、根據預設、備份與還原服務會為您在物件儲存區中建立儲存區。如果您想要使用特定名稱或指派特殊屬性、可以自行建立貯體。如果您想要建立自己的貯體、則必須先建立貯體、然後再啟動啟動精靈。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["瞭解如何建立物件儲存貯體"]。

目前不支援將備份檔案建立至 StorageGRID 系統時使用此功能。



== 2023 年 7 月 4 日



=== 應用程式（雲端原生）的 BlueXP 備份與還原功能增強功能

* SAP HANA 系統
+
** 支援非資料磁碟區和具有 Azure NetApp Files 次要保護的全域非資料磁碟區的連線和複本還原


* Oracle資料庫
+
** 支援將 Azure NetApp Files 上的 Oracle 資料庫還原至其他位置
** 支援 Oracle Recovery Manager （ RMAN ）在 Azure NetApp Files 上分類備份 Oracle 資料庫
** 可讓您將資料庫主機設為維護模式、以執行維護工作






=== 應用程式（混合式） BlueXP 備份與還原的增強功能

* 支援還原至其他位置
* 可讓您掛載 Oracle 資料庫備份
* 支援將備份從 GCP 移至歸檔層




=== 虛擬機器（混合式） BlueXP 備份與還原的增強功能

* 支援 NFS 和 VMFS 類型的資料存放區保護
* 可讓您取消登錄 VMware vSphere 主機的 SnapCenter 外掛程式
* 支援重新整理及探索最新的資料存放區和備份




== 2023 年 6 月 5 日



=== FlexGroup 磁碟區可以使用 DataLock 和勒索軟體保護來備份和保護

FlexGroup Volume 的備份原則現在可以在叢集執行 ONTAP 9.13.1 或更新版本時、使用 DataLock 和勒索軟體保護。



=== 新的報告功能

現在有一個「報告」索引標籤、您可以在其中產生「備份庫存」報告、其中包括特定帳戶、工作環境或 SVM 庫存的所有備份。您也可以建立「資料保護工作活動」報告、提供有關 Snapshot 、備份、複製和還原作業的資訊、協助您監控服務層級協議。請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["報告資料保護涵蓋範圍"]。



=== 工作監控增強功能

您現在可以在「工作監控」頁面上檢閱 _backup 生命週期 _ 做為工作類型、協助您追蹤整個備份生命週期。您也可以在 BlueXP 時間軸上查看所有作業的詳細資料。請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["監控備份與還原工作的狀態"]。



=== 不相符原則標籤的額外通知警示

新增了備份警示：「 Snapshot 原則標籤不相符、因此未建立備份檔案」。如果備份原則中定義的 _label_ 在 Snapshot 原則中沒有相符的 _label_ 、則不會建立備份檔案。您需要使用系統管理員或 ONTAP CLI 、將遺失的標籤新增至 Volume Snapshot 原則。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["檢閱 BlueXP 備份與還原可以傳送的所有警示"]。



=== 自動備份黑暗網站中的關鍵 BlueXP 備份與還原檔案

當您在無法存取網際網路的站台（稱為「私有模式」部署）中使用 BlueXP 備份與還原時、 BlueXP 備份與還原資訊只會儲存在本機 Connector 系統上。這項新功能會自動將重要的 BlueXP 備份與還原資料備份至連線 StorageGRID 系統上的儲存庫、以便在必要時將資料還原至新的 Connector 。 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["深入瞭解"]



== 2023 年 5 月 8 日



=== 資料夾層級的還原作業現在可從歸檔儲存設備和鎖定的備份中獲得支援

如果備份檔案已設定為 DataLock 和勒索軟體保護、或是備份檔案位於歸檔儲存區、則當叢集執行 ONTAP 9.13.1 或更新版本時、現在支援資料夾層級的還原作業。



=== 將磁碟區備份至 Google Cloud 時、支援跨區域和跨專案客戶管理的金鑰

現在您可以選擇與客戶管理的加密金鑰（ CMEK ）專案不同的儲存庫。

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["深入瞭解如何設定您自己的客戶管理加密金鑰"]。

endif::gcp[]



=== AWS 中國地區現在支援備份檔案

如果叢集執行的是 ONTAP 9.12.1 或更新版本、則 AWS 中國北京（ CN-north-1 ）和寧夏（ CN-n前來 -1 ）地區現在都支援做為備份檔案的目的地。

請注意、指派給 BlueXP Connector 的 IAM 原則需要將所有 _Resource_ 區段下的 AWS 資源名稱「 arn 」從「 AWS 」變更為「 AWS-CN 」、例如「 arn:AWS-CN:S3 ：：：： NetApp-backup-* 」。

ifdef::aws[]

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["將 Cloud Volumes ONTAP 資料備份至 Amazon S3"] 和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["將內部部署 ONTAP 資料備份至 Amazon S3"] 。

endif::aws[]



=== 工作監控的增強功能

系統啟動的工作（例如持續的備份作業）現在可在 * 工作監控 * 標籤中找到、適用於執行 ONTAP 9.13.1 或更新版本的內部部署 ONTAP 系統。舊版 ONTAP 只會顯示使用者啟動的工作。



== 2023 年 4 月 14 日



=== 應用程式（雲端原生）的 BlueXP 備份與還原功能增強功能

* SAP HANA資料庫
+
** 支援指令碼型系統重新整理
** 如果已設定 Azure NetApp Files 備份、則支援單一檔案快照還原
** 支援外掛程式升級


* Oracle資料庫
+
** 透過簡化非 root Sudo 使用者組態、增強外掛程式部署功能
** 支援外掛程式升級
** 支援 Azure NetApp Files 上 Oracle 資料庫的自動探索和原則導向保護
** 支援將 Oracle 資料庫還原至原始位置、並提供精細的還原功能






=== 應用程式（混合式） BlueXP 備份與還原的增強功能

* 應用程式（混合式）的 BlueXP 備份與還原是從 SaaS 控制層面驅動
* 修改混合式 REST API 以符合雲端原生 API 。
* 支援電子郵件通知




== 2023 年 4 月 4 日



=== 能夠以「受限」模式、從 Cloud Volumes ONTAP 系統將資料備份到雲端

現在您可以在「受限模式」下、從安裝在 AWS 、 Azure 和 GCP 商業區域的 Cloud Volumes ONTAP 系統備份資料。這需要您先在「受限」商業區域安裝 Connector 。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["深入瞭解 BlueXP 部署模式"^]。

ifdef::aws[]

請參閱 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["將Cloud Volumes ONTAP 不支援的資料備份至Amazon S3"]

endif::aws[]

ifdef::azure[]

請參閱。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["將Cloud Volumes ONTAP 無法取得的資料備份到Azure Blob"]

endif::azure[]



=== 能夠使用 API 將內部部署的 ONTAP 磁碟區備份至 ONTAP S3

API 的新功能可讓您使用 BlueXP 備份與還原、將磁碟區快照備份至 ONTAP S3 。此功能目前僅適用於內部部署 ONTAP 系統。如需詳細指示、請參閱部落格 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["與 ONTAP S3 整合為目的地"^]。



=== 能夠將 Azure 儲存帳戶的區域備援層面從 LRS 變更為 ZRS

從 Cloud Volumes ONTAP 系統建立備份至 Azure 儲存設備時、 BlueXP 備份與還原預設會將 Blob 容器與本機備援（ LRS ）一起配置、以達到成本最佳化。如果您想要在不同區域之間複寫資料、可以將此設定變更為區域備援（ ZRS ）。請參閱的 Microsoft 指示 https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["變更儲存帳戶的複寫方式"^]。



=== 工作監控的增強功能

* 從 BlueXP 備份與還原 UI 和 API 啟動的使用者初始化備份與還原作業、以及系統起始的工作（例如持續的備份作業）、現在都可在執行 ONTAP 9.13.0 或更新版本的 Cloud Volumes ONTAP 系統的 * 工作監控 * 標籤中取得。舊版 ONTAP 只會顯示使用者啟動的工作。
* 除了能夠下載 CSV 檔案來報告所有工作之外、現在您可以下載 JSON 檔案來處理單一工作、並查看其詳細資料。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["深入瞭解"]。
* 新增兩個備份工作警示：「排程工作失敗」和「還原工作完成但有警告」。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["檢閱 BlueXP 備份與還原可以傳送的所有警示"]。




== 2023年3月9日



=== 資料夾層級的還原作業現在包括所有子資料夾和檔案

過去當您還原資料夾時、只會還原該資料夾中的檔案、子資料夾中的任何子資料夾或檔案都不會還原。現在、如果您使用ONTAP 的是更新版本的版本、則會還原所選資料夾中的所有子資料夾和檔案。如果您在頂層資料夾中有多個巢狀資料夾、這可節省大量時間與金錢。



=== 能夠在具有有限輸出連線能力的站台中、從 Cloud Volumes ONTAP 系統備份資料

現在、您可以將Cloud Volumes ONTAP 安裝在AWS和Azure商業區域的支援資料系統備份到Amazon S3或Azure Blob。這需要您在商業地區的 Linux 主機上以「受限模式」安裝 Connector 、並在該處部署 Cloud Volumes ONTAP 系統。

ifdef::aws[]

請參閱。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["將Cloud Volumes ONTAP 不支援的資料備份至Amazon S3"]

endif::aws[]

ifdef::azure[]

請參閱。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["將Cloud Volumes ONTAP 無法取得的資料備份到Azure Blob"]

endif::azure[]



=== 工作監控器的多項增強功能

* 「工作監控」頁面已新增進階篩選功能、可讓您依時間、工作負載（磁碟區、應用程式或虛擬機器）、工作類型、 狀態、工作環境和儲存 VM 。您也可以輸入任意文字來搜尋任何資源、例如「application_3」。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["瞭解如何使用進階篩選器"]。
* 從 BlueXP 備份與還原 UI 和 API 啟動的使用者初始化備份與還原作業、以及系統起始的工作（例如持續的備份作業）、現在都可在執行 ONTAP 9.13.0 或更新版本的 Cloud Volumes ONTAP 系統的 * 工作監控 * 標籤中取得。早期版本Cloud Volumes ONTAP 的不一致系統和內部部署ONTAP 的不一致系統、目前只會顯示使用者啟動的工作。




== 2023年2月6日



=== 能夠將較舊的備份檔案從StorageGRID 無法還原的系統移至Azure歸檔儲存設備

現在、您可以將舊版備份檔案分層、從StorageGRID 無法更新的系統到Azure中的歸檔儲存設備。如此一來StorageGRID 、您就能釋出整個作業系統的空間、並使用經濟實惠的儲存類別來儲存舊的備份檔案、進而節省成本。

如果內部叢集使用ONTAP 的是更新版本的版本、StorageGRID 而您的系統使用的是11.4或更新版本、則可使用此功能。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["如需詳細資訊、請參閱此處"^]。



=== 您可以在Azure Blob中設定DataLock和勒索軟體保護功能、以供備份檔案使用

Azure Blob儲存的備份檔案現在支援DataLock和勒索軟體保護。如果Cloud Volumes ONTAP 您的支援對象ONTAP 為執行ONTAP 支援的支援對象、那麼您現在可以鎖定備份檔案、然後掃描檔案、以偵測可能的勒索軟體。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["深入瞭解如何使用DataLock和勒索軟體保護來保護備份"^]。



=== 備份與還原FlexGroup 功能強化功能

* 現在、您可以在還原FlexGroup 完一個功能區時、選擇多個集合體。在最後一個版本中、您只能選取單一Aggregate。
* 目前支援在不支援的系統上進行還原Cloud Volumes ONTAP FlexGroup 。在上一版中、您只能還原到內部ONTAP 的作業系統。




=== 可將舊版備份移至Google Archival儲存設備Cloud Volumes ONTAP

備份檔案最初是在Google Standard儲存類別中建立。現在您可以使用 BlueXP 備份與還原、將舊備份分層化至 Google Archive 儲存設備、以進一步最佳化成本。上一版僅支援內部ONTAP 使用的功能、目前Cloud Volumes ONTAP 支援部署在Google Cloud上的各種系統。



=== Volume Restore作業現在可讓您選取要還原Volume資料的SVM

現在您可以將Volume資料還原至ONTAP 您的叢集中的不同儲存VM。過去無法選擇儲存VM。



=== 增強支援以支援各種形式進行的Volume MetroCluster

當使用ONTAP 的是版本號為《支援使用支援的功能》（例如《支援使用支援的功能》）的更新版本時、系統會以MetroCluster 「支援的功能」的形式連接至主系統。整個備份組態會傳輸到次要系統、以便在切換後自動繼續備份到雲端。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["如需詳細資訊、請參閱備份限制"]。



== 2023年1月9日



=== 能夠將較舊的備份檔案從StorageGRID 支援系統移至AWS S3歸檔儲存設備

現在您可以將舊的備份檔案分層、從StorageGRID 支援的系統、到AWS S3的歸檔儲存設備。如此一來StorageGRID 、您就能釋出整個作業系統的空間、並使用經濟實惠的儲存類別來儲存舊的備份檔案、進而節省成本。您可以選擇將備份分層至AWS S3 Glacier或S3 Glacier Deep Archive儲存設備。

如果內部叢集使用ONTAP 的是更新版本的版本、StorageGRID 而您的系統使用的是11.3或更新版本、則可使用此功能。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["如需詳細資訊、請參閱此處"]。



=== 能夠在Google Cloud上選擇您自己的客戶管理金鑰來進行資料加密

將ONTAP 資料從您的支援系統備份到Google Cloud Storage時、現在您可以在啟動精靈中選擇自己的客戶管理金鑰來進行資料加密、而不使用預設的Google管理加密金鑰。只要先在 Google 中設定客戶管理的加密金鑰、然後在啟動 BlueXP 備份與還原時輸入詳細資料即可。



=== 服務帳戶不再需要「儲存管理員」角色、即可在Google Cloud Storage中建立備份

在舊版中、服務帳戶需要「儲存管理員」角色、才能讓 BlueXP 備份與還原存取 Google Cloud Storage 貯體。現在您可以建立自訂角色、並減少指派給服務帳戶的權限集。

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["瞭解如何準備Google Cloud Storage進行備份"]。

endif::gcp[]



=== 我們新增支援、在沒有網際網路存取的站台中使用「搜尋與還原」來還原資料

如果您將資料從內部ONTAP 的支援叢集備份到StorageGRID 無法存取網際網路的站台（也稱為暗站或離線站台）、現在您可以使用「搜尋與還原」選項在必要時還原資料。此功能需要在離線站台部署BlueXP Connector（3.9.25版或更新版本）。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["瞭解如何ONTAP 使用Search  Restore還原資料"]。
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["瞭解如何在離線站台中安裝Connector"]。



=== 能夠下載「工作監控結果」頁面做為CSV報告

篩選「工作監控」頁面以顯示您感興趣的工作和行動之後、您現在可以產生並下載該資料的.csvs檔案。然後您可以分析資訊、或將報告傳送給組織中的其他人員。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["請參閱如何產生工作監控報告"]。



== 2022年12月19日



=== Cloud Backup for Applications的增強功能

* SAP HANA資料庫
+
** 支援以原則為基礎的SAP HANA資料庫備份與還原Azure NetApp Files 功能、這些資料庫位於支援中心
** 支援自訂原則


* Oracle資料庫
+
** 新增主機並自動部署外掛程式
** 支援自訂原則
** 支援以原則為基礎的Oracle資料庫備份、還原及複製Cloud Volumes ONTAP 、這些資料庫位於支援中心
** 支援以原則為基礎的Oracle資料庫備份與還原、這些資料庫位於Amazon FSX for NetApp ONTAP
** 支援使用連線與複製方法還原Oracle資料庫
** 支援Oracle 21c
** 支援雲端原生 Oracle 資料庫的複製






=== 增強了適用於虛擬機器的Cloud Backup功能

* 虛擬機器
+
** 從內部部署的次要儲存設備備份虛擬機器
** 支援自訂原則
** 支援Google Cloud Platform（GCP）備份一或多個資料存放區
** 支援低成本的雲端儲存設備、例如Glacier、Deep Glacier和Azure歸檔






== 2022年12月6日



=== 必要的連接器輸出網際網路存取端點變更

由於Cloud Backup有所變更、您必須變更下列Connector端點、才能成功執行Cloud Backup作業：

[cols="50,50"]
|===
| 舊端點 | 新的端點 


| \https://cloudmanager.cloud.netapp.com | \https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
請參閱的完整端點清單 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^]、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^]或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] 雲端環境：



=== 支援在UI中選取Google Archival儲存類別

備份檔案最初是在Google Standard儲存類別中建立。現在您可以使用Cloud Backup使用者介面、在特定天數後將舊備份分層至Google歸檔儲存設備、以進一步最佳化成本。

目前支援ONTAP 內部使用ONTAP 的支援功能適用於使用支援更新版本的支援功能。目前不提供Cloud Volumes ONTAP 此功能給非系統。



=== 支援FlexGroup 支援功能

Cloud Backup現在支援還原FlexGroup 及備份功能。使用ONTAP 支援更新版本的《支援資料》時、您可以將FlexGroup 《支援資料》備份到公有雲和私有雲儲存設備。如果您的工作環境包含FlexVol 了一些不含支援的功能、FlexGroup 請在更新ONTAP 完您的支援功能後、在FlexGroup 這些系統上備份任何的支援功能。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["請參閱支援的磁碟區類型完整清單"]。



=== 能夠將資料從備份還原到Cloud Volumes ONTAP 位於不受影響的系統上的特定集合體

在早期版本中、您只能在將資料還原至內部ONTAP 的資訊系統時、才選取Aggregate。此功能現在可用於將資料還原Cloud Volumes ONTAP 至還原系統。



== 2022年11月2日



=== 能夠將較舊的Snapshot複本匯出至基礎備份檔案

如果您工作環境中有任何符合備份排程標籤的Volume本機Snapshot複本（例如每日、每週等）、您可以將這些歷史快照匯出至物件儲存設備作為備份檔案。這可讓您將舊的Snapshot複本移至基礎備份複本、以初始化雲端中的備份。

在工作環境中啟動Cloud Backup時、可使用此選項。您也可以稍後在中變更此設定 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["進階設定頁面"]。



=== 雲端備份現在可用於歸檔來源系統不再需要的磁碟區

現在您可以刪除磁碟區的備份關係。如果您想要停止建立新的備份檔案並刪除來源Volume、但保留所有現有的備份檔案、這將提供歸檔機制。這可讓您在未來視需要從備份檔案還原磁碟區、同時從來源儲存系統中清除空間。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["瞭解方法"]。



=== 新增支援功能、可在電子郵件和通知中心接收Cloud Backup警示

Cloud Backup已整合至BlueXP通知服務。您可以按一下BlueXP功能表列中的通知警示、以顯示Cloud Backup通知。您也可以設定BluefXP以電子郵件傳送通知作為警示、即使您尚未登入系統、也能得知重要的系統活動。電子郵件可傳送給任何需要注意備份與還原活動的收件者。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["瞭解方法"]。



=== 「新增進階設定」頁面可讓您變更叢集層級的備份設定

此新頁面可讓您變更在啟用每ONTAP 個作業系統的Cloud Backup時所設定的許多叢集層級備份設定。您也可以修改某些套用為「預設」備份設定的設定。您可以變更的完整備份設定包括：

* 儲存金鑰可讓ONTAP 您的系統獲得存取物件儲存設備的權限
* 分配給上傳備份到物件儲存設備的網路頻寬
* 未來磁碟區的自動備份設定（和原則）
* 歸檔儲存類別（僅限AWS）
* 歷史Snapshot複本是否包含在初始基礎備份檔案中
* 是否從來源系統移除「每年」快照
* 連接至物件儲存設備的物件保護區（在啟動期間選擇不正確的情況下）ONTAP


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["深入瞭解如何管理叢集層級的備份設定"]。



=== 現在您可以使用內部部署Connector時、使用「搜尋與還原」來還原備份檔案

在先前的版本中、當您的內部部署連接器時、新增了將備份檔案建立至公有雲的支援。在此版本中、持續支援使用搜尋與還原功能、在部署連接器於內部部署時、從Amazon S3或Azure Blob還原備份。搜尋與還原功能也支援將備份從StorageGRID 還原系統還原至內部部署ONTAP 的還原系統。

此時、使用搜尋與還原從Google Cloud Storage還原備份時、必須在Google Cloud Platform中部署Connector。



=== 「工作監控」頁面已更新

已對進行下列更新 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["「工作監控」頁面"]：

* 「工作負載」欄位可供您篩選頁面、以檢視下列備份服務的工作： Volume 、 Applications 和 Virtual Machines 。
* 若要檢視特定備份工作的這些詳細資料、您可以新增「使用者名稱」和「工作類型」欄。
* 「工作詳細資料」頁面會顯示正在執行以完成主要工作的所有子工作。
* 此頁面每15分鐘自動重新整理一次、讓您隨時都能看到最新的工作狀態結果。您也可以按一下「*重新整理*」按鈕、立即更新頁面。




=== AWS跨帳戶備份增強功能

如果您想要使用不同於Cloud Volumes ONTAP 來源磁碟區的AWS帳戶進行還原備份、則必須在BluetXP中新增目的地AWS帳戶認證、而且必須將「S3：PuttBucketPolicy」和「S3：PuttetOwnershipControl」權限新增至IAM角色、以便為BlueXP提供權限。過去、您需要在AWS主控台設定許多設定、您不再需要這麼做了。



== 2022年9月28日



=== Cloud Backup for Applications的增強功能

* 支援Google Cloud Platform（GCP）和StorageGRID 支援以備份應用程式一致的快照
* 建立自訂原則
* 支援歸檔儲存
* 備份SAP HANA應用程式
* 備份VMware環境中的Oracle和SQL應用程式
* 從內部部署的二線儲存設備備份應用程式
* 停用備份
* 取消登SnapCenter 錄伺服器




=== 增強了適用於虛擬機器的Cloud Backup功能

* 支援StorageGRID 使用支援還原來備份一或多個資料存放區
* 建立自訂原則




== 2022年9月19日



=== DataLock和勒索軟體保護功能可設定用於StorageGRID 支援還原系統中的備份檔案

上一版針對儲存在Amazon S3儲存區的備份推出_DataLock和勒索軟體Protection。此版本可擴充對StorageGRID 儲存在還原系統中的備份檔案的支援。如果您的叢集使用ONTAP 的是更新版本的版本、StorageGRID 而您的系統執行的是11.6.0.3或更新版本、則可使用此新的備份原則選項。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["深入瞭解如何使用DataLock和勒索軟體保護來保護備份"^]。

請注意、您必須執行3.9.22版或更新版本軟體的Connector。連接器必須安裝在您的內部環境中、而且可以安裝在有或沒有網際網路存取的站台中。



=== 資料夾層級的還原功能現在可從您的備份檔案取得

現在、如果您需要存取該資料夾（目錄或共用）中的所有檔案、可以從備份檔案還原資料夾。還原資料夾比還原整個磁碟區更有效率。此功能可用於使用瀏覽與還原方法及使用ONTAP 版本更新版本的搜尋與還原方法進行還原作業。此時您只能選取及還原單一資料夾、而且只會還原該資料夾中的檔案、而不會還原子資料夾或子資料夾中的檔案。



=== 檔案層級還原現在可從已移至歸檔儲存設備的備份取得

過去您只能從已移至歸檔儲存設備的備份檔案還原磁碟區（僅限AWS和Azure）。現在您可以從這些已歸檔的備份檔案還原個別檔案。此功能可用於使用瀏覽與還原方法及使用ONTAP 版本更新版本的搜尋與還原方法進行還原作業。



=== 檔案層級還原現在提供覆寫原始來源檔案的選項

過去、還原至原始磁碟區的檔案一律會以新檔案的形式還原、並以「RESE_」為前置詞。現在、您可以選擇在將檔案還原至磁碟區上的原始位置時、覆寫原始來源檔案。此功能可用於使用「瀏覽與還原」方法和「搜尋與還原」方法進行還原作業。



=== 拖放以啟用「雲端備份至StorageGRID 不支援的系統」

如果是 https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 備份的目的地在畫版上會以工作環境的形式存在、您可以將內部ONTAP 作業環境拖曳到目的地、以啟動Cloud Backup設定精靈。
