= 增強型ONTAP卷儀表板
:allow-uri-read: 




=== 增強型ONTAP卷儀表板

2025 年 4 月，我們推出了增強型ONTAP卷儀表板的預覽版，它速度更快、更有效率。

此儀表板旨在協助企業客戶處理大量工作負載。即使對於擁有 20,000 個卷的客戶，新儀表板也能在 10 秒內加載完成。

預覽版成功上線，並獲得了許多預覽版用戶的正面回饋，我們現已將其設為所有客戶的預設體驗。準備好迎接極速儀表板吧！

如需詳細資訊、請參閱 link:br-use-dashboard.html["在儀表板中查看保護健康狀況"]。



=== Microsoft SQL Server 工作負載支援作為公共技術預覽

此版本的BlueXP backup and recovery提供了更新的使用者介面，可讓您使用BlueXP backup and recovery服務中熟悉的 3-2-1 保護策略來管理 Microsoft SQL Server 工作負載。使用此新版本，您可以將這些工作負載備份到主存儲，複製到輔助存儲，然後備份到雲端物件儲存。

您可以透過完成此步驟註冊預覽 https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["預覽註冊表"^] 。


NOTE: 本文檔是關於保護微軟 SQL SERVER 工作負載的，作為技術預覽提供。透過此預覽方案、 NetApp 保留在「一般供應」之前修改產品詳細資料、內容和時間表的權利。

此版本的BlueXP backup and recovery包括以下更新：

* *3-2-1 備份功能*：此版本整合了SnapCenter功能，讓您能夠透過BlueXP backup and recovery使用者介面使用 3-2-1 資料保護策略來管理和保護您的SnapCenter資源。
* *從SnapCenter匯入*：您可以將SnapCenter備份資料和原則匯入BlueXP backup and recovery。
* *重新設計的使用者介面*為管理備份和復原任務提供了更直覺的體驗。
* *備份目標*：您可以在 Amazon Web Services (AWS)、Microsoft Azure Blob Storage、 StorageGRID和ONTAP S3 環境中新增儲存桶，以用作 Microsoft SQL Server 工作負載的備份目標。
* *工作負載支援*：此版本支援您備份、還原、驗證和複製 Microsoft SQL Server 資料庫和可用性群組。（未來版本將添加對其他工作負載的支援。）
* *靈活的復原選項*：此版本可讓您在發生損壞或意外資料遺失的情況下將資料庫還原至原始位置和備用位置。
* *即時生產副本*：在幾分鐘內（而不是幾小時或幾天）產生用於開發、測試或分析的節省空間的生產副本。
* 此版本包括建立詳細報告的功能。


有關保護 Microsoft SQL Server 工作負載的詳細信息，請參閱link:br-use-mssql-protect-overview.html["保護 Microsoft SQL Server 工作負載概述"] 。
