= 高效能索引
:allow-uri-read: 




=== 高效能索引

BlueXP  備份與還原引進更新的索引功能，可讓來源工作環境上的資料索引更有效率。新的索引功能包括 UI 更新，還原資料的「搜尋與還原」方法效能提升，全球搜尋功能升級，擴充性更佳。

以下是改善項目的細目：

* * 資料夾整合 * ：更新版本會使用包含特定識別碼的名稱將資料夾群組在一起，使索引程序更順暢。
* * 硬碟檔案壓縮 * ：更新版本可減少用於建立每個磁碟區索引的檔案數量，簡化程序並免除額外資料庫的需求。
* * 以更多工作階段進行橫向擴充 * ：新版本新增更多工作階段來處理索引工作，加速程序。
* * 支援多個索引容器 * ：新版本使用多個容器來更好地管理及散佈索引工作。
* * 分割索引工作流程 * ：新版本將索引程序分為兩個部分，以提升效率。
* * 改善的並行處理 * ：新版本可同時刪除或移動目錄，加速索引程序。


.誰能從這項功能中獲益？
所有新客戶都能使用新的索引功能。

.如何啟用索引？
在您使用「搜尋與還原」方法還原資料之前，您必須先在每個準備還原磁碟區或檔案的來源工作環境上啟用「索引」。這可讓「索引型錄」追蹤每個磁碟區和每個備份檔案，讓您的搜尋快速又有效率。

執行「搜尋與還原」時，選取「啟用索引」選項，即可在來源工作環境上啟用索引。

有關詳細信息，請參閱文檔 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["如何使用搜尋擴大機還原 ONTAP 資料；還原"]。

.支援的擴充
新的索引功能支援下列項目：

* 不到 3 分鐘即可達到全域搜尋效率
* 多達 50 億個檔案
* 每個叢集最多 5000 個磁碟區
* 每個磁碟區最多可有 1 ，上限的快照
* 基準索引的最長時間少於 7 天。實際時間會因您的環境而異。




=== 全球搜尋效能提升

此版本也包含全球搜尋效能的增強功能。現在您將看到進度指標和更詳細的搜尋結果，包括檔案數和搜尋所需時間。專屬的搜尋和索引容器可確保在五分鐘內完成全域搜尋。

請注意下列與全域搜尋相關的考量事項：

* 新索引不會在標示為每小時的快照上執行。
* 新的索引功能僅適用於 FlexVols 上的快照，不適用於 FlexGroups 上的快照。

